"""OpenFMB ``reclosermodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class Recloser(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.Recloser``."""
    PROTO: ClassVar[str] = 'reclosermodule.Recloser'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})
    normalOpen: bool | None = Field(default=None, json_schema_extra={'proto': 'google.protobuf.BoolValue', 'wrapper': 'BoolValue'})

class RecloserDiscreteControlXCBR(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.RecloserDiscreteControlXCBR``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserDiscreteControlXCBR'
    discreteControlXCBR: _common_module.DiscreteControlXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.DiscreteControlXCBR'})

class RecloserDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.RecloserDiscreteControl``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    recloserDiscreteControlXCBR: RecloserDiscreteControlXCBR | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.RecloserDiscreteControlXCBR'})

class RecloserDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``reclosermodule.RecloserDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    recloser: Recloser | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.Recloser'})
    recloserDiscreteControl: RecloserDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.RecloserDiscreteControl'})

class RecloserEvent(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.RecloserEvent``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    statusAndEventXCBR: _common_module.StatusAndEventXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusAndEventXCBR'})

class RecloserEventProfile(OpenFMBMessage):
    """OpenFMB profile ``reclosermodule.RecloserEventProfile``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    recloser: Recloser | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.Recloser'})
    recloserEvent: RecloserEvent | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.RecloserEvent'})

class RecloserReading(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.RecloserReading``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    diffReadingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class RecloserReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``reclosermodule.RecloserReadingProfile``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    recloser: Recloser | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.Recloser'})
    recloserReading: list[RecloserReading] = Field(default_factory=list, json_schema_extra={'proto': 'reclosermodule.RecloserReading'})

class RecloserStatus(OpenFMBMessage):
    """OpenFMB message ``reclosermodule.RecloserStatus``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    statusAndEventXCBR: _common_module.StatusAndEventXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusAndEventXCBR'})

class RecloserStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``reclosermodule.RecloserStatusProfile``."""
    PROTO: ClassVar[str] = 'reclosermodule.RecloserStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    recloser: Recloser | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.Recloser'})
    recloserStatus: RecloserStatus | None = Field(default=None, json_schema_extra={'proto': 'reclosermodule.RecloserStatus'})


PROFILES = {'RecloserDiscreteControlProfile': RecloserDiscreteControlProfile, 'RecloserEventProfile': RecloserEventProfile, 'RecloserReadingProfile': RecloserReadingProfile, 'RecloserStatusProfile': RecloserStatusProfile}
__all__ = ['Recloser', 'RecloserDiscreteControl', 'RecloserDiscreteControlProfile', 'RecloserDiscreteControlXCBR', 'RecloserEvent', 'RecloserEventProfile', 'RecloserReading', 'RecloserReadingProfile', 'RecloserStatus', 'RecloserStatusProfile']
