"""OpenFMB ``solarmodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class SolarPoint(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarPoint``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarPoint'
    mode: _common_module.ENG_GridConnectModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENG_GridConnectModeKind'})
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    reset: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})
    enterServiceOperation: _common_module.EnterServiceAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnterServiceAPC'})
    hzWOperation: _common_module.HzWAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.HzWAPC'})
    limitWOperation: _common_module.LimitWAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LimitWAPC'})
    pFOperation: _common_module.PFSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PFSPC'})
    tmHzTripOperation: _common_module.TmHzCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.TmHzCSG'})
    tmVoltTripOperation: _common_module.TmVoltCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.TmVoltCSG'})
    vArOperation: _common_module.VarSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VarSPC'})
    voltVarOperation: _common_module.VoltVarCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VoltVarCSG'})
    voltWOperation: _common_module.VoltWCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VoltWCSG'})
    wVarOperation: _common_module.WVarCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.WVarCSG'})
    blackStartEnabled: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    wOperation: _common_module.WSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.WSPC'})

class SolarCurvePoint(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCurvePoint``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCurvePoint'
    control: SolarPoint | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarPoint'})
    startTime: _common_module.ControlTimestamp | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlTimestamp'})

class SolarCSG(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCSG``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCSG'
    crvPts: list[SolarCurvePoint] = Field(default_factory=list, json_schema_extra={'proto': 'solarmodule.SolarCurvePoint'})

class SolarCapabilityConfiguration(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCapabilityConfiguration``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapabilityConfiguration'
    sourceCapabilityConfiguration: _common_module.SourceCapabilityConfiguration | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.SourceCapabilityConfiguration'})

class SolarCapabilityRatings(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCapabilityRatings``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapabilityRatings'
    sourceCapabilityRatings: _common_module.SourceCapabilityRatings | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.SourceCapabilityRatings'})

class SolarCapability(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCapability``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapability'
    nameplateValue: _common_module.NameplateValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.NameplateValue'})
    solarCapabilityConfiguration: SolarCapabilityConfiguration | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCapabilityConfiguration'})
    solarCapabilityRatings: SolarCapabilityRatings | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCapabilityRatings'})

class SolarCapabilityOverride(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarCapabilityOverride``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapabilityOverride'
    identifiedObject: _common_module.IdentifiedObject | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.IdentifiedObject'})
    solarCapabilityConfiguration: SolarCapabilityConfiguration | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCapabilityConfiguration'})

class SolarInverter(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarInverter``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarInverter'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})

class SolarCapabilityOverrideProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarCapabilityOverrideProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapabilityOverrideProfile'
    PROFILE: ClassVar[bool] = True
    capabilityMessageInfo: _common_module.CapabilityMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CapabilityMessageInfo'})
    solarCapabilityOverride: SolarCapabilityOverride | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCapabilityOverride'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})

class SolarCapabilityProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarCapabilityProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarCapabilityProfile'
    PROFILE: ClassVar[bool] = True
    capabilityMessageInfo: _common_module.CapabilityMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CapabilityMessageInfo'})
    solarCapability: SolarCapability | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCapability'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})

class SolarControlScheduleFSCH(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarControlScheduleFSCH``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarControlScheduleFSCH'
    ValDCSG: SolarCSG | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarCSG'})

class SolarControlFSCC(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarControlFSCC``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarControlFSCC'
    controlFSCC: _common_module.ControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlFSCC'})
    SolarControlScheduleFSCH_: SolarControlScheduleFSCH | None = Field(default=None, alias='SolarControlScheduleFSCH', json_schema_extra={'proto': 'solarmodule.SolarControlScheduleFSCH'})

class SolarControl(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarControl``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    solarControlFSCC: SolarControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarControlFSCC'})

class SolarControlProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarControlProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    solarControl: SolarControl | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarControl'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})

class SolarDiscreteControlPV(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarDiscreteControlPV``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarDiscreteControlPV'
    logicalNodeForControl: _common_module.LogicalNodeForControl | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForControl'})
    control: SolarPoint | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarPoint'})

class SolarDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarDiscreteControl``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    solarDiscreteControlPV: SolarDiscreteControlPV | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarDiscreteControlPV'})

class SolarDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    solarDiscreteControl: SolarDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarDiscreteControl'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})

class SolarPointStatus(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarPointStatus``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarPointStatus'
    frequencySetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    mode: _common_module.ENG_GridConnectModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENG_GridConnectModeKind'})
    pctHzDroop: float | None = Field(default=None, json_schema_extra={'proto': 'google.protobuf.FloatValue', 'wrapper': 'FloatValue'})
    pctVDroop: float | None = Field(default=None, json_schema_extra={'proto': 'google.protobuf.FloatValue', 'wrapper': 'FloatValue'})
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    reactivePwrSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    realPwrSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})
    voltageSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    blackStartEnabled: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    enterServiceOperation: _common_module.EnterServiceAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnterServiceAPC'})
    hzWOperation: _common_module.HzWPoint | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.HzWPoint'})
    limitWOperation: _common_module.LimitWAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LimitWAPC'})
    pFOperation: _common_module.PFSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PFSPC'})
    syncBackToGrid: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    tmHzTripOperation: _common_module.TmHzCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.TmHzCSG'})
    tmVoltTripOperation: _common_module.TmVoltCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.TmVoltCSG'})
    vArOperation: _common_module.VarSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VarSPC'})
    voltVarOperation: _common_module.VoltVarCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VoltVarCSG'})
    voltWOperation: _common_module.VoltWCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VoltWCSG'})
    wVarOperation: _common_module.WVarCSG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.WVarCSG'})

class SolarEventAndStatusZGEN(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarEventAndStatusZGEN``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarEventAndStatusZGEN'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    AuxPwrSt: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    EmgStop: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    PointStatus: SolarPointStatus | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarPointStatus'})
    Alrm: _common_module.Optional_AlrmKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_AlrmKind'})
    GnSynSt: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    GridConnectionState: _common_module.Optional_GridConnectionStateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_GridConnectionStateKind'})
    ManAlrmInfo: str | None = Field(default=None, json_schema_extra={'proto': 'google.protobuf.StringValue', 'wrapper': 'StringValue'})
    OperatingState: _common_module.Optional_OperatingStateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_OperatingStateKind'})

class SolarEventZGEN(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarEventZGEN``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarEventZGEN'
    solarEventAndStatusZGEN: SolarEventAndStatusZGEN | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarEventAndStatusZGEN'})
    GriMod: _common_module.ENG_GridConnectModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENG_GridConnectModeKind'})

class SolarEvent(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarEvent``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    solarEventZGEN: SolarEventZGEN | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarEventZGEN'})

class SolarEventProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarEventProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    solarEvent: SolarEvent | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarEvent'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})

class SolarReading(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarReading``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class SolarReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarReadingProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})
    solarReading: SolarReading | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarReading'})

class SolarStatusZGEN(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarStatusZGEN``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarStatusZGEN'
    solarEventAndStatusZGEN: SolarEventAndStatusZGEN | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarEventAndStatusZGEN'})
    GriMod: _common_module.ENG_GridConnectModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENG_GridConnectModeKind'})

class SolarStatus(OpenFMBMessage):
    """OpenFMB message ``solarmodule.SolarStatus``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    solarStatusZGEN: SolarStatusZGEN | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarStatusZGEN'})

class SolarStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``solarmodule.SolarStatusProfile``."""
    PROTO: ClassVar[str] = 'solarmodule.SolarStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    solarInverter: SolarInverter | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarInverter'})
    solarStatus: SolarStatus | None = Field(default=None, json_schema_extra={'proto': 'solarmodule.SolarStatus'})


PROFILES = {'SolarCapabilityOverrideProfile': SolarCapabilityOverrideProfile, 'SolarCapabilityProfile': SolarCapabilityProfile, 'SolarControlProfile': SolarControlProfile, 'SolarDiscreteControlProfile': SolarDiscreteControlProfile, 'SolarEventProfile': SolarEventProfile, 'SolarReadingProfile': SolarReadingProfile, 'SolarStatusProfile': SolarStatusProfile}
__all__ = ['SolarCSG', 'SolarCapability', 'SolarCapabilityConfiguration', 'SolarCapabilityOverride', 'SolarCapabilityOverrideProfile', 'SolarCapabilityProfile', 'SolarCapabilityRatings', 'SolarControl', 'SolarControlFSCC', 'SolarControlProfile', 'SolarControlScheduleFSCH', 'SolarCurvePoint', 'SolarDiscreteControl', 'SolarDiscreteControlPV', 'SolarDiscreteControlProfile', 'SolarEvent', 'SolarEventAndStatusZGEN', 'SolarEventProfile', 'SolarEventZGEN', 'SolarInverter', 'SolarPoint', 'SolarPointStatus', 'SolarReading', 'SolarReadingProfile', 'SolarStatus', 'SolarStatusProfile', 'SolarStatusZGEN']
