"""Integration: a SunSpec inverter discovered with pysunspec2, driven by the fake driver and used through
SunSpec, IEEE 2030.5 and IEEE 1815.2, with scale factors applied either by the transform or by the driver.

Exercises the same path the presentation service takes for an aliased resource: the mapping engine
resolves the alias to the canonical device and its format, the registry finds the chain from the
device's own format through ``sunspec`` to the alias format, and the compiled chain is applied to a
message shaped like the platform driver's ``devices/.../all`` publish. Everything under
``tests/integration/fake_sunspec/<mode>_scaling/`` is generated by ``build_configs.py`` from the
pysunspec2 device description ``device_1547.json``.
"""
from __future__ import annotations

import csv
import json
from importlib import resources
from pathlib import Path

import pytest

from interoperability.discovery.device_formats import (infer_scaling, is_scale_factor_point, sunspec_device_transforms,
                                             sunspec_point_path, sunspec_scale_factor)
from interoperability.mapping_engine import UAITree
from interoperability.transform_parser import TransformParser
from interoperability.transform_registry import TransformNotFoundError, TransformRegistry

pytest.importorskip('sunspec2')
from interoperability.discovery.sunspec import discover_file, fake_registry_rows, modbus_registry_rows  # noqa: E402

CASE = Path(__file__).parent / 'integration' / 'fake_sunspec'
MODES = ('transform', 'driver')


def _rows(path: Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def fake_driver_all_message(mode: str) -> dict:
    """What the fake driver publishes on devices/site1/feeder1/pv_inverter/all: the registry's starting values."""
    def value(row):
        raw, kind = row['Starting Value'], row['Type']
        return float(raw) if kind == 'float' else int(raw) if kind == 'int' else raw
    return {row['Volttron Point Name']: value(row) for row in _rows(CASE / f'{mode}_scaling' / 'fake_sunspec_pv.fake.csv')
            if row['Starting Value'] != ''}


@pytest.fixture(scope='module')
def device():
    return discover_file(CASE / 'device_1547.json')


@pytest.fixture(scope='module', params=MODES)
def mode(request):
    return request.param


@pytest.fixture(scope='module')
def config(mode) -> dict:
    return json.loads((CASE / f'{mode}_scaling' / 'presentation_config.json').read_text())


@pytest.fixture(scope='module')
def service(config):
    """Mapping engine and transform registry loaded the way PresentationService.configure_main does."""
    tree = UAITree()
    tree.ingest_mappings(config['mappings'])
    registry = TransformRegistry()
    for name, spec in config['formats'].items():
        registry.declare_format(name, **spec)
    bundled = resources.files('interoperability').joinpath('transforms')
    registry.update_registry([d for f in sorted(bundled.iterdir(), key=lambda f: f.name)
                              if f.is_file() and f.name.endswith('.json') for d in json.loads(f.read_text())]
                             + config['transforms'])
    return tree, registry


def resolve(service, uai: list[str]):
    """The agent's resolve(): canonical resource, target format, route, retention and the compiled chain."""
    tree, registry = service
    node, as_format, aliases = tree.resolve(tuple(uai))
    assert node is not None and node.is_canonical
    resource = node.resource.model_dump()
    for alias in reversed(aliases):
        resource['parameters'].update(alias.resource.parameters)
    chain, retention, path = registry.lookup_scored(resource['data_format'], as_format)
    parser = TransformParser(context=resource['parameters'])
    return resource, as_format, path, retention, parser.build_transform_from_schema(chain)


# ---- discovery and generation ----

def test_discovery_reads_the_device(device):
    assert device.identity == {'Mn': 'SunSpecTest', 'Md': 'Test-1547-1', 'SN': 'sn-123456789', 'Vr': '1.2.3'}
    assert len(device.points) == 384 and device.notes == []
    assert device.scale_factors['705_V_SF'] == -2 and device.scale_factors['701_Hz_SF'] == -3
    by_name = {p.name: p for p in device.points}
    assert by_name['701_W'].address == 40070 + 10 and by_name['701_W'].type == 'int16' and by_name['701_W'].scale_factor == '701_W_SF'
    assert by_name['705_Crv1_Pt1_V'].scale_factor == '705_V_SF' and by_name['705_Crv1_Pt1_V'].writable
    assert by_name['1_Mn'].is_string and by_name['1_Mn'].size == 16
    assert sum(1 for p in device.points if p.name.startswith('705_Crv')) == 3 * (9 + 4 * 2)      # 3 curves, 4 points each


def test_generated_case_is_current(device, mode):
    """The checked-in files match what build_configs.py derives from the device description."""
    out = CASE / f'{mode}_scaling'
    assert _rows(out / 'fake_sunspec_pv.fake.csv') == [{k: str(v) for k, v in r.items()} for r in fake_registry_rows(device, mode)]
    assert _rows(out / 'fake_sunspec_pv.modbus.csv') == [{k: str(v) for k, v in r.items()} for r in modbus_registry_rows(device, mode)]
    config = json.loads((out / 'presentation_config.json').read_text())
    names = [r['Volttron Point Name'] for r in _rows(out / 'fake_sunspec_pv.fake.csv')]
    assert config['formats']['fake_sunspec_pv'] == {'hub': False, 'scaling': mode, 'fields': sorted(names)}
    assert config['transforms'] == sunspec_device_transforms('fake_sunspec_pv', names, scaling=mode,
                                                             scale_factors=device.scale_factors).definitions
    assert infer_scaling(_rows(out / 'fake_sunspec_pv.modbus.csv')) == mode
    assert (out / 'store_configs.sh').read_text().count('vctl config store') == 3


def test_registries_reflect_the_scaling_mode(device):
    transform_rows = {r['Volttron Point Name']: r for r in modbus_registry_rows(device, 'transform')}
    driver_rows = {r['Volttron Point Name']: r for r in modbus_registry_rows(device, 'driver')}
    assert '701_W_SF' in transform_rows and '701_W_SF' not in driver_rows          # SF points only when the transform scales
    assert transform_rows['701_Hz']['Transform'] == '' and driver_rows['701_Hz']['Transform'] == 'scale_reg_pow_10(701_Hz_SF)'
    assert transform_rows['701_Hz']['Data Type'] == 'UINT32' and transform_rows['701_Hz']['Point Address'] == 40070 + 17
    assert transform_rows['1_Mn']['Data Type'] == 'string[32]'
    fake_transform = {r['Volttron Point Name']: r for r in fake_registry_rows(device, 'transform')}
    fake_driver = {r['Volttron Point Name']: r for r in fake_registry_rows(device, 'driver')}
    assert fake_transform['701_Hz']['Starting Value'] == 60010 and fake_driver['701_Hz']['Starting Value'] == 60.01
    assert fake_transform['705_Crv1_Pt1_V']['Starting Value'] == 9200 and fake_driver['705_Crv1_Pt1_V']['Starting Value'] == 92.0


def test_point_names_scale_factors_and_underscored_names():
    assert sunspec_point_path('705_Crv1_Pt3_Var') == ('705', 'Crv', 0, 'Pt', 2, 'Var')
    assert sunspec_point_path('708_Crv1_MustTrip_Pt1_V') == ('708', 'Crv', 0, 'MustTrip', 'Pt', 0, 'V')
    assert sunspec_point_path('701_TotWh_SF') == ('701', 'TotWh_SF')                 # underscore inside a SunSpec name
    assert sunspec_scale_factor('705_Crv1_Pt1_V') == '705_V_SF' and sunspec_scale_factor('705_Crv1_Pt1_Var') == '705_DeptRef_SF'
    assert sunspec_scale_factor('701_W') == '701_W_SF' and sunspec_scale_factor('705_Ena') is None
    assert is_scale_factor_point('701_W_SF') and not is_scale_factor_point('701_W')
    for bad in ['999_W', '701_Nope', '705_Crv_ActPt', '705_Crv1_Pt1', '701_W1', '701_W_Extra']:
        with pytest.raises(ValueError):
            sunspec_point_path(bad)


def test_device_transforms_scale_where_the_mode_says():
    names = ['701_W', '701_W_SF', '705_Crv1_ActPt', '705_Crv1_Pt1_V', '705_Crv1_Pt1_Var', '705_V_SF', '705_DeptRef_SF']
    by_transform = sunspec_device_transforms('dev', names, scaling='transform', scale_factors={'701_W_SF': 1, '705_V_SF': -2})
    read, write = by_transform.definitions
    assert read['pattern']['701']['W'] == "transform[701_W](scale_reg_pow_10('/701_W_SF'))"
    assert read['pattern']['705']['Crv[#] 1']['Pt[#]']['V'] == "transform[#, V](scale_reg_pow_10('/705_V_SF'))"
    assert write['pattern']['701_W'] == 'transform[701, W](scale(0.1))'
    assert "scale_fields('V:100.0')" in write['pattern']['*705_Crv_0_Pt']
    assert by_transform.notes == ['705_Crv1_Pt1_Var: scale factor 705_DeptRef_SF was not discovered; write left unscaled']
    by_driver = sunspec_device_transforms('dev', names, scaling='driver')
    read, write = by_driver.definitions
    assert read['pattern']['701'] == {'W': 'transform[701_W]()'} and '705_V_SF' not in json.dumps(read['pattern'])
    assert write['pattern']['701_W'] == 'transform[701, W]()' and by_driver.notes == []
    with pytest.raises(ValueError):
        sunspec_device_transforms('dev', names, scaling='magic')


# ---- the device used through each alias ----

def test_device_used_as_sunspec(service, mode):
    resource, fmt, path, retention, pipeline = resolve(service, ['site1', 'pv_sunspec'])
    assert resource['data_format'] == 'fake_sunspec_pv' and fmt == 'sunspec' and path == ['fake_sunspec_pv', 'sunspec']
    sunspec = pipeline.execute(fake_driver_all_message(mode))
    assert sunspec['701']['W'] == 9800.0 and sunspec['701']['Hz'] == 60.01 and sunspec['701']['LNV'] == 240.0
    assert sunspec['704']['PFWInj'] == {'PF': 0.95, 'Ext': 1}
    assert len(sunspec['705']['Crv']) == 3                                       # every stored curve, not just the active one
    curve = sunspec['705']['Crv'][0]
    assert curve['ActPt'] == 4 and curve['Pt'][:2] == [{'V': 92.0, 'Var': 30.0}, {'V': 96.7, 'Var': 0.0}]
    assert sunspec['711']['Ctl'][0]['DbOf'] == 600.3
    if mode == 'transform':
        assert sunspec['705']['V_SF'] == -2                                      # raw factors travel along
    else:
        assert 'V_SF' not in sunspec['705']
    # Writes reproduce every published device point exactly, whichever side scales.
    tree, registry = service
    back = TransformParser().build_transform_from_schema(registry.lookup('sunspec', 'fake_sunspec_pv')).execute(sunspec)
    assert back == fake_driver_all_message(mode)


def test_both_scaling_modes_yield_the_same_sunspec_message():
    outputs = []
    for mode in MODES:
        config = json.loads((CASE / f'{mode}_scaling' / 'presentation_config.json').read_text())
        to_sunspec = next(d['pattern'] for d in config['transforms'] if d['output_format'] == 'sunspec')
        message = TransformParser().build_transform_from_schema(to_sunspec).execute(fake_driver_all_message(mode))
        outputs.append({m: {k: v for k, v in body.items() if not k.endswith('_SF')} for m, body in message.items()})
    assert outputs[0] == outputs[1]


def test_device_used_as_2030_5(service, mode):
    resource, fmt, path, retention, pipeline = resolve(service, ['site1', 'pv_2030_5'])
    assert fmt == '2030.5' and path[:2] == ['fake_sunspec_pv', 'sunspec'] and path[-1] == '2030.5'
    sep2 = pipeline.execute(fake_driver_all_message(mode))
    assert sep2['MirrorMeterReading']['W'] == 9800.0 and sep2['MirrorMeterReading']['Hz'] == 60.01
    assert sep2['DERCapability']['rtgMaxW'] == 10000.0 and sep2['DERCapability']['rtgVNom'] == 240.0
    assert sep2['DERControl']['opModFixedPFInjectW'] == {'displacement': 0.95, 'excitation': 1}
    assert sep2['DERCurve']['opModVoltVar']['CurveData'][:2] == [{'xvalue': 92.0, 'yvalue': 30.0}, {'xvalue': 96.7, 'yvalue': 0.0}]
    assert len(sep2['DERCurve']['opModVoltVar']['CurveData']) == 4
    assert sep2['DERControl']['opModFreqDroop']['dBOF'] == 600.3


def test_device_used_as_1815_2_inputs(service, mode):
    resource, fmt, path, retention, pipeline = resolve(service, ['site1', 'pv_dnp3'])
    assert fmt == '1815.2.inputs' and path[:2] == ['fake_sunspec_pv', 'sunspec'] and path[-1] == '1815.2.inputs'
    dnp3 = pipeline.execute(fake_driver_all_message(mode))
    assert dnp3['AI']['298'] == 6                                               # volt-var open loop time
    windows = dnp3['sequence']
    assert [w['AI']['328'] for w in windows] == list(range(1, 10))            # nine curve modes, one window each
    volt_var = windows[0]['AI']
    assert volt_var['329'] == 2 and volt_var['330'] == 4
    assert [volt_var[str(i)] for i in range(333, 337)] == [92.0, 30.0, 96.7, 0.0]
    assert volt_var['297'] == 1


def test_driver_payload_shapes_yield_the_same_sunspec_message(service, mode):
    """The modular driver publishes [values, meta]; a bare values dict must give the same result."""
    _, _, _, _, pipeline = resolve(service, ['site1', 'pv_sunspec'])
    values = fake_driver_all_message(mode)
    meta = {name: {'units': 'W', 'type': 'integer'} for name in values}
    assert pipeline.execute([values, meta]) == pipeline.execute(values)
    assert pipeline.execute([values, meta])['701']['Hz'] == 60.01


def test_device_used_as_openfmb_solar_reading_profile(service, mode, config):
    """The OpenFMB alias: one profile with a fresh header, the device identity from the alias parameters, and
    protobuf on the wire as the alias declares."""
    from interoperability.models.openfmb import PROFILES
    alias = next(m for m in config['mappings'] if m['resource']['data_format'] == 'openfmb.solar.reading')
    assert alias['uai'][:3] == ['openfmb', 'solarmodule', 'SolarReadingProfile'] and alias['resource']['encoding'] == 'protobuf'
    resource, fmt, path, retention, pipeline = resolve(service, alias['uai'])
    assert fmt == 'openfmb.solar.reading'
    assert path == ['fake_sunspec_pv', 'sunspec', '61850', 'openfmb.solar', 'openfmb.solar.reading']
    assert resource['parameters'] == alias['resource']['parameters']
    values = fake_driver_all_message(mode)
    result = pipeline.execute([values, {name: {'units': ''} for name in values}])
    assert set(result) == {'readingMessageInfo', 'solarInverter', 'solarReading'}
    assert result['solarInverter']['conductingEquipment'] == {'mRID': alias['resource']['parameters']['mrid'],
                                                              'namedObject': {'name': 'PV inverter 1'}}
    assert len(result['readingMessageInfo']['messageInfo']['identifiedObject']['mRID']) == 36
    mmxu = result['solarReading']['readingMMXU']
    assert mmxu['Hz']['mag'] == 60.01 and mmxu['W']['net']['cVal']['mag'] == pipeline.execute(values)['solarReading']['readingMMXU']['W']['net']['cVal']['mag']
    PROFILES['SolarReadingProfile'].model_validate(result)
    pytest.importorskip('google.protobuf')
    from interoperability.codecs import openfmb as codec
    data = codec.encode('solarmodule.SolarReadingProfile', result)
    decoded = codec.decode('solarmodule.SolarReadingProfile', data)
    assert decoded['solarReading']['readingMMXU']['Hz']['mag'] == 60.01
    assert decoded['solarInverter']['conductingEquipment']['mRID'] == alias['resource']['parameters']['mrid']


def test_unmapped_alias_format_is_reported_not_silent(service):
    tree, registry = service
    with pytest.raises(TransformNotFoundError, match='has no registered transforms'):
        registry.lookup('fake_sunspec_pv', 'modbus_rtu')


def test_scoring_explains_the_route(service):
    tree, registry = service
    chain, retention, path = registry.lookup_scored('fake_sunspec_pv', '2030.5')
    assert 0.2 < retention <= 1.0
    info = registry.edge_info('fake_sunspec_pv', 'sunspec')
    assert info['retention'] > 0.9 and info['unmapped_targets'] == 0                # every device point is carried
