"""OpenFMB ``environmentmodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class EnvironmentReading(OpenFMBMessage):
    """OpenFMB message ``environmentmodule.EnvironmentReading``."""
    PROTO: ClassVar[str] = 'environmentmodule.EnvironmentReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    readingMENV: _common_module.ReadingMENV | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMENV'})
    readingMMET: _common_module.ReadingMMET | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMET'})

class EnvironmentReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``environmentmodule.EnvironmentReadingProfile``."""
    PROTO: ClassVar[str] = 'environmentmodule.EnvironmentReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    sensor: _common_module.Sensor | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Sensor'})
    environmentReading: EnvironmentReading | None = Field(default=None, json_schema_extra={'proto': 'environmentmodule.EnvironmentReading'})


PROFILES = {'EnvironmentReadingProfile': EnvironmentReadingProfile}
__all__ = ['EnvironmentReading', 'EnvironmentReadingProfile']
