"""OpenFMB ``breakermodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class Breaker(OpenFMBMessage):
    """OpenFMB message ``breakermodule.Breaker``."""
    PROTO: ClassVar[str] = 'breakermodule.Breaker'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})

class BreakerDiscreteControlXCBR(OpenFMBMessage):
    """OpenFMB message ``breakermodule.BreakerDiscreteControlXCBR``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerDiscreteControlXCBR'
    discreteControlXCBR: _common_module.DiscreteControlXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.DiscreteControlXCBR'})

class BreakerDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``breakermodule.BreakerDiscreteControl``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    breakerDiscreteControlXCBR: BreakerDiscreteControlXCBR | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.BreakerDiscreteControlXCBR'})

class BreakerDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``breakermodule.BreakerDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    breaker: Breaker | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.Breaker'})
    breakerDiscreteControl: BreakerDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.BreakerDiscreteControl'})

class BreakerEvent(OpenFMBMessage):
    """OpenFMB message ``breakermodule.BreakerEvent``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    statusAndEventXCBR: _common_module.StatusAndEventXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusAndEventXCBR'})

class BreakerEventProfile(OpenFMBMessage):
    """OpenFMB profile ``breakermodule.BreakerEventProfile``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    breaker: Breaker | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.Breaker'})
    breakerEvent: BreakerEvent | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.BreakerEvent'})

class BreakerReading(OpenFMBMessage):
    """OpenFMB message ``breakermodule.BreakerReading``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    diffReadingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class BreakerReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``breakermodule.BreakerReadingProfile``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    breaker: Breaker | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.Breaker'})
    breakerReading: list[BreakerReading] = Field(default_factory=list, json_schema_extra={'proto': 'breakermodule.BreakerReading'})

class BreakerStatus(OpenFMBMessage):
    """OpenFMB message ``breakermodule.BreakerStatus``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    statusAndEventXCBR: _common_module.StatusAndEventXCBR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusAndEventXCBR'})

class BreakerStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``breakermodule.BreakerStatusProfile``."""
    PROTO: ClassVar[str] = 'breakermodule.BreakerStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    breaker: Breaker | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.Breaker'})
    breakerStatus: BreakerStatus | None = Field(default=None, json_schema_extra={'proto': 'breakermodule.BreakerStatus'})


PROFILES = {'BreakerDiscreteControlProfile': BreakerDiscreteControlProfile, 'BreakerEventProfile': BreakerEventProfile, 'BreakerReadingProfile': BreakerReadingProfile, 'BreakerStatusProfile': BreakerStatusProfile}
__all__ = ['Breaker', 'BreakerDiscreteControl', 'BreakerDiscreteControlProfile', 'BreakerDiscreteControlXCBR', 'BreakerEvent', 'BreakerEventProfile', 'BreakerReading', 'BreakerReadingProfile', 'BreakerStatus', 'BreakerStatusProfile']
