"""OpenFMB ``resourcemodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class AnalogControlGGIO(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.AnalogControlGGIO``."""
    PROTO: ClassVar[str] = 'resourcemodule.AnalogControlGGIO'
    logicalNode: _common_module.LogicalNode | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNode'})
    AnOut: _common_module.ControlAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlAPC'})
    Phase: _common_module.Optional_PhaseCodeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_PhaseCodeKind'})

class BooleanControlGGIO(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.BooleanControlGGIO``."""
    PROTO: ClassVar[str] = 'resourcemodule.BooleanControlGGIO'
    logicalNode: _common_module.LogicalNode | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNode'})
    Phase: _common_module.Optional_PhaseCodeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_PhaseCodeKind'})
    SPCSO: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})

class IntegerControlGGIO(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.IntegerControlGGIO``."""
    PROTO: ClassVar[str] = 'resourcemodule.IntegerControlGGIO'
    logicalNode: _common_module.LogicalNode | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNode'})
    ISCSO: _common_module.ControlINC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlINC'})
    Phase: _common_module.Optional_PhaseCodeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_PhaseCodeKind'})

class StringControlGGIO(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.StringControlGGIO``."""
    PROTO: ClassVar[str] = 'resourcemodule.StringControlGGIO'
    logicalNode: _common_module.LogicalNode | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNode'})
    Phase: _common_module.Optional_PhaseCodeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_PhaseCodeKind'})
    StrOut: _common_module.VSC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.VSC'})

class ResourceDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.ResourceDiscreteControl``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceDiscreteControl'
    identifiedObject: _common_module.IdentifiedObject | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.IdentifiedObject'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    analogControlGGIO: list[AnalogControlGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'resourcemodule.AnalogControlGGIO'})
    booleanControlGGIO: list[BooleanControlGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'resourcemodule.BooleanControlGGIO'})
    integerControlGGIO: list[IntegerControlGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'resourcemodule.IntegerControlGGIO'})
    stringControlGGIO: list[StringControlGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'resourcemodule.StringControlGGIO'})

class ResourceDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``resourcemodule.ResourceDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})
    resourceDiscreteControl: ResourceDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'resourcemodule.ResourceDiscreteControl'})

class ResourceEvent(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.ResourceEvent``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceEvent'
    identifiedObject: _common_module.IdentifiedObject | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.IdentifiedObject'})
    analogEventAndStatusGGIO: list[_common_module.AnalogEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.AnalogEventAndStatusGGIO'})
    booleanEventAndStatusGGIO: list[_common_module.BooleanEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.BooleanEventAndStatusGGIO'})
    integerEventAndStatusGGIO: list[_common_module.IntegerEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.IntegerEventAndStatusGGIO'})
    stringEventAndStatusGGIO: list[_common_module.StringEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.StringEventAndStatusGGIO'})

class ResourceEventProfile(OpenFMBMessage):
    """OpenFMB profile ``resourcemodule.ResourceEventProfile``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})
    resourceEvent: ResourceEvent | None = Field(default=None, json_schema_extra={'proto': 'resourcemodule.ResourceEvent'})

class ResourceReading(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.ResourceReading``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class ResourceReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``resourcemodule.ResourceReadingProfile``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})
    resourceReading: ResourceReading | None = Field(default=None, json_schema_extra={'proto': 'resourcemodule.ResourceReading'})

class ResourceStatus(OpenFMBMessage):
    """OpenFMB message ``resourcemodule.ResourceStatus``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceStatus'
    identifiedObject: _common_module.IdentifiedObject | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.IdentifiedObject'})
    analogEventAndStatusGGIO: list[_common_module.AnalogEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.AnalogEventAndStatusGGIO'})
    booleanEventAndStatusGGIO: list[_common_module.BooleanEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.BooleanEventAndStatusGGIO'})
    integerEventAndStatusGGIO: list[_common_module.IntegerEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.IntegerEventAndStatusGGIO'})
    stringEventAndStatusGGIO: list[_common_module.StringEventAndStatusGGIO] = Field(default_factory=list, json_schema_extra={'proto': 'commonmodule.StringEventAndStatusGGIO'})

class ResourceStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``resourcemodule.ResourceStatusProfile``."""
    PROTO: ClassVar[str] = 'resourcemodule.ResourceStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})
    resourceStatus: ResourceStatus | None = Field(default=None, json_schema_extra={'proto': 'resourcemodule.ResourceStatus'})


PROFILES = {'ResourceDiscreteControlProfile': ResourceDiscreteControlProfile, 'ResourceEventProfile': ResourceEventProfile, 'ResourceReadingProfile': ResourceReadingProfile, 'ResourceStatusProfile': ResourceStatusProfile}
__all__ = ['AnalogControlGGIO', 'BooleanControlGGIO', 'IntegerControlGGIO', 'ResourceDiscreteControl', 'ResourceDiscreteControlProfile', 'ResourceEvent', 'ResourceEventProfile', 'ResourceReading', 'ResourceReadingProfile', 'ResourceStatus', 'ResourceStatusProfile', 'StringControlGGIO']
