"""OpenFMB ``switchmodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class ProtectedSwitch(OpenFMBMessage):
    """OpenFMB message ``switchmodule.ProtectedSwitch``."""
    PROTO: ClassVar[str] = 'switchmodule.ProtectedSwitch'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})

class SwitchDiscreteControlXSWI(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchDiscreteControlXSWI``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchDiscreteControlXSWI'
    logicalNodeForControl: _common_module.LogicalNodeForControl | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForControl'})
    Pos: _common_module.PhaseDPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseDPC'})
    ResetProtectionPickup: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})

class SwitchDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchDiscreteControl``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    switchDiscreteControlXSWI: SwitchDiscreteControlXSWI | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchDiscreteControlXSWI'})

class SwitchDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``switchmodule.SwitchDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    protectedSwitch: ProtectedSwitch | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.ProtectedSwitch'})
    switchDiscreteControl: SwitchDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchDiscreteControl'})

class SwitchEventXSWI(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchEventXSWI``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchEventXSWI'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    Pos: _common_module.PhaseDPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseDPS'})

class SwitchEvent(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchEvent``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    switchEventXSWI: SwitchEventXSWI | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchEventXSWI'})

class SwitchEventProfile(OpenFMBMessage):
    """OpenFMB profile ``switchmodule.SwitchEventProfile``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    protectedSwitch: ProtectedSwitch | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.ProtectedSwitch'})
    switchEvent: SwitchEvent | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchEvent'})

class SwitchReading(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchReading``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    diffReadingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class SwitchReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``switchmodule.SwitchReadingProfile``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    protectedSwitch: ProtectedSwitch | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.ProtectedSwitch'})
    switchReading: list[SwitchReading] = Field(default_factory=list, json_schema_extra={'proto': 'switchmodule.SwitchReading'})

class SwitchStatusXSWI(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchStatusXSWI``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchStatusXSWI'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    Pos: _common_module.PhaseDPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseDPS'})
    ProtectionPickup: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})

class SwitchStatus(OpenFMBMessage):
    """OpenFMB message ``switchmodule.SwitchStatus``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    switchStatusXSWI: SwitchStatusXSWI | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchStatusXSWI'})

class SwitchStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``switchmodule.SwitchStatusProfile``."""
    PROTO: ClassVar[str] = 'switchmodule.SwitchStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    protectedSwitch: ProtectedSwitch | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.ProtectedSwitch'})
    switchStatus: SwitchStatus | None = Field(default=None, json_schema_extra={'proto': 'switchmodule.SwitchStatus'})


PROFILES = {'SwitchDiscreteControlProfile': SwitchDiscreteControlProfile, 'SwitchEventProfile': SwitchEventProfile, 'SwitchReadingProfile': SwitchReadingProfile, 'SwitchStatusProfile': SwitchStatusProfile}
__all__ = ['ProtectedSwitch', 'SwitchDiscreteControl', 'SwitchDiscreteControlProfile', 'SwitchDiscreteControlXSWI', 'SwitchEvent', 'SwitchEventProfile', 'SwitchEventXSWI', 'SwitchReading', 'SwitchReadingProfile', 'SwitchStatus', 'SwitchStatusProfile', 'SwitchStatusXSWI']
