"""SunSpec model 126: Static Volt-VAR

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Volt_var',
    'Volt_varCurve',
    'Volt_varCurveDeptRef',
    'Volt_varCurveReadOnly',
    'Volt_varModEna',
]


class Volt_varCurveDeptRef(SunSpecEnum):
    """Enumeration for point ``Volt_varCurve.DeptRef`` (enum16)."""
    WMAX = 1    # WMax
    VARMAX = 2    # VArMax
    VARAVAL = 3    # VArAval


class Volt_varCurveReadOnly(SunSpecEnum):
    """Enumeration for point ``Volt_varCurve.ReadOnly`` (enum16)."""
    READWRITE = 0
    READONLY = 1


class Volt_varModEna(SunSpecFlags):
    """Bitfield for point ``Volt_var.ModEna`` (bitfield16)."""
    ENABLED = 1


class Volt_varCurve(SunSpecGroup):
    """curve"""

    GROUP_NAME: ClassVar[str] = 'curve'

    ActPt: int | None = Field(default=None, description='Number of active points in array.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActPt'})
    DeptRef: Volt_varCurveDeptRef | int | None = Field(default=None, description='Meaning of dependent variable: 1=%WMax 2=%VArMax 3=%VArAval.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DeptRef'})
    V1: int | None = Field(default=None, description='Point 1 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'V1'})
    VAr1: int | None = Field(default=None, description='Point 1 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'VAr1'})
    V2: int | None = Field(default=None, description='Point 2 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V2'})
    VAr2: int | None = Field(default=None, description='Point 2 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr2'})
    V3: int | None = Field(default=None, description='Point 3 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V3'})
    VAr3: int | None = Field(default=None, description='Point 3 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr3'})
    V4: int | None = Field(default=None, description='Point 4 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V4'})
    VAr4: int | None = Field(default=None, description='Point 4 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr4'})
    V5: int | None = Field(default=None, description='Point 5 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V5'})
    VAr5: int | None = Field(default=None, description='Point 5 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr5'})
    V6: int | None = Field(default=None, description='Point 6 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V6'})
    VAr6: int | None = Field(default=None, description='Point 6 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr6'})
    V7: int | None = Field(default=None, description='Point 7 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V7'})
    VAr7: int | None = Field(default=None, description='Point 7 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr7'})
    V8: int | None = Field(default=None, description='Point 8 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V8'})
    VAr8: int | None = Field(default=None, description='Point 8 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr8'})
    V9: int | None = Field(default=None, description='Point 9 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V9'})
    VAr9: int | None = Field(default=None, description='Point 9 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr9'})
    V10: int | None = Field(default=None, description='Point 10 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V10'})
    VAr10: int | None = Field(default=None, description='Point 10 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr10'})
    V11: int | None = Field(default=None, description='Point 11 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V11'})
    VAr11: int | None = Field(default=None, description='Point 11 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr11'})
    V12: int | None = Field(default=None, description='Point 12 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V12'})
    VAr12: int | None = Field(default=None, description='Point 12 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr12'})
    V13: int | None = Field(default=None, description='Point 13 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V13'})
    VAr13: int | None = Field(default=None, description='Point 13 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr13'})
    V14: int | None = Field(default=None, description='Point 14 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V14'})
    VAr14: int | None = Field(default=None, description='Point 14 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr14'})
    V15: int | None = Field(default=None, description='Point 15 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V15'})
    VAr15: int | None = Field(default=None, description='Point 15 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr15'})
    V16: int | None = Field(default=None, description='Point 16 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V16'})
    VAr16: int | None = Field(default=None, description='Point 16 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr16'})
    V17: int | None = Field(default=None, description='Point 17 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V17'})
    VAr17: int | None = Field(default=None, description='Point 17 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr17'})
    V18: int | None = Field(default=None, description='Point 18 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V18'})
    VAr18: int | None = Field(default=None, description='Point 18 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr18'})
    V19: int | None = Field(default=None, description='Point 19 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V19'})
    VAr19: int | None = Field(default=None, description='Point 19 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr19'})
    V20: int | None = Field(default=None, description='Point 20 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V20'})
    VAr20: int | None = Field(default=None, description='Point 20 VARs.', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'VAr20'})
    CrvNam: str | None = Field(default=None, description='Optional description for curve. (Max 16 chars)', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'CrvNam'})
    RmpTms: int | None = Field(default=None, description='The time of the PT1 in seconds (time to accomplish a change of 95%).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpTms'})
    RmpDecTmm: int | None = Field(default=None, description='The maximum rate at which the VAR value may be reduced in response to changes in the voltage value. %refVal is %WMax %VArMax or %VArAval depending on value of DeptRef.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% ref_value/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpDecTmm'})
    RmpIncTmm: int | None = Field(default=None, description='The maximum rate at which the VAR value may be increased in response to changes in the voltage value. %refVal is %WMax %VArMax or %VArAval depending on value of DeptRef.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% ref_value/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpIncTmm'})
    ReadOnly: Volt_varCurveReadOnly | int | None = Field(default=None, description='Boolean flag indicates if curve is read-only or can be modified.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'ReadOnly'})


@register_model
class Volt_var(SunSpecModel):
    """Static Volt-VAR Arrays"""

    GROUP_NAME: ClassVar[str] = 'volt_var'
    MODEL_ID: ClassVar[int] = 126
    MODEL_LABEL: ClassVar[str] = 'Static Volt-VAR'

    ID: int | None = Field(default=126, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 126})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    ActCrv: int | None = Field(default=None, description='Index of active curve. 0=no active curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActCrv'})
    ModEna: Volt_varModEna | int | None = Field(default=None, description='Is Volt-VAR control active.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    WinTms: int | None = Field(default=None, description='Time window for volt-VAR change.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'WinTms'})
    RvrtTms: int | None = Field(default=None, description='Timeout period for volt-VAR curve selection.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RvrtTms'})
    RmpTms: int | None = Field(default=None, description='The time of the PT1 in seconds (time to accomplish a change of 95%).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpTms'})
    NCrv: int | None = Field(default=None, description='Number of curves supported (recommend 4).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NCrv'})
    NPt: int | None = Field(default=None, description='Number of curve points supported (maximum of 20).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NPt'})
    V_SF: int | None = Field(default=None, description='Scale factor for percent VRef.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'V_SF'})
    DeptRef_SF: int | None = Field(default=None, description='Scale factor for dependent variable.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'DeptRef_SF'})
    RmpIncDec_SF: int | None = Field(default=None, description='RmpIncDec_SF', json_schema_extra={'type': 'sunssf', 'size': 1})
    curve: list[Volt_varCurve] = Field(default_factory=list, description='curve', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
