"""SunSpec model 711: DER Frequency Droop

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERFreqDroop',
    'DERFreqDroopAdptCtlRslt',
    'DERFreqDroopCtl',
    'DERFreqDroopCtlReadOnly',
    'DERFreqDroopEna',
]


class DERFreqDroopCtlReadOnly(SunSpecEnum):
    """Enumeration for point ``DERFreqDroopCtl.ReadOnly`` (enum16)."""
    RW = 0    # Read-Write Access
    R = 1    # Read-Only Access


class DERFreqDroopEna(SunSpecEnum):
    """Enumeration for point ``DERFreqDroop.Ena`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERFreqDroopAdptCtlRslt(SunSpecEnum):
    """Enumeration for point ``DERFreqDroop.AdptCtlRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DERFreqDroopCtl(SunSpecGroup):
    """Stored control sets."""

    GROUP_NAME: ClassVar[str] = 'Ctl'

    DbOf: int | None = Field(default=None, description='The deadband value for over-frequency conditions in Hz.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Hz', 'sf': 'Db_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Over-Frequency Deadband', 'standards': ['IEEE 1547-2018']})
    DbUf: int | None = Field(default=None, description='The deadband value for under-frequency conditions in Hz.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Hz', 'sf': 'Db_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Under-Frequency Deadband', 'standards': ['IEEE 1547-2018']})
    KOf: int | None = Field(default=None, description='Frequency droop per-unit frequency change for over-frequency conditions corresponding to 1 per-unit power output change.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'K_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Over-Frequency Change Ratio', 'standards': ['IEEE 1547-2018']})
    KUf: int | None = Field(default=None, description='Frequency droop per-unit frequency change for under-frequency conditions corresponding to 1 per-unit power output change.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'K_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Under-Frequency Change Ratio', 'standards': ['IEEE 1547-2018']})
    RspTms: int | None = Field(default=None, description='The open-loop response time in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'RspTms_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Open-Loop Response Time', 'standards': ['IEEE 1547-2018']})
    PMin: int | None = Field(default=None, description='The minimum active power output due to DER prime mover constraints, in percent of the DER active power rating. The valid range is -100 to 100. This setting applies only to the frequency droop control.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'access': 'RW', 'label': 'Minimum Active Power'})
    ReadOnly: DERFreqDroopCtlReadOnly | int | None = Field(default=None, description='Control read-write access.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Control Access', 'standards': ['IEEE 1547-2018']})


@register_model
class DERFreqDroop(SunSpecModel):
    """DER Frequency Droop model."""

    GROUP_NAME: ClassVar[str] = 'DERFreqDroop'
    MODEL_ID: ClassVar[int] = 711
    MODEL_LABEL: ClassVar[str] = 'DER Frequency Droop'

    ID: int | None = Field(default=711, description='DER Frequency Droop model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 711})
    L: int | None = Field(default=None, description='DER Frequency Droop model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Ena: DERFreqDroopEna | int | None = Field(default=None, description='DER Frequency-Watt (Frequency-Droop) control enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DER Frequency Droop Module Enable', 'standards': ['IEEE 1547-2018']})
    AdptCtlReq: int | None = Field(default=None, description='Set active control. 0 = No active control.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Set Active Control Request', 'standards': ['IEEE 1547-2018']})
    AdptCtlRslt: DERFreqDroopAdptCtlRslt | int | None = Field(default=None, description='Result of last set active control operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Set Active Control Result', 'standards': ['IEEE 1547-2018']})
    NCtl: int | None = Field(default=None, description='Number of stored controls supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Control Count', 'standards': ['IEEE 1547-2018']})
    RvrtTms: int | None = Field(default=None, description='Reversion time in seconds. 0 = No reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Reversion Timeout'})
    RvrtRem: int | None = Field(default=None, description='Reversion time remaining in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Reversion Time Left'})
    RvrtCtl: int | None = Field(default=None, description='Default control after reversion timeout.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Reversion Control'})
    Db_SF: int | None = Field(default=None, description='Deadband scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Deadband Scale Factor', 'standards': ['IEEE 1547-2018']})
    K_SF: int | None = Field(default=None, description='Frequency change scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Frequency Change Scale Factor', 'standards': ['IEEE 1547-2018']})
    RspTms_SF: int | None = Field(default=None, description='Open loop response time scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Open-Loop Scale Factor', 'standards': ['IEEE 1547-2018']})
    Ctl: list[DERFreqDroopCtl] = Field(default_factory=list, description='Stored control sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NCtl'})
