"""SunSpec model 8: Get Device Security Certificate

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_8',
    'Model_8Fmt',
    'Model_8Repeating',
]


class Model_8Fmt(SunSpecEnum):
    """Enumeration for point ``Model_8.Fmt`` (enum16)."""
    NONE = 0
    X509_PEM = 1
    X509_DER = 2


class Model_8Repeating(SunSpecGroup):
    """repeating"""

    GROUP_NAME: ClassVar[str] = 'repeating'

    Cert: int | None = Field(default=None, description='X.509 Certificate of the device', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Cert'})


@register_model
class Model_8(SunSpecModel):
    """Security model for PKI"""

    GROUP_NAME: ClassVar[str] = 'model_8'
    MODEL_ID: ClassVar[int] = 8
    MODEL_LABEL: ClassVar[str] = 'Get Device Security Certificate'

    ID: int | None = Field(default=8, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 8})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Fmt: Model_8Fmt | int | None = Field(default=None, description='X.509 format of the certificate. DER or PEM.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Format'})
    N: int | None = Field(default=None, description='Number of registers to follow for the certificate', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'N'})
    repeating: list[Model_8Repeating] = Field(default_factory=list, description='repeating', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
