"""SunSpec model 127: Freq-Watt Param

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Freq_watt_param',
    'Freq_watt_paramHysEna',
    'Freq_watt_paramModEna',
]


class Freq_watt_paramHysEna(SunSpecFlags):
    """Bitfield for point ``Freq_watt_param.HysEna`` (bitfield16)."""
    ENABLED = 1


class Freq_watt_paramModEna(SunSpecFlags):
    """Bitfield for point ``Freq_watt_param.ModEna`` (bitfield16)."""
    ENABLED = 1


@register_model
class Freq_watt_param(SunSpecModel):
    """Parameterized Frequency-Watt"""

    GROUP_NAME: ClassVar[str] = 'freq_watt_param'
    MODEL_ID: ClassVar[int] = 127
    MODEL_LABEL: ClassVar[str] = 'Freq-Watt Param'

    ID: int | None = Field(default=127, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 127})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    WGra: int | None = Field(default=None, description='The slope of the reduction in the maximum allowed watts output as a function of frequency.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% PM/Hz', 'sf': 'WGra_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'WGra'})
    HzStr: int | None = Field(default=None, description='The frequency deviation from nominal frequency (ECPNomHz) at which a snapshot of the instantaneous power output is taken to act as the CAPPED power level (PM) and above which reduction in power output occurs.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Hz', 'sf': 'HzStrStop_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'HzStr'})
    HzStop: int | None = Field(default=None, description='The frequency deviation from nominal frequency (ECPNomHz) at which curtailed power output may return to normal and the cap on the power level value is removed.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Hz', 'sf': 'HzStrStop_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'HzStop'})
    HysEna: Freq_watt_paramHysEna | int | None = Field(default=None, description='Enable hysteresis', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'HysEna'})
    ModEna: Freq_watt_paramModEna | int | None = Field(default=None, description='Is Parameterized Frequency-Watt control active.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    HzStopWGra: int | None = Field(default=None, description='The maximum time-based rate of change at which power output returns to normal after having been capped by an over frequency event.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'HzStopWGra'})
    WGra_SF: int | None = Field(default=None, description='Scale factor for output gradient.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'WGra_SF'})
    HzStrStop_SF: int | None = Field(default=None, description='Scale factor for frequency deviations.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'HzStrStop_SF'})
    RmpIncDec_SF: int | None = Field(default=None, description='Scale factor for increment and decrement ramps.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'RmpIncDec_SF'})
    Pad: int | None = Field(default=None, description='Pad', json_schema_extra={'type': 'pad', 'size': 1})
