"""SunSpec model 64410: DC Simulator Control Interface

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DCSimInterface',
    'DCSimInterfaceAdptProfRslt',
    'DCSimInterfaceEN50530',
    'DCSimInterfaceEna',
    'DCSimInterfaceEnaProf',
    'DCSimInterfaceMode',
    'DCSimInterfaceProf',
    'DCSimInterfaceProfDeptRef',
    'DCSimInterfaceProfPt',
    'DCSimInterfaceReset',
]


class DCSimInterfaceProfDeptRef(SunSpecFlags):
    """Bitfield for point ``DCSimInterfaceProf.DeptRef`` (bitfield32)."""
    VOLTAGE = 1    # Voltage
    POWER = 2    # Power
    CURRENT = 4    # Current
    IRRADIANCE = 8    # Irradiance


class DCSimInterfaceMode(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.Mode`` (enum16)."""
    CV = 0    # CV Mode
    CC = 1    # CC Mode


class DCSimInterfaceEna(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.Ena`` (enum16)."""
    ON = 1    # Power On
    OFF = 0    # Power Off


class DCSimInterfaceReset(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.Reset`` (enum16)."""
    RESET = 1    # Reset Device
    DO_NOT_RESET = 0    # Do Not Reset Device


class DCSimInterfaceEN50530(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.EN50530`` (enum16)."""
    EN50530 = 1    # EN50530 Mode
    DO_NOT_EN50530 = 0    # Do Not Use EN50530 Mode


class DCSimInterfaceEnaProf(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.EnaProf`` (enum16)."""
    START = 1    # Start Profile
    STOP = 0    # Stop Profile


class DCSimInterfaceAdptProfRslt(SunSpecEnum):
    """Enumeration for point ``DCSimInterface.AdptProfRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DCSimInterfaceProfPt(SunSpecGroup):
    """Stored profile points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    Tms: int | None = Field(default=None, description='Profile time.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Sec', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Profile Time'})
    V: int | None = Field(default=None, description='Profile voltage point in Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point'})
    P: int | None = Field(default=None, description='Profile power point in Watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Power Point'})
    I: int | None = Field(default=None, description='Profile current point in Amps.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'access': 'RW', 'label': 'Current Point'})
    G: int | None = Field(default=None, description='Profile irradiance point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'sf': 'Pct_SF', 'access': 'RW', 'label': 'Irradiance Point'})


class DCSimInterfaceProf(SunSpecGroup):
    """Stored profile sets."""

    GROUP_NAME: ClassVar[str] = 'Prof'

    ActPt: int | None = Field(default=None, description='Number of active points.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Active Points'})
    DeptRef: DCSimInterfaceProfDeptRef | int | None = Field(default=None, description='Profile references.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'access': 'RW', 'mandatory': 'M', 'label': 'Dependent References'})
    Pt: list[DCSimInterfaceProfPt] = Field(default_factory=list, description='Stored profile points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


@register_model
class DCSimInterface(SunSpecModel):
    """A generic DC simulator/power supply control interface for DER electrical testing."""

    GROUP_NAME: ClassVar[str] = 'DCSimInterface'
    MODEL_ID: ClassVar[int] = 64410
    MODEL_LABEL: ClassVar[str] = 'DC Simulator Control Interface'

    ID: int | None = Field(default=64410, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 64410})
    L: int | None = Field(default=None, description='Model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    VMaxLim: int | None = Field(default=None, description='Upper Voltage Protection Limit', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'Maximum Voltage'})
    PMaxLim: int | None = Field(default=None, description='Upper Power Protection Limit', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Maximum Power'})
    IMaxLim: int | None = Field(default=None, description='Upper Current Protection Limit', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'access': 'RW', 'label': 'Maximum Current'})
    Mode: DCSimInterfaceMode | int | None = Field(default=None, description='Constant Voltage (CV) or Constant Current (CC) Mode', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'CV or CC Mode'})
    Ena: DCSimInterfaceEna | int | None = Field(default=None, description='Power On/Off', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power On/Off'})
    Reset: DCSimInterfaceReset | int | None = Field(default=None, description='Reset Device', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reset Device'})
    VSet: int | None = Field(default=None, description='Voltage Setpoint', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Setpoint'})
    PSet: int | None = Field(default=None, description='Power Setpoint', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Power Setpoint'})
    ISet: int | None = Field(default=None, description='Current Setpoint', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'access': 'RW', 'label': 'Current Setpoint'})
    EN50530: DCSimInterfaceEN50530 | int | None = Field(default=None, description='EN50530 Mode - Enable or disable EN50530 profile mode', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'EN50530 Mode'})
    Vmpp: int | None = Field(default=None, description='EN50530 MPP Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'EN50530 MPP Voltage'})
    Pmpp: int | None = Field(default=None, description='EN50530 MPP Power', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'EN50530 MPP Power'})
    GSet: int | None = Field(default=None, description='Irradiance Setpoint', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W/m^2', 'sf': 'G_SF', 'access': 'RW', 'label': 'Irradiance Setpoint'})
    VSlewRate: int | None = Field(default=None, description='Voltage Slew Rate', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V/s', 'sf': 'VSlew_SF', 'access': 'RW', 'label': 'Voltage Slew Rate'})
    PSlewRate: int | None = Field(default=None, description='Power Slew Rate', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W/s', 'sf': 'PSlew_SF', 'access': 'RW', 'label': 'Power Slew Rate'})
    ISlewRate: int | None = Field(default=None, description='Current Slew Rate', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A/s', 'sf': 'ISlew_SF', 'access': 'RW', 'label': 'Current Slew Rate'})
    EnaProf: DCSimInterfaceEnaProf | int | None = Field(default=None, description='Start/Stop the Profile', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Enable Profile'})
    AdptProfReq: int | None = Field(default=None, description='Index of profile points to adopt. First curve index is 1.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Profile Adoption Request'})
    AdptProfRslt: DCSimInterfaceAdptProfRslt | int | None = Field(default=None, description='Result of last adopt profile operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Adopt Profile Result'})
    V: int | None = Field(default=None, description='Measured Voltage', json_schema_extra={'type': 'int32', 'size': 2, 'label': 'Measured Voltage'})
    P: int | None = Field(default=None, description='Measured Power', json_schema_extra={'type': 'int32', 'size': 2, 'label': 'Measured Power'})
    I: int | None = Field(default=None, description='Measured Current', json_schema_extra={'type': 'int32', 'size': 2, 'label': 'Measured Current'})
    Errors: str | None = Field(default=None, description='Error States', json_schema_extra={'type': 'string', 'size': 32, 'access': 'R', 'label': 'Errors'})
    NPt: int | None = Field(default=None, description='Number of profile points supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Number Of Points'})
    NProf: int | None = Field(default=None, description='Number of stored profiles supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Profile Count'})
    W_SF: int | None = Field(default=None, description='Scale factor for power points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Power Scale Factor'})
    V_SF: int | None = Field(default=None, description='Scale factor for voltage points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Scale Factor'})
    A_SF: int | None = Field(default=None, description='Scale factor for current points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Current Scale Factor'})
    G_SF: int | None = Field(default=None, description='Scale factor for irradiance.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Irradiance Scale Factor'})
    Tms_SF: int | None = Field(default=None, description='Scale factor for time points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Time Scale Factor'})
    VSlew_SF: int | None = Field(default=None, description='Scale factor for voltage slew rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Slew Rate Scale Factor'})
    PSlew_SF: int | None = Field(default=None, description='Scale factor for power slew rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Power Slew Rate Scale Factor'})
    ISlew_SF: int | None = Field(default=None, description='Scale factor for current slew rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Current Slew Rate Scale Factor'})
    Pct_SF: int | None = Field(default=None, description='Scale factor for percentages.', json_schema_extra={'type': 'sunssf', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'static': 'S', 'label': 'Percent Scale Factor'})
    Prof: list[DCSimInterfaceProf] = Field(default_factory=list, description='Stored profile sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NProf'})
