"""SunSpec model 124: Storage

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Storage_basic',
    'Storage_basicChaGriSet',
    'Storage_basicChaSt',
    'Storage_basicStorCtl_Mod',
]


class Storage_basicStorCtl_Mod(SunSpecFlags):
    """Bitfield for point ``Storage_basic.StorCtl_Mod`` (bitfield16)."""
    CHARGE = 1
    DISCHARGE = 2    # DiSCHARGE


class Storage_basicChaSt(SunSpecEnum):
    """Enumeration for point ``Storage_basic.ChaSt`` (enum16)."""
    OFF = 1
    EMPTY = 2
    DISCHARGING = 3
    CHARGING = 4
    FULL = 5
    HOLDING = 6
    TESTING = 7


class Storage_basicChaGriSet(SunSpecEnum):
    """Enumeration for point ``Storage_basic.ChaGriSet`` (enum16)."""
    PV = 0
    GRID = 1


@register_model
class Storage_basic(SunSpecModel):
    """Basic Storage Controls"""

    GROUP_NAME: ClassVar[str] = 'storage_basic'
    MODEL_ID: ClassVar[int] = 124
    MODEL_LABEL: ClassVar[str] = 'Storage'

    ID: int | None = Field(default=124, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 124})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    WChaMax: int | None = Field(default=None, description='Setpoint for maximum charge.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'WChaMax_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'WChaMax'})
    WChaGra: int | None = Field(default=None, description='Setpoint for maximum charging rate. Default is MaxChaRte.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WChaMax/sec', 'sf': 'WChaDisChaGra_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'WChaGra'})
    WDisChaGra: int | None = Field(default=None, description='Setpoint for maximum discharge rate. Default is MaxDisChaRte.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WChaMax/sec', 'sf': 'WChaDisChaGra_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'WDisChaGra'})
    StorCtl_Mod: Storage_basicStorCtl_Mod | int | None = Field(default=None, description='Activate hold/discharge/charge storage control mode.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'StorCtl_Mod'})
    VAChaMax: int | None = Field(default=None, description='Setpoint for maximum charging VA.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VAChaMax_SF', 'access': 'RW', 'label': 'VAChaMax'})
    MinRsvPct: int | None = Field(default=None, description='Setpoint for minimum reserve for storage as a percentage of the nominal maximum storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WChaMax', 'sf': 'MinRsvPct_SF', 'access': 'RW', 'label': 'MinRsvPct'})
    ChaState: int | None = Field(default=None, description='Currently available energy as a percent of the capacity rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% AhrRtg', 'sf': 'ChaState_SF', 'label': 'ChaState'})
    StorAval: int | None = Field(default=None, description='State of charge (ChaState) minus storage reserve (MinRsvPct) times capacity rating (AhrRtg).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'AH', 'sf': 'StorAval_SF', 'label': 'StorAval'})
    InBatV: int | None = Field(default=None, description='Internal battery voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'InBatV_SF', 'label': 'InBatV'})
    ChaSt: Storage_basicChaSt | int | None = Field(default=None, description='Charge status of storage device.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'ChaSt'})
    OutWRte: int | None = Field(default=None, description='Percent of max discharge rate.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WDisChaMax', 'sf': 'InOutWRte_SF', 'access': 'RW', 'label': 'OutWRte'})
    InWRte: int | None = Field(default=None, description='Percent of max charging rate.', json_schema_extra={'type': 'int16', 'size': 1, 'units': ' % WChaMax', 'sf': 'InOutWRte_SF', 'access': 'RW', 'label': 'InWRte'})
    InOutWRte_WinTms: int | None = Field(default=None, description='Time window for charge/discharge rate change.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'InOutWRte_WinTms'})
    InOutWRte_RvrtTms: int | None = Field(default=None, description='Timeout period for charge/discharge rate.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'InOutWRte_RvrtTms'})
    InOutWRte_RmpTms: int | None = Field(default=None, description='Ramp time for moving from current setpoint to new setpoint.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'InOutWRte_RmpTms'})
    ChaGriSet: Storage_basicChaGriSet | int | None = Field(default=None, description='ChaGriSet', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW'})
    WChaMax_SF: int | None = Field(default=None, description='Scale factor for maximum charge.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'WChaMax_SF'})
    WChaDisChaGra_SF: int | None = Field(default=None, description='Scale factor for maximum charge and discharge rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'WChaDisChaGra_SF'})
    VAChaMax_SF: int | None = Field(default=None, description='Scale factor for maximum charging VA.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'VAChaMax_SF'})
    MinRsvPct_SF: int | None = Field(default=None, description='Scale factor for minimum reserve percentage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'MinRsvPct_SF'})
    ChaState_SF: int | None = Field(default=None, description='Scale factor for available energy percent.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'ChaState_SF'})
    StorAval_SF: int | None = Field(default=None, description='Scale factor for state of charge.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'StorAval_SF'})
    InBatV_SF: int | None = Field(default=None, description='Scale factor for battery voltage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'InBatV_SF'})
    InOutWRte_SF: int | None = Field(default=None, description='Scale factor for percent charge/discharge rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'InOutWRte_SF'})
