"""SunSpec model 16: Simple IP Network

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_16',
    'Model_16Cfg',
    'Model_16Ctl',
    'Model_16LnkCtl',
]


class Model_16Cfg(SunSpecEnum):
    """Enumeration for point ``Model_16.Cfg`` (enum16)."""
    STATIC = 0
    DHCP = 1


class Model_16Ctl(SunSpecFlags):
    """Bitfield for point ``Model_16.Ctl`` (bitfield16)."""
    ENABLE_DNS = 1
    ENABLE_NTP = 2


class Model_16LnkCtl(SunSpecFlags):
    """Bitfield for point ``Model_16.LnkCtl`` (bitfield16)."""
    AUTONEGOTIATE = 1
    FULL_DUPLEX = 2
    FORCE_10MB = 4
    FORCE_100MB = 8
    FORCE_1GB = 16


@register_model
class Model_16(SunSpecModel):
    """Include this model for a simple IPv4 network stack"""

    GROUP_NAME: ClassVar[str] = 'model_16'
    MODEL_ID: ClassVar[int] = 16
    MODEL_LABEL: ClassVar[str] = 'Simple IP Network'

    ID: int | None = Field(default=16, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 16})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Nam: str | None = Field(default=None, description='Interface name. (8 chars)', json_schema_extra={'type': 'string', 'size': 4, 'access': 'RW', 'label': 'Name'})
    Cfg: Model_16Cfg | int | None = Field(default=None, description='Force IPv4 configuration method', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Config'})
    Ctl: Model_16Ctl | int | None = Field(default=None, description='Configure use of services', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Control'})
    Addr: str | None = Field(default=None, description='IP address', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'mandatory': 'M', 'label': 'Address'})
    Msk: str | None = Field(default=None, description='Netmask', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'mandatory': 'M', 'label': 'Netmask'})
    Gw: str | None = Field(default=None, description='Gateway IP address', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'Gateway'})
    DNS1: str | None = Field(default=None, description='32 bit IP address of DNS server', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'DNS1'})
    DNS2: str | None = Field(default=None, description='32 bit IP address of DNS server', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'DNS2'})
    MAC: str | None = Field(default=None, description='IEEE MAC address of this interface', json_schema_extra={'type': 'eui48', 'size': 4, 'label': 'MAC'})
    LnkCtl: Model_16LnkCtl | int | None = Field(default=None, description='Link control flags', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'label': 'Link Control'})
    Pad: int | None = Field(default=None, description='Pad', json_schema_extra={'type': 'pad', 'size': 1})
