"""SunSpec model 132: Volt-Watt

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Volt_watt',
    'Volt_wattCurve',
    'Volt_wattCurveDeptRef',
    'Volt_wattCurveReadOnly',
    'Volt_wattModEna',
]


class Volt_wattCurveDeptRef(SunSpecEnum):
    """Enumeration for point ``Volt_wattCurve.DeptRef`` (enum16)."""
    PCT_WMAX = 1    # %WMax
    PCT_WAVAL = 2    # %WAval


class Volt_wattCurveReadOnly(SunSpecEnum):
    """Enumeration for point ``Volt_wattCurve.ReadOnly`` (enum16)."""
    READWRITE = 0
    READONLY = 1


class Volt_wattModEna(SunSpecFlags):
    """Bitfield for point ``Volt_watt.ModEna`` (bitfield16)."""
    ENABLED = 1


class Volt_wattCurve(SunSpecGroup):
    """curve"""

    GROUP_NAME: ClassVar[str] = 'curve'

    ActPt: int | None = Field(default=None, description='Number of active points in array.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActPt'})
    DeptRef: Volt_wattCurveDeptRef | int | None = Field(default=None, description='Defines the meaning of the Watts DeptRef. 1=% WMax 2=% WAvail', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DeptRef'})
    V1: int | None = Field(default=None, description='Point 1 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'V1'})
    W1: int | None = Field(default=None, description='Point 1 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'W1'})
    V2: int | None = Field(default=None, description='Point 2 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V2'})
    W2: int | None = Field(default=None, description='Point 2 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W2'})
    V3: int | None = Field(default=None, description='Point 3 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V3'})
    W3: int | None = Field(default=None, description='Point 3 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W3'})
    V4: int | None = Field(default=None, description='Point 4 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V4'})
    W4: int | None = Field(default=None, description='Point 4 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W4'})
    V5: int | None = Field(default=None, description='Point 5 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V5'})
    W5: int | None = Field(default=None, description='Point 5 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W5'})
    V6: int | None = Field(default=None, description='Point 6 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V6'})
    W6: int | None = Field(default=None, description='Point 6 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W6'})
    V7: int | None = Field(default=None, description='Point 7 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V7'})
    W7: int | None = Field(default=None, description='Point 7 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W7'})
    V8: int | None = Field(default=None, description='Point 8 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V8'})
    W8: int | None = Field(default=None, description='Point 8 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W8'})
    V9: int | None = Field(default=None, description='Point 9 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V9'})
    W9: int | None = Field(default=None, description='Point 9 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W9'})
    V10: int | None = Field(default=None, description='Point 10 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V10'})
    W10: int | None = Field(default=None, description='Point 10 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W10'})
    V11: int | None = Field(default=None, description='Point 11 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V11'})
    W11: int | None = Field(default=None, description='Point 11 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W11'})
    V12: int | None = Field(default=None, description='Point 12 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V12'})
    W12: int | None = Field(default=None, description='Point 12 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W12'})
    V13: int | None = Field(default=None, description='Point 13 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V13'})
    W13: int | None = Field(default=None, description='Point 13 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W13'})
    V14: int | None = Field(default=None, description='Point 14 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V14'})
    W14: int | None = Field(default=None, description='Point 14 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W14'})
    V15: int | None = Field(default=None, description='Point 15 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V15'})
    W15: int | None = Field(default=None, description='Point 15 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W15'})
    V16: int | None = Field(default=None, description='Point 16 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V16'})
    W16: int | None = Field(default=None, description='Point 16 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W16'})
    V17: int | None = Field(default=None, description='Point 17 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V17'})
    W17: int | None = Field(default=None, description='Point 17 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W17'})
    V18: int | None = Field(default=None, description='Point 18 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V18'})
    W18: int | None = Field(default=None, description='Point 18 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W18'})
    V19: int | None = Field(default=None, description='Point 19 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V19'})
    W19: int | None = Field(default=None, description='Point 19 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W19'})
    V20: int | None = Field(default=None, description='Point 20 Volts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V20'})
    W20: int | None = Field(default=None, description='Point 20 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% VRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'W20'})
    CrvNam: str | None = Field(default=None, description='Optional description for curve.', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'CrvNam'})
    RmpPt1Tms: int | None = Field(default=None, description='The time of the PT1 in seconds (time to accomplish a change of 95%).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpPt1Tms'})
    RmpDecTmm: int | None = Field(default=None, description='The maximum rate at which the watt value may be reduced in response to changes in the voltage value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpDecTmm'})
    RmpIncTmm: int | None = Field(default=None, description='The maximum rate at which the watt value may be increased in response to changes in the voltage value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpIncTmm'})
    ReadOnly: Volt_wattCurveReadOnly | int | None = Field(default=None, description='Curve is read-only or can be modified.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'ReadOnly'})


@register_model
class Volt_watt(SunSpecModel):
    """Volt-Watt"""

    GROUP_NAME: ClassVar[str] = 'volt_watt'
    MODEL_ID: ClassVar[int] = 132
    MODEL_LABEL: ClassVar[str] = 'Volt-Watt'

    ID: int | None = Field(default=132, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 132})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    ActCrv: int | None = Field(default=None, description='Index of active curve. 0=no active curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActCrv'})
    ModEna: Volt_wattModEna | int | None = Field(default=None, description='Is Volt-Watt control active.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    WinTms: int | None = Field(default=None, description='Time window for volt-watt change.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'WinTms'})
    RvrtTms: int | None = Field(default=None, description='Timeout period for volt-watt curve selection.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RvrtTms'})
    RmpTms: int | None = Field(default=None, description='Ramp time for moving from current mode to new mode.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpTms'})
    NCrv: int | None = Field(default=None, description='Number of curves supported (recommend min. 4).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NCrv'})
    NPt: int | None = Field(default=None, description='Number of points in array (maximum 20).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NPt'})
    V_SF: int | None = Field(default=None, description='Scale factor for percent VRef.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'V_SF'})
    DeptRef_SF: int | None = Field(default=None, description='Scale Factor for % DeptRef', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'DeptRef_SF'})
    RmpIncDec_SF: int | None = Field(default=None, description='Scale factor for increment and decrement ramps.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'RmpIncDec_SF'})
    curve: list[Volt_wattCurve] = Field(default_factory=list, description='curve', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
