"""SunSpec model 702: DER Capacity

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERCapacity',
    'DERCapacityAbnOpCatRtg',
    'DERCapacityCtrlModes',
    'DERCapacityIntIslandCat',
    'DERCapacityIntIslandCatRtg',
    'DERCapacityNorOpCatRtg',
]


class DERCapacityNorOpCatRtg(SunSpecEnum):
    """Enumeration for point ``DERCapacity.NorOpCatRtg`` (enum16)."""
    CAT_A = 0    # Category A
    CAT_B = 1    # Category B


class DERCapacityAbnOpCatRtg(SunSpecEnum):
    """Enumeration for point ``DERCapacity.AbnOpCatRtg`` (enum16)."""
    CAT_1 = 0    # Category I
    CAT_2 = 1    # Category II
    CAT_3 = 2    # Category III


class DERCapacityCtrlModes(SunSpecFlags):
    """Bitfield for point ``DERCapacity.CtrlModes`` (bitfield32)."""
    MAX_W = 1    # Limit Maximum Active Power
    FIXED_W = 2    # Fixed Active Power
    FIXED_VAR = 4    # Fixed Reactive Power
    FIXED_PF = 8    # Fixed Power Factor
    VOLT_VAR = 16    # Volt-Var Function
    FREQ_WATT = 32    # Freq-Watt Function
    DYN_REACT_CURR = 64    # Dynamic Reactive Current Function
    LV_TRIP = 128    # Low-Voltage Trip
    HV_TRIP = 256    # High-Voltage Trip
    WATT_VAR = 512    # Watt-Var Function
    VOLT_WATT = 1024    # Volt-Watt Function
    SCHEDULED = 2048    # Scheduling
    LF_TRIP = 4096    # Low-Frequency Trip
    HF_TRIP = 8192    # High-Frequency Trip


class DERCapacityIntIslandCatRtg(SunSpecFlags):
    """Bitfield for point ``DERCapacity.IntIslandCatRtg`` (bitfield16)."""
    UNCATEGORIZED = 1    # Uncategorized
    INT_ISL_CAPABLE = 2    # Intentional Island-Capable
    BLACK_START_CAPABLE = 4    # Black Start-Capable
    ISOCH_CAPABLE = 8    # Isochronous-Capable


class DERCapacityIntIslandCat(SunSpecFlags):
    """Bitfield for point ``DERCapacity.IntIslandCat`` (bitfield16)."""
    UNCATEGORIZED = 1    # Uncategorized
    INT_ISL_CAPABLE = 2    # Intentional Island-Capable
    BLACK_START_CAPABLE = 4    # Black Start-Capable
    ISOCH_CAPABLE = 8    # Isochronous-Capable


@register_model
class DERCapacity(SunSpecModel):
    """DER capacity model."""

    GROUP_NAME: ClassVar[str] = 'DERCapacity'
    MODEL_ID: ClassVar[int] = 702
    MODEL_LABEL: ClassVar[str] = 'DER Capacity'

    ID: int | None = Field(default=702, description='DER capacity model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 702})
    L: int | None = Field(default=None, description='DER capacity model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    WMaxRtg: int | None = Field(default=None, description='Maximum active power rating at unity power factor in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'static': 'S', 'label': 'Active Power Max Rating', 'standards': ['IEEE 1547-2018']})
    WOvrExtRtg: int | None = Field(default=None, description='Active power rating at specified over-excited power factor in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'static': 'S', 'label': 'Active Power (Over-Excited) Rating', 'standards': ['IEEE 1547-2018']})
    WOvrExtRtgPF: int | None = Field(default=None, description='Specified over-excited power factor.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'static': 'S', 'label': 'Specified Over-Excited PF', 'standards': ['IEEE 1547-2018']})
    WUndExtRtg: int | None = Field(default=None, description='Active power rating at specified under-excited power factor in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'static': 'S', 'label': 'Active Power (Under-Excited) Rating', 'standards': ['IEEE 1547-2018']})
    WUndExtRtgPF: int | None = Field(default=None, description='Specified under-excited power factor.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'static': 'S', 'label': 'Specified Under-Excited PF', 'standards': ['IEEE 1547-2018']})
    VAMaxRtg: int | None = Field(default=None, description='Maximum apparent power rating in voltamperes.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'static': 'S', 'label': 'Apparent Power Max Rating', 'standards': ['IEEE 1547-2018']})
    VarMaxInjRtg: int | None = Field(default=None, description='Maximum injected reactive power rating in vars.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Var', 'sf': 'Var_SF', 'static': 'S', 'label': 'Reactive Power Injected Rating', 'standards': ['IEEE 1547-2018']})
    VarMaxAbsRtg: int | None = Field(default=None, description='Maximum absorbed reactive power rating in vars.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Var', 'sf': 'Var_SF', 'static': 'S', 'label': 'Reactive Power Absorbed Rating', 'standards': ['IEEE 1547-2018']})
    WChaRteMaxRtg: int | None = Field(default=None, description='Maximum active power charge rate in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'static': 'S', 'label': 'Charge Rate Max Rating', 'standards': ['IEEE 1547-2018']})
    WDisChaRteMaxRtg: int | None = Field(default=None, description='Maximum active power discharge rate in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'static': 'S', 'label': 'Discharge Rate Max Rating'})
    VAChaRteMaxRtg: int | None = Field(default=None, description='Maximum apparent power charge rate in voltamperes.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'static': 'S', 'label': 'Charge Rate Max VA Rating', 'standards': ['IEEE 1547-2018']})
    VADisChaRteMaxRtg: int | None = Field(default=None, description='Maximum apparent power discharge rate in voltamperes.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'static': 'S', 'label': 'Discharge Rate Max VA Rating'})
    VNomRtg: int | None = Field(default=None, description='AC voltage nominal rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'static': 'S', 'label': 'AC Voltage Nominal Rating', 'standards': ['IEEE 1547-2018']})
    VMaxRtg: int | None = Field(default=None, description='AC voltage maximum rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'static': 'S', 'label': 'AC Voltage Max Rating', 'standards': ['IEEE 1547-2018']})
    VMinRtg: int | None = Field(default=None, description='AC voltage minimum rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'static': 'S', 'label': 'AC Voltage Min Rating', 'standards': ['IEEE 1547-2018']})
    AMaxRtg: int | None = Field(default=None, description='AC current maximum rating in amps.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'static': 'S', 'label': 'AC Current Max Rating'})
    PFOvrExtRtg: int | None = Field(default=None, description='Unused. Please use WOvrExtRtgPF.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'static': 'S', 'label': 'PF Over-Excited Rating (Unused)'})
    PFUndExtRtg: int | None = Field(default=None, description='Unused. Please use WUndExtRtgPF.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'static': 'S', 'label': 'PF Under-Excited Rating (Unused)'})
    ReactSusceptRtg: int | None = Field(default=None, description='Reactive susceptance that remains connected to the Area EPS in the cease to energize and trip state.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'S', 'sf': 'S_SF', 'static': 'S', 'label': 'Reactive Susceptance', 'standards': ['IEEE 1547-2018']})
    NorOpCatRtg: DERCapacityNorOpCatRtg | int | None = Field(default=None, description='Normal operating performance category as specified in IEEE 1547-2018.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'static': 'S', 'label': 'Normal Operating Category', 'standards': ['IEEE 1547-2018']})
    AbnOpCatRtg: DERCapacityAbnOpCatRtg | int | None = Field(default=None, description='Abnormal operating performance category as specified in IEEE 1547-2018.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'static': 'S', 'label': 'Abnormal Operating Category', 'standards': ['IEEE 1547-2018']})
    CtrlModes: DERCapacityCtrlModes | int | None = Field(default=None, description='Supported control mode functions.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'static': 'S', 'label': 'Supported Control Modes', 'standards': ['IEEE 1547-2018']})
    IntIslandCatRtg: DERCapacityIntIslandCatRtg | int | None = Field(default=None, description='Intentional island categories.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'static': 'S', 'label': 'Intentional Island Categories'})
    WMax: int | None = Field(default=None, description='Maximum active power setting used to adjust maximum active power setting.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Active Power Max Setting'})
    WMaxOvrExt: int | None = Field(default=None, description='Active power setting at specified over-excited power factor in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Active Power (Over-Excited) Setting'})
    WOvrExtPF: int | None = Field(default=None, description='Specified over-excited power factor.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Specified Over-Excited PF'})
    WMaxUndExt: int | None = Field(default=None, description='Active power setting at specified under-excited power factor in watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Active Power (Under-Excited) Setting'})
    WUndExtPF: int | None = Field(default=None, description='Specified under-excited power factor.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Specified Under-Excited PF'})
    VAMax: int | None = Field(default=None, description='Maximum apparent power setting used to adjust maximum apparent power rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'access': 'RW', 'label': 'Apparent Power Max Setting'})
    VarMaxInj: int | None = Field(default=None, description='Maximum injected reactive power setting used to adjust maximum injected reactive power rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Var', 'sf': 'Var_SF', 'access': 'RW', 'label': 'Reactive Power Injected Setting'})
    VarMaxAbs: int | None = Field(default=None, description='Maximum absorbed reactive power setting used to adjust maximum absorbed reactive power rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Var', 'sf': 'Var_SF', 'access': 'RW', 'label': 'Reactive Power Absorbed Setting'})
    WChaRteMax: int | None = Field(default=None, description='Maximum active power charge rate setting used to adjust maximum active power charge rate rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Charge Rate Max Setting'})
    WDisChaRteMax: int | None = Field(default=None, description='Maximum active power discharge rate setting used to adjust maximum active power discharge rate rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'Discharge Rate Max Setting'})
    VAChaRteMax: int | None = Field(default=None, description='Maximum apparent power charge rate setting used to adjust maximum apparent power charge rate rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'access': 'RW', 'label': 'Charge Rate Max VA Setting'})
    VADisChaRteMax: int | None = Field(default=None, description='Maximum apparent power discharge rate setting used to adjust maximum apparent power discharge rate rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'access': 'RW', 'label': 'Discharge Rate Max VA Setting'})
    VNom: int | None = Field(default=None, description='Nominal AC voltage setting.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'Nominal AC Voltage Setting'})
    VMax: int | None = Field(default=None, description='AC voltage maximum setting used to adjust AC voltage maximum rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'AC Voltage Max Setting'})
    VMin: int | None = Field(default=None, description='AC voltage minimum setting used to adjust AC voltage minimum rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'access': 'RW', 'label': 'AC Voltage Min Setting'})
    AMax: int | None = Field(default=None, description='Maximum AC current setting used to adjust maximum AC current rating.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'access': 'RW', 'label': 'AC Current Max Setting'})
    PFOvrExt: int | None = Field(default=None, description='Unused. Please use WOvrExtPF.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'PF Over-Excited Setting (Unused)'})
    PFUndExt: int | None = Field(default=None, description='Unused. Please use WUndExtPF.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'PF Under-Excited Setting (Unused)'})
    IntIslandCat: DERCapacityIntIslandCat | int | None = Field(default=None, description='Intentional island categories.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'label': 'Intentional Island Categories'})
    W_SF: int | None = Field(default=None, description='Active power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Active Power Scale Factor'})
    PF_SF: int | None = Field(default=None, description='Power factor scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Power Factor Scale Factor'})
    VA_SF: int | None = Field(default=None, description='Apparent power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Apparent Power Scale Factor'})
    Var_SF: int | None = Field(default=None, description='Reactive power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Reactive Power Scale Factor'})
    V_SF: int | None = Field(default=None, description='Voltage scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Voltage Scale Factor'})
    A_SF: int | None = Field(default=None, description='Current scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Current Scale Factor'})
    S_SF: int | None = Field(default=None, description='Susceptance scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Susceptance Scale Factor'})
