"""SunSpec model 9: Set Operator Security Certificate

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_9',
    'Model_9Alg',
    'Model_9Fmt',
    'Model_9Repeating',
    'Model_9Typ',
]


class Model_9Fmt(SunSpecEnum):
    """Enumeration for point ``Model_9.Fmt`` (enum16)."""
    NONE = 0
    X509_PEM = 1
    X509_DER = 2


class Model_9Typ(SunSpecEnum):
    """Enumeration for point ``Model_9.Typ`` (enum16)."""
    DEV_KEY_PAIR = 0
    DEV_SHARED_KEY = 1
    OPERATOR_PUB = 2
    OPERATOR_SHARED = 3
    CA_PUB = 4


class Model_9Alg(SunSpecEnum):
    """Enumeration for point ``Model_9.Alg`` (enum16)."""
    NONE = 0
    AES_GMAC_64 = 1    # AES-GMAC-64
    ECC_256 = 2    # ECC-256


class Model_9Repeating(SunSpecGroup):
    """repeating"""

    GROUP_NAME: ClassVar[str] = 'repeating'

    Cert: int | None = Field(default=None, description='Cert', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})


@register_model
class Model_9(SunSpecModel):
    """Security model for PKI"""

    GROUP_NAME: ClassVar[str] = 'model_9'
    MODEL_ID: ClassVar[int] = 9
    MODEL_LABEL: ClassVar[str] = 'Set Operator Security Certificate'

    ID: int | None = Field(default=9, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 9})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    CertUID: int | None = Field(default=None, description='User ID for this certificate', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Cert_UID'})
    CertRole: int | None = Field(default=None, description='Role for this certificate', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Cert_Role'})
    Fmt: Model_9Fmt | int | None = Field(default=None, description='Format of this certificate', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Format'})
    Typ: Model_9Typ | int | None = Field(default=None, description='Type of this certificate', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Type'})
    TotLn: int | None = Field(default=None, description='Total Length of the Certificate', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Total Length'})
    FrgLn: int | None = Field(default=None, description='Length of this fragment', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Fragment length'})
    Frg1: int | None = Field(default=None, description='First word of this fragment', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Frag1'})
    Frg2: int | None = Field(default=None, description='Frg2', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg3: int | None = Field(default=None, description='Frg3', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg4: int | None = Field(default=None, description='Frg4', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg5: int | None = Field(default=None, description='Frg5', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg6: int | None = Field(default=None, description='Frg6', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg7: int | None = Field(default=None, description='Frg7', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg8: int | None = Field(default=None, description='Frg8', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg9: int | None = Field(default=None, description='Frg9', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg10: int | None = Field(default=None, description='Frg10', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg11: int | None = Field(default=None, description='Frg11', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg12: int | None = Field(default=None, description='Frg12', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg13: int | None = Field(default=None, description='Frg13', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg14: int | None = Field(default=None, description='Frg14', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg15: int | None = Field(default=None, description='Frg15', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg16: int | None = Field(default=None, description='Frg16', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg17: int | None = Field(default=None, description='Frg17', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg18: int | None = Field(default=None, description='Frg18', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg19: int | None = Field(default=None, description='Frg19', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg20: int | None = Field(default=None, description='Frg20', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg21: int | None = Field(default=None, description='Frg21', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg22: int | None = Field(default=None, description='Frg22', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg23: int | None = Field(default=None, description='Frg23', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg24: int | None = Field(default=None, description='Frg24', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg25: int | None = Field(default=None, description='Frg25', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg26: int | None = Field(default=None, description='Frg26', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg27: int | None = Field(default=None, description='Frg27', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg28: int | None = Field(default=None, description='Frg28', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg29: int | None = Field(default=None, description='Frg29', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg30: int | None = Field(default=None, description='Frg30', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg31: int | None = Field(default=None, description='Frg31', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg32: int | None = Field(default=None, description='Frg32', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg33: int | None = Field(default=None, description='Frg33', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg34: int | None = Field(default=None, description='Frg34', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg35: int | None = Field(default=None, description='Frg35', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg36: int | None = Field(default=None, description='Frg36', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg37: int | None = Field(default=None, description='Frg37', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg38: int | None = Field(default=None, description='Frg38', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg39: int | None = Field(default=None, description='Frg39', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg40: int | None = Field(default=None, description='Frg40', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg41: int | None = Field(default=None, description='Frg41', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg42: int | None = Field(default=None, description='Frg42', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg43: int | None = Field(default=None, description='Frg43', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg44: int | None = Field(default=None, description='Frg44', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg45: int | None = Field(default=None, description='Frg45', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg46: int | None = Field(default=None, description='Frg46', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg47: int | None = Field(default=None, description='Frg47', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg48: int | None = Field(default=None, description='Frg48', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg49: int | None = Field(default=None, description='Frg49', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg50: int | None = Field(default=None, description='Frg50', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg51: int | None = Field(default=None, description='Frg51', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg52: int | None = Field(default=None, description='Frg52', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg53: int | None = Field(default=None, description='Frg53', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg54: int | None = Field(default=None, description='Frg54', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg55: int | None = Field(default=None, description='Frg55', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg56: int | None = Field(default=None, description='Frg56', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg57: int | None = Field(default=None, description='Frg57', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg58: int | None = Field(default=None, description='Frg58', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg59: int | None = Field(default=None, description='Frg59', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg60: int | None = Field(default=None, description='Frg60', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg61: int | None = Field(default=None, description='Frg61', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg62: int | None = Field(default=None, description='Frg62', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg63: int | None = Field(default=None, description='Frg63', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg64: int | None = Field(default=None, description='Frg64', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg65: int | None = Field(default=None, description='Frg65', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg66: int | None = Field(default=None, description='Frg66', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg67: int | None = Field(default=None, description='Frg67', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg68: int | None = Field(default=None, description='Frg68', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg69: int | None = Field(default=None, description='Frg69', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg70: int | None = Field(default=None, description='Frg70', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg71: int | None = Field(default=None, description='Frg71', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg72: int | None = Field(default=None, description='Frg72', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg73: int | None = Field(default=None, description='Frg73', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg74: int | None = Field(default=None, description='Frg74', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg75: int | None = Field(default=None, description='Frg75', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg78: int | None = Field(default=None, description='Frg78', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg79: int | None = Field(default=None, description='Frg79', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Frg80: int | None = Field(default=None, description='Last word of this fragment', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Frag80'})
    Ts: int | None = Field(default=None, description='Timestamp value is the number of seconds since January 1, 2000', json_schema_extra={'type': 'uint32', 'size': 2, 'access': 'RW', 'mandatory': 'M', 'label': 'Timestamp'})
    Ms: int | None = Field(default=None, description='Millisecond counter 0-999', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Milliseconds'})
    Seq: int | None = Field(default=None, description='Sequence number of request', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Sequence'})
    UID: int | None = Field(default=None, description='User ID for the request signature', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'UID'})
    Role: int | None = Field(default=None, description='Signing key used 0-5', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Role'})
    Alg: Model_9Alg | int | None = Field(default=None, description='Algorithm used to compute the digital signature', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Algorithm'})
    N: int | None = Field(default=None, description='Number of registers to follow for the certificate', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'N'})
    repeating: list[Model_9Repeating] = Field(default_factory=list, description='repeating', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
