"""SunSpec model 134: Freq-Watt Crv

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Freq_watt',
    'Freq_wattCurve',
    'Freq_wattCurveReadOnly',
    'Freq_wattModEna',
]


class Freq_wattCurveReadOnly(SunSpecEnum):
    """Enumeration for point ``Freq_wattCurve.ReadOnly`` (enum16)."""
    READWRITE = 0
    READONLY = 1


class Freq_wattModEna(SunSpecFlags):
    """Bitfield for point ``Freq_watt.ModEna`` (bitfield16)."""
    ENABLED = 1


class Freq_wattCurve(SunSpecGroup):
    """curve"""

    GROUP_NAME: ClassVar[str] = 'curve'

    ActPt: int | None = Field(default=None, description='Number of active points in array.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActPt'})
    Hz1: int | None = Field(default=None, description='Point 1 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Hz1'})
    W1: int | None = Field(default=None, description='Point 1 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'W1'})
    Hz2: int | None = Field(default=None, description='Point 2 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz2'})
    W2: int | None = Field(default=None, description='Point 2 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W2'})
    Hz3: int | None = Field(default=None, description='Point 3 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz3'})
    W3: int | None = Field(default=None, description='Point 3 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W3'})
    Hz4: int | None = Field(default=None, description='Point 4 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz4'})
    W4: int | None = Field(default=None, description='Point 4 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W4'})
    Hz5: int | None = Field(default=None, description='Point 5 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz5'})
    W5: int | None = Field(default=None, description='Point 5 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W5'})
    Hz6: int | None = Field(default=None, description='Point 6 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz6'})
    W6: int | None = Field(default=None, description='Point 6 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W6'})
    Hz7: int | None = Field(default=None, description='Point 7 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz7'})
    W7: int | None = Field(default=None, description='Point 7 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W7'})
    Hz8: int | None = Field(default=None, description='Point 8 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz8'})
    W8: int | None = Field(default=None, description='Point 8 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W8'})
    Hz9: int | None = Field(default=None, description='Point 9 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz9'})
    W9: int | None = Field(default=None, description='Point 9 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W9'})
    Hz10: int | None = Field(default=None, description='Point 10 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz10'})
    W10: int | None = Field(default=None, description='Point 10 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W10'})
    Hz11: int | None = Field(default=None, description='Point 11 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz11'})
    W11: int | None = Field(default=None, description='Point 11 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W11'})
    Hz12: int | None = Field(default=None, description='Point 12 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz12'})
    W12: int | None = Field(default=None, description='Point 12 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W12'})
    Hz13: int | None = Field(default=None, description='Point 13 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz13'})
    W13: int | None = Field(default=None, description='Point 13 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W13'})
    Hz14: int | None = Field(default=None, description='Point 14 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz14'})
    W14: int | None = Field(default=None, description='Point 14 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W14'})
    Hz15: int | None = Field(default=None, description='Point 15 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz15'})
    W15: int | None = Field(default=None, description='Point 15 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W15'})
    Hz16: int | None = Field(default=None, description='Point 16 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz16'})
    W16: int | None = Field(default=None, description='Point 16 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W16'})
    Hz17: int | None = Field(default=None, description='Point 17 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz17'})
    W17: int | None = Field(default=None, description='Point 17 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W17'})
    Hz18: int | None = Field(default=None, description='Point 18 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz18'})
    W18: int | None = Field(default=None, description='Point 18 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W18'})
    Hz19: int | None = Field(default=None, description='Point 19 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz19'})
    W19: int | None = Field(default=None, description='Point 19 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W19'})
    Hz20: int | None = Field(default=None, description='Point 20 Hertz.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'Hz20'})
    W20: int | None = Field(default=None, description='Point 20 Watts.', json_schema_extra={'type': 'int16', 'size': 1, 'units': '% WRef', 'sf': 'W_SF', 'access': 'RW', 'label': 'W20'})
    CrvNam: str | None = Field(default=None, description='Optional description for curve. (Max 16 chars)', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'CrvNam'})
    RmpPT1Tms: int | None = Field(default=None, description='The time of the PT1 in seconds (time to accomplish a change of 95%).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpPT1Tms'})
    RmpDecTmm: int | None = Field(default=None, description='The maximum rate at which the power value may be reduced in response to changes in the frequency value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpDecTmm'})
    RmpIncTmm: int | None = Field(default=None, description='The maximum rate at which the power value may be increased in response to changes in the frequency value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpIncTmm'})
    RmpRsUp: int | None = Field(default=None, description='The maximum rate at which the power may be increased after releasing the frozen value of snap shot function.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% WMax/min', 'sf': 'RmpIncDec_SF', 'access': 'RW', 'label': 'RmpRsUp'})
    SnptW: int | None = Field(default=None, description='1=enable snapshot/capture mode', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'SnptW'})
    WRef: int | None = Field(default=None, description='Reference active power (default = WMax).', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'access': 'RW', 'label': 'WRef'})
    WRefStrHz: int | None = Field(default=None, description='Frequency deviation from nominal frequency at the time of the snapshot to start constraining power output.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'WRefStrHz'})
    WRefStopHz: int | None = Field(default=None, description='Frequency deviation from nominal frequency at which to release the power output.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'access': 'RW', 'label': 'WRefStopHz'})
    ReadOnly: Freq_wattCurveReadOnly | int | None = Field(default=None, description='Curve is read-only or can be modified.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'ReadOnly'})


@register_model
class Freq_watt(SunSpecModel):
    """Curve-Based Frequency-Watt"""

    GROUP_NAME: ClassVar[str] = 'freq_watt'
    MODEL_ID: ClassVar[int] = 134
    MODEL_LABEL: ClassVar[str] = 'Freq-Watt Crv'

    ID: int | None = Field(default=134, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 134})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    ActCrv: int | None = Field(default=None, description='Index of active curve. 0=no active curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActCrv'})
    ModEna: Freq_wattModEna | int | None = Field(default=None, description='Is curve-based Frequency-Watt control active.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    WinTms: int | None = Field(default=None, description='Time window for freq-watt change.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'WinTms'})
    RvrtTms: int | None = Field(default=None, description='Timeout period for freq-watt curve selection.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RvrtTms'})
    RmpTms: int | None = Field(default=None, description='Ramp time for moving from current mode to new mode.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpTms'})
    NCrv: int | None = Field(default=None, description='Number of curves supported (recommend min. 4).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NCrv'})
    NPt: int | None = Field(default=None, description='Number of curve points supported (maximum of 20).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NPt'})
    Hz_SF: int | None = Field(default=None, description='Scale factor for frequency.', json_schema_extra={'type': 'sunssf', 'size': 1, 'units': 'SF', 'mandatory': 'M', 'label': 'Hz_SF'})
    W_SF: int | None = Field(default=None, description='Scale factor for percent WRef.', json_schema_extra={'type': 'sunssf', 'size': 1, 'units': 'SF', 'mandatory': 'M', 'label': 'W_SF'})
    RmpIncDec_SF: int | None = Field(default=None, description='Scale factor for increment and decrement ramps.', json_schema_extra={'type': 'sunssf', 'size': 1, 'units': 'SF', 'label': 'RmpIncDec_SF'})
    curve: list[Freq_wattCurve] = Field(default_factory=list, description='curve', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
