"""SunSpec model 501: Solar Module

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Solar_module_float',
    'Solar_module_floatEvt',
    'Solar_module_floatStat',
]


class Solar_module_floatStat(SunSpecEnum):
    """Enumeration for point ``Solar_module_float.Stat`` (enum16)."""
    OFF = 1
    SLEEPING = 2
    STARTING = 3
    MPPT = 4
    THROTTLED = 5
    SHUTTING_DOWN = 6
    FAULT = 7
    STANDBY = 8
    TEST = 9
    OTHER = 10


class Solar_module_floatEvt(SunSpecFlags):
    """Bitfield for point ``Solar_module_float.Evt`` (bitfield32)."""
    GROUND_FAULT = 1
    INPUT_OVER_VOLTAGE = 2
    RESERVED_2 = 4
    DC_DISCONNECT = 8
    RESERVED_4 = 16
    RESERVED_5 = 32
    MANUAL_SHUTDOWN = 64
    OVER_TEMPERATURE = 128
    RESERVED_8 = 256
    RESERVED_9 = 512
    RESERVED_10 = 1024
    RESERVED_11 = 2048
    BLOWN_FUSE = 4096
    UNDER_TEMPERATURE = 8192
    MEMORY_LOSS = 16384
    ARC_DETECTION = 32768
    THEFT_DETECTION = 65536
    OUTPUT_OVER_CURRENT = 131072
    OUTPUT_OVER_VOLTAGE = 262144
    OUTPUT_UNDER_VOLTAGE = 524288
    TEST_FAILED = 1048576


@register_model
class Solar_module_float(SunSpecModel):
    """A solar module model supporting DC-DC converter"""

    GROUP_NAME: ClassVar[str] = 'solar_module_float'
    MODEL_ID: ClassVar[int] = 501
    MODEL_LABEL: ClassVar[str] = 'Solar Module'

    ID: int | None = Field(default=501, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 501})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Stat: Solar_module_floatStat | int | None = Field(default=None, description='Module Status Code', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Status'})
    StatVend: int | None = Field(default=None, description='Module Vendor Status Code', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Vendor Status'})
    Evt: Solar_module_floatEvt | int | None = Field(default=None, description='Module Event Flags', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Events'})
    EvtVend: int | None = Field(default=None, description='Vendor specific flags', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Module Event Flags'})
    Ctl: int | None = Field(default=None, description='Module Control', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Control'})
    CtlVend: int | None = Field(default=None, description='Vendor Module Control', json_schema_extra={'type': 'enum32', 'size': 2, 'access': 'RW', 'label': 'Vendor Control'})
    CtlVal: int | None = Field(default=None, description='Module Control Value', json_schema_extra={'type': 'int32', 'size': 2, 'access': 'RW', 'label': 'Control Value'})
    Tms: int | None = Field(default=None, description='Time in seconds since 2000 epoch', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Timestamp'})
    OutA: float | None = Field(default=None, description='Output Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'label': 'Output Current'})
    OutV: float | None = Field(default=None, description='Output Voltage', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Output Voltage'})
    OutWh: float | None = Field(default=None, description='Output Energy', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'Wh', 'label': 'Output Energy'})
    OutW: float | None = Field(default=None, description='Output Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'W', 'label': 'Output Power'})
    Tmp: float | None = Field(default=None, description='Module Temperature', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'C', 'label': 'Temp'})
    InA: float | None = Field(default=None, description='Input Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'label': 'Input Current'})
    InV: float | None = Field(default=None, description='Input Voltage', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Input Voltage'})
    InWh: float | None = Field(default=None, description='Input Energy', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'Wh', 'label': 'Input Energy'})
    InW: float | None = Field(default=None, description='Input Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'W', 'label': 'Input Power'})
