"""SunSpec model 802: Battery Base Model

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Battery',
    'BatteryChaSt',
    'BatteryEvt1',
    'BatteryLocRemCtl',
    'BatteryReqInvState',
    'BatterySetInvState',
    'BatterySetOp',
    'BatteryState',
    'BatteryTyp',
]


class BatteryChaSt(SunSpecEnum):
    """Enumeration for point ``Battery.ChaSt`` (enum16)."""
    OFF = 1
    EMPTY = 2
    DISCHARGING = 3
    CHARGING = 4
    FULL = 5
    HOLDING = 6
    TESTING = 7


class BatteryLocRemCtl(SunSpecEnum):
    """Enumeration for point ``Battery.LocRemCtl`` (enum16)."""
    REMOTE = 0
    LOCAL = 1


class BatteryTyp(SunSpecEnum):
    """Enumeration for point ``Battery.Typ`` (enum16)."""
    NOT_APPLICABLE_UNKNOWN = 0    # NOT APPLICABLE_UNKNOWN
    LEAD_ACID = 1
    NICKEL_METAL_HYDRATE = 2
    NICKEL_CADMIUM = 3
    LITHIUM_ION = 4
    CARBON_ZINC = 5
    ZINC_CHLORIDE = 6
    ALKALINE = 7
    RECHARGEABLE_ALKALINE = 8
    SODIUM_SULFUR = 9
    FLOW = 10
    OTHER = 99


class BatteryState(SunSpecEnum):
    """Enumeration for point ``Battery.State`` (enum16)."""
    DISCONNECTED = 1
    INITIALIZING = 2
    CONNECTED = 3
    STANDBY = 4
    SOC_PROTECTION = 5    # SOC PROTECTION
    SUSPENDING = 6
    FAULT = 99


class BatteryEvt1(SunSpecFlags):
    """Bitfield for point ``Battery.Evt1`` (bitfield32)."""
    COMMUNICATION_ERROR = 1
    OVER_TEMP_ALARM = 2
    OVER_TEMP_WARNING = 4
    UNDER_TEMP_ALARM = 8
    UNDER_TEMP_WARNING = 16
    OVER_CHARGE_CURRENT_ALARM = 32
    OVER_CHARGE_CURRENT_WARNING = 64
    OVER_DISCHARGE_CURRENT_ALARM = 128
    OVER_DISCHARGE_CURRENT_WARNING = 256
    OVER_VOLT_ALARM = 512
    OVER_VOLT_WARNING = 1024
    UNDER_VOLT_ALARM = 2048
    UNDER_VOLT_WARNING = 4096
    UNDER_SOC_MIN_ALARM = 8192
    UNDER_SOC_MIN_WARNING = 16384
    OVER_SOC_MAX_ALARM = 32768
    OVER_SOC_MAX_WARNING = 65536
    VOLTAGE_IMBALANCE_WARNING = 131072
    TEMPERATURE_IMBALANCE_ALARM = 262144
    TEMPERATURE_IMBALANCE_WARNING = 524288
    CONTACTOR_ERROR = 1048576
    FAN_ERROR = 2097152
    GROUND_FAULT = 4194304
    OPEN_DOOR_ERROR = 8388608
    CURRENT_IMBALANCE_WARNING = 16777216
    OTHER_ALARM = 33554432
    OTHER_WARNING = 67108864
    RESERVED_1 = 134217728
    CONFIGURATION_ALARM = 268435456
    CONFIGURATION_WARNING = 536870912


class BatteryReqInvState(SunSpecEnum):
    """Enumeration for point ``Battery.ReqInvState`` (enum16)."""
    NO_REQUEST = 0    # NO REQUEST
    START = 1
    STOP = 2


class BatterySetOp(SunSpecEnum):
    """Enumeration for point ``Battery.SetOp`` (enum16)."""
    CONNECT = 1
    DISCONNECT = 2


class BatterySetInvState(SunSpecEnum):
    """Enumeration for point ``Battery.SetInvState`` (enum16)."""
    INVERTER_STOPPED = 1
    INVERTER_STANDBY = 2
    INVERTER_STARTED = 3


@register_model
class Battery(SunSpecModel):
    """Battery Base Model"""

    GROUP_NAME: ClassVar[str] = 'battery'
    MODEL_ID: ClassVar[int] = 802
    MODEL_LABEL: ClassVar[str] = 'Battery Base Model'

    ID: int | None = Field(default=802, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 802})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    AHRtg: int | None = Field(default=None, description='Nameplate charge capacity in amp-hours.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Ah', 'sf': 'AHRtg_SF', 'mandatory': 'M', 'label': 'Nameplate Charge Capacity'})
    WHRtg: int | None = Field(default=None, description='Nameplate energy capacity in DC watt-hours.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Wh', 'sf': 'WHRtg_SF', 'mandatory': 'M', 'label': 'Nameplate Energy Capacity'})
    WChaRteMax: int | None = Field(default=None, description='Maximum rate of energy transfer into the storage device in DC watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'WChaDisChaMax_SF', 'mandatory': 'M', 'label': 'Nameplate Max Charge Rate'})
    WDisChaRteMax: int | None = Field(default=None, description='Maximum rate of energy transfer out of the storage device in DC watts.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'WChaDisChaMax_SF', 'mandatory': 'M', 'label': 'Nameplate Max Discharge Rate'})
    DisChaRte: int | None = Field(default=None, description='Self discharge rate. Percentage of capacity (WHRtg) discharged per day.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'DisChaRte_SF', 'label': 'Self Discharge Rate'})
    SoCMax: int | None = Field(default=None, description='Manufacturer maximum state of charge, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'SoC_SF', 'label': 'Nameplate Max SoC'})
    SoCMin: int | None = Field(default=None, description='Manufacturer minimum state of charge, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'SoC_SF', 'label': 'Nameplate Min SoC'})
    SocRsvMax: int | None = Field(default=None, description='Setpoint for maximum reserve for storage as a percentage of the nominal maximum storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'SoC_SF', 'access': 'RW', 'label': 'Max Reserve Percent'})
    SoCRsvMin: int | None = Field(default=None, description='Setpoint for minimum reserve for storage as a percentage of the nominal maximum storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'SoC_SF', 'access': 'RW', 'label': 'Min Reserve Percent'})
    SoC: int | None = Field(default=None, description='State of charge, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%WHRtg', 'sf': 'SoC_SF', 'mandatory': 'M', 'label': 'State of Charge'})
    DoD: int | None = Field(default=None, description='Depth of discharge, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%', 'sf': 'DoD_SF', 'label': 'Depth of Discharge'})
    SoH: int | None = Field(default=None, description='Percentage of battery life remaining.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%', 'sf': 'SoH_SF', 'label': 'State of Health'})
    NCyc: int | None = Field(default=None, description='Number of cycles executed in the battery.', json_schema_extra={'type': 'uint32', 'size': 2, 'label': 'Cycle Count'})
    ChaSt: BatteryChaSt | int | None = Field(default=None, description='Charge status of storage device. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Charge Status'})
    LocRemCtl: BatteryLocRemCtl | int | None = Field(default=None, description='Battery control mode. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Control Mode'})
    Hb: int | None = Field(default=None, description='Value is incremented every second with periodic resets to zero.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Battery Heartbeat'})
    CtrlHb: int | None = Field(default=None, description='Value is incremented every second with periodic resets to zero.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Controller Heartbeat'})
    AlmRst: int | None = Field(default=None, description='Used to reset any latched alarms. 1 = Reset.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Alarm Reset'})
    Typ: BatteryTyp | int | None = Field(default=None, description='Type of battery. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Battery Type'})
    State: BatteryState | int | None = Field(default=None, description='State of the battery bank. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'State of the Battery Bank'})
    StateVnd: int | None = Field(default=None, description='Vendor specific battery bank state. Enumeration.', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Vendor Battery Bank State'})
    WarrDt: int | None = Field(default=None, description='Date the device warranty expires.', json_schema_extra={'type': 'uint32', 'size': 2, 'label': 'Warranty Date'})
    Evt1: BatteryEvt1 | int | None = Field(default=None, description='Alarms and warnings.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Battery Event 1 Bitfield'})
    Evt2: int | None = Field(default=None, description='Alarms and warnings.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Battery Event 2 Bitfield'})
    EvtVnd1: int | None = Field(default=None, description='Vendor defined events.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Vendor Event Bitfield 1'})
    EvtVnd2: int | None = Field(default=None, description='Vendor defined events.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Vendor Event Bitfield 2'})
    V: int | None = Field(default=None, description='DC Bus Voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'External Battery Voltage'})
    VMax: int | None = Field(default=None, description='Instantaneous maximum battery voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Max Battery Voltage'})
    VMin: int | None = Field(default=None, description='Instantaneous minimum battery voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Min Battery Voltage'})
    CellVMax: int | None = Field(default=None, description='Maximum voltage for all cells in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'label': 'Max Cell Voltage'})
    CellVMaxStr: int | None = Field(default=None, description='String containing the cell with maximum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Cell Voltage String'})
    CellVMaxMod: int | None = Field(default=None, description='Module containing the cell with maximum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Cell Voltage Module'})
    CellVMin: int | None = Field(default=None, description='Minimum voltage for all cells in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'label': 'Min Cell Voltage'})
    CellVMinStr: int | None = Field(default=None, description='String containing the cell with minimum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Cell Voltage String'})
    CellVMinMod: int | None = Field(default=None, description='Module containing the cell with minimum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Cell Voltage Module'})
    CellVAvg: int | None = Field(default=None, description='Average cell voltage for all cells in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'label': 'Average Cell Voltage'})
    A: int | None = Field(default=None, description='Total DC current flowing to/from the battery bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Total DC Current'})
    AChaMax: int | None = Field(default=None, description='Instantaneous maximum DC charge current.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'AMax_SF', 'label': 'Max Charge Current'})
    ADisChaMax: int | None = Field(default=None, description='Instantaneous maximum DC discharge current.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'AMax_SF', 'label': 'Max Discharge Current'})
    W: int | None = Field(default=None, description='Total power flowing to/from the battery bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'mandatory': 'M', 'label': 'Total Power'})
    ReqInvState: BatteryReqInvState | int | None = Field(default=None, description='Request from battery to start or stop the inverter. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Inverter State Request'})
    ReqW: int | None = Field(default=None, description='AC Power requested by battery.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Battery Power Request'})
    SetOp: BatterySetOp | int | None = Field(default=None, description='Instruct the battery bank to perform an operation such as connecting. Enumeration.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Set Operation'})
    SetInvState: BatterySetInvState | int | None = Field(default=None, description='Set the current state of the inverter.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Set Inverter State'})
    AHRtg_SF: int | None = Field(default=None, description='Scale factor for charge capacity.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    WHRtg_SF: int | None = Field(default=None, description='Scale factor for energy capacity.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    WChaDisChaMax_SF: int | None = Field(default=None, description='Scale factor for maximum charge and discharge rate.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    DisChaRte_SF: int | None = Field(default=None, description='Scale factor for self discharge rate.', json_schema_extra={'type': 'sunssf', 'size': 1})
    SoC_SF: int | None = Field(default=None, description='Scale factor for state of charge values.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    DoD_SF: int | None = Field(default=None, description='Scale factor for depth of discharge.', json_schema_extra={'type': 'sunssf', 'size': 1})
    SoH_SF: int | None = Field(default=None, description='Scale factor for state of health.', json_schema_extra={'type': 'sunssf', 'size': 1})
    V_SF: int | None = Field(default=None, description='Scale factor for DC bus voltage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    CellV_SF: int | None = Field(default=None, description='Scale factor for cell voltage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    A_SF: int | None = Field(default=None, description='Scale factor for DC current.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    AMax_SF: int | None = Field(default=None, description='Scale factor for instantaneous DC charge/discharge current.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    W_SF: int | None = Field(default=None, description='Scale factor for AC power request.', json_schema_extra={'type': 'sunssf', 'size': 1})
