"""SunSpec model 203: wye-connect three phase (abcn) meter

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Ac_meter_abcn',
    'Ac_meter_abcnEvt',
]


class Ac_meter_abcnEvt(SunSpecFlags):
    """Bitfield for point ``Ac_meter_abcn.Evt`` (bitfield32)."""
    M_EVENT_POWER_FAILURE = 4    # M_EVENT_Power_Failure
    M_EVENT_UNDER_VOLTAGE = 8    # M_EVENT_Under_Voltage
    M_EVENT_LOW_PF = 16    # M_EVENT_Low_PF
    M_EVENT_OVER_CURRENT = 32    # M_EVENT_Over_Current
    M_EVENT_OVER_VOLTAGE = 64    # M_EVENT_Over_Voltage
    M_EVENT_MISSING_SENSOR = 128    # M_EVENT_Missing_Sensor
    M_EVENT_RESERVED1 = 256    # M_EVENT_Reserved1
    M_EVENT_RESERVED2 = 512    # M_EVENT_Reserved2
    M_EVENT_RESERVED3 = 1024    # M_EVENT_Reserved3
    M_EVENT_RESERVED4 = 2048    # M_EVENT_Reserved4
    M_EVENT_RESERVED5 = 4096    # M_EVENT_Reserved5
    M_EVENT_RESERVED6 = 8192    # M_EVENT_Reserved6
    M_EVENT_RESERVED7 = 16384    # M_EVENT_Reserved7
    M_EVENT_RESERVED8 = 32768    # M_EVENT_Reserved8
    M_EVENT_OEM01 = 65536
    M_EVENT_OEM02 = 131072
    M_EVENT_OEM03 = 262144
    M_EVENT_OEM04 = 524288
    M_EVENT_OEM05 = 1048576
    M_EVENT_OEM06 = 2097152
    M_EVENT_OEM07 = 4194304
    M_EVENT_OEM08 = 8388608
    M_EVENT_OEM09 = 16777216
    M_EVENT_OEM10 = 33554432
    M_EVENT_OEM11 = 67108864
    M_EVENT_OEM12 = 134217728
    M_EVENT_OEM13 = 268435456
    M_EVENT_OEM14 = 536870912
    M_EVENT_OEM15 = 1073741824


@register_model
class Ac_meter_abcn(SunSpecModel):
    """wye-connect three phase (abcn) meter"""

    GROUP_NAME: ClassVar[str] = 'ac_meter_abcn'
    MODEL_ID: ClassVar[int] = 203
    MODEL_LABEL: ClassVar[str] = 'wye-connect three phase (abcn) meter'

    ID: int | None = Field(default=203, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 203})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    A: int | None = Field(default=None, description='Total AC Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Amps'})
    AphA: int | None = Field(default=None, description='Phase A Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Amps PhaseA'})
    AphB: int | None = Field(default=None, description='Phase B Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Amps PhaseB'})
    AphC: int | None = Field(default=None, description='Phase C Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Amps PhaseC'})
    A_SF: int | None = Field(default=None, description='Current scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    PhV: int | None = Field(default=None, description='Line to Neutral AC Voltage (average of active phases)', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Voltage LN'})
    PhVphA: int | None = Field(default=None, description='Phase Voltage AN', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage AN'})
    PhVphB: int | None = Field(default=None, description='Phase Voltage BN', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage BN'})
    PhVphC: int | None = Field(default=None, description='Phase Voltage CN', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage CN'})
    PPV: int | None = Field(default=None, description='Line to Line AC Voltage (average of active phases)', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Voltage LL'})
    PhVphAB: int | None = Field(default=None, description='Phase Voltage AB', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage AB'})
    PhVphBC: int | None = Field(default=None, description='Phase Voltage BC', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage BC'})
    PhVphCA: int | None = Field(default=None, description='Phase Voltage CA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Phase Voltage CA'})
    V_SF: int | None = Field(default=None, description='Voltage scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    Hz: int | None = Field(default=None, description='Frequency', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Hz', 'sf': 'Hz_SF', 'mandatory': 'M', 'label': 'Hz'})
    Hz_SF: int | None = Field(default=None, description='Frequency scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    W: int | None = Field(default=None, description='Total Real Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'mandatory': 'M', 'label': 'Watts'})
    WphA: int | None = Field(default=None, description='Watts phase A', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Watts phase A'})
    WphB: int | None = Field(default=None, description='Watts phase B', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Watts phase B'})
    WphC: int | None = Field(default=None, description='Watts phase C', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Watts phase C'})
    W_SF: int | None = Field(default=None, description='Real Power scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    VA: int | None = Field(default=None, description='AC Apparent Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'label': 'VA'})
    VAphA: int | None = Field(default=None, description='VA phase A', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'label': 'VA phase A'})
    VAphB: int | None = Field(default=None, description='VA phase B', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'label': 'VA phase B'})
    VAphC: int | None = Field(default=None, description='VA phase C', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'VA', 'sf': 'VA_SF', 'label': 'VA phase C'})
    VA_SF: int | None = Field(default=None, description='Apparent Power scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    VAR: int | None = Field(default=None, description='Reactive Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'var', 'sf': 'VAR_SF', 'label': 'VAR'})
    VARphA: int | None = Field(default=None, description='VAR phase A', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'var', 'sf': 'VAR_SF', 'label': 'VAR phase A'})
    VARphB: int | None = Field(default=None, description='VAR phase B', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'var', 'sf': 'VAR_SF', 'label': 'VAR phase B'})
    VARphC: int | None = Field(default=None, description='VAR phase C', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'var', 'sf': 'VAR_SF', 'label': 'VAR phase C'})
    VAR_SF: int | None = Field(default=None, description='Reactive Power scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    PF: int | None = Field(default=None, description='Power Factor', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'PF_SF', 'label': 'PF'})
    PFphA: int | None = Field(default=None, description='PF phase A', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'PF_SF', 'label': 'PF phase A'})
    PFphB: int | None = Field(default=None, description='PF phase B', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'PF_SF', 'label': 'PF phase B'})
    PFphC: int | None = Field(default=None, description='PF phase C', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'PF_SF', 'label': 'PF phase C'})
    PF_SF: int | None = Field(default=None, description='Power Factor scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    TotWhExp: int | None = Field(default=None, description='Total Real Energy Exported', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'mandatory': 'M', 'label': 'Total Watt-hours Exported'})
    TotWhExpPhA: int | None = Field(default=None, description='Total Watt-hours Exported phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Exported phase A'})
    TotWhExpPhB: int | None = Field(default=None, description='Total Watt-hours Exported phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Exported phase B'})
    TotWhExpPhC: int | None = Field(default=None, description='Total Watt-hours Exported phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Exported phase C'})
    TotWhImp: int | None = Field(default=None, description='Total Real Energy Imported', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'mandatory': 'M', 'label': 'Total Watt-hours Imported'})
    TotWhImpPhA: int | None = Field(default=None, description='Total Watt-hours Imported phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Imported phase A'})
    TotWhImpPhB: int | None = Field(default=None, description='Total Watt-hours Imported phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Imported phase B'})
    TotWhImpPhC: int | None = Field(default=None, description='Total Watt-hours Imported phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'TotWh_SF', 'label': 'Total Watt-hours Imported phase C'})
    TotWh_SF: int | None = Field(default=None, description='Real Energy scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    TotVAhExp: int | None = Field(default=None, description='Total Apparent Energy Exported', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Exported'})
    TotVAhExpPhA: int | None = Field(default=None, description='Total VA-hours Exported phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Exported phase A'})
    TotVAhExpPhB: int | None = Field(default=None, description='Total VA-hours Exported phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Exported phase B'})
    TotVAhExpPhC: int | None = Field(default=None, description='Total VA-hours Exported phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Exported phase C'})
    TotVAhImp: int | None = Field(default=None, description='Total Apparent Energy Imported', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Imported'})
    TotVAhImpPhA: int | None = Field(default=None, description='Total VA-hours Imported phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Imported phase A'})
    TotVAhImpPhB: int | None = Field(default=None, description='Total VA-hours Imported phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Imported phase B'})
    TotVAhImpPhC: int | None = Field(default=None, description='Total VA-hours Imported phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'VAh', 'sf': 'TotVAh_SF', 'label': 'Total VA-hours Imported phase C'})
    TotVAh_SF: int | None = Field(default=None, description='Apparent Energy scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    TotVArhImpQ1: int | None = Field(default=None, description='Total Reactive Energy Imported Quadrant 1', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAR-hours Imported Q1'})
    TotVArhImpQ1PhA: int | None = Field(default=None, description='Total VAr-hours Imported Q1 phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q1 phase A'})
    TotVArhImpQ1PhB: int | None = Field(default=None, description='Total VAr-hours Imported Q1 phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q1 phase B'})
    TotVArhImpQ1PhC: int | None = Field(default=None, description='Total VAr-hours Imported Q1 phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q1 phase C'})
    TotVArhImpQ2: int | None = Field(default=None, description='Total Reactive Power Imported Quadrant 2', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q2'})
    TotVArhImpQ2PhA: int | None = Field(default=None, description='Total VAr-hours Imported Q2 phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q2 phase A'})
    TotVArhImpQ2PhB: int | None = Field(default=None, description='Total VAr-hours Imported Q2 phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q2 phase B'})
    TotVArhImpQ2PhC: int | None = Field(default=None, description='Total VAr-hours Imported Q2 phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Imported Q2 phase C'})
    TotVArhExpQ3: int | None = Field(default=None, description='Total Reactive Power Exported Quadrant 3', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q3'})
    TotVArhExpQ3PhA: int | None = Field(default=None, description='Total VAr-hours Exported Q3 phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q3 phase A'})
    TotVArhExpQ3PhB: int | None = Field(default=None, description='Total VAr-hours Exported Q3 phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q3 phase B'})
    TotVArhExpQ3PhC: int | None = Field(default=None, description='Total VAr-hours Exported Q3 phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q3 phase C'})
    TotVArhExpQ4: int | None = Field(default=None, description='Total Reactive Power Exported Quadrant 4', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q4'})
    TotVArhExpQ4PhA: int | None = Field(default=None, description='Total VAr-hours Exported Q4 Imported phase A', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q4 Imported phase A'})
    TotVArhExpQ4PhB: int | None = Field(default=None, description='Total VAr-hours Exported Q4 Imported phase B', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q4 Imported phase B'})
    TotVArhExpQ4PhC: int | None = Field(default=None, description='Total VAr-hours Exported Q4 Imported phase C', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'varh', 'sf': 'TotVArh_SF', 'label': 'Total VAr-hours Exported Q4 Imported phase C'})
    TotVArh_SF: int | None = Field(default=None, description='Reactive Energy scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    Evt: Ac_meter_abcnEvt | int | None = Field(default=None, description='Meter Event Flags', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Events'})
