"""SunSpec model 3: Secure Dataset Read Request

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_3',
    'Model_3Alg',
    'Model_3Repeating',
]


class Model_3Alg(SunSpecEnum):
    """Enumeration for point ``Model_3.Alg`` (enum16)."""
    NONE = 0
    AES_GMAC_64 = 1    # AES-GMAC-64
    ECC_256 = 2    # ECC-256


class Model_3Repeating(SunSpecGroup):
    """repeating"""

    GROUP_NAME: ClassVar[str] = 'repeating'

    DS: int | None = Field(default=None, description='Digital Signature', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'DS'})


@register_model
class Model_3(SunSpecModel):
    """Request a digital signature over a specified set of data registers"""

    GROUP_NAME: ClassVar[str] = 'model_3'
    MODEL_ID: ClassVar[int] = 3
    MODEL_LABEL: ClassVar[str] = 'Secure Dataset Read Request'

    ID: int | None = Field(default=3, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 3})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    X: int | None = Field(default=None, description='Number of registers being requested', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'X'})
    Off1: int | None = Field(default=None, description='Offset of value to read', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Offset1'})
    Off2: int | None = Field(default=None, description='Off2', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off3: int | None = Field(default=None, description='Off3', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off4: int | None = Field(default=None, description='Off4', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off5: int | None = Field(default=None, description='Off5', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off6: int | None = Field(default=None, description='Off6', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off7: int | None = Field(default=None, description='Off7', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off8: int | None = Field(default=None, description='Off8', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off9: int | None = Field(default=None, description='Off9', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off10: int | None = Field(default=None, description='Off10', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off11: int | None = Field(default=None, description='Off11', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off12: int | None = Field(default=None, description='Off12', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off13: int | None = Field(default=None, description='Off13', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off14: int | None = Field(default=None, description='Off14', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off15: int | None = Field(default=None, description='Off15', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off16: int | None = Field(default=None, description='Off16', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off17: int | None = Field(default=None, description='Off17', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off18: int | None = Field(default=None, description='Off18', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off19: int | None = Field(default=None, description='Off19', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off20: int | None = Field(default=None, description='Off20', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off21: int | None = Field(default=None, description='Off21', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off22: int | None = Field(default=None, description='Off22', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off23: int | None = Field(default=None, description='Off23', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off24: int | None = Field(default=None, description='Off24', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off25: int | None = Field(default=None, description='Off25', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off26: int | None = Field(default=None, description='Off26', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off27: int | None = Field(default=None, description='Off27', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off28: int | None = Field(default=None, description='Off28', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off29: int | None = Field(default=None, description='Off29', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off30: int | None = Field(default=None, description='Off30', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off31: int | None = Field(default=None, description='Off31', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off32: int | None = Field(default=None, description='Off32', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off33: int | None = Field(default=None, description='Off33', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off34: int | None = Field(default=None, description='Off34', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off35: int | None = Field(default=None, description='Off35', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off36: int | None = Field(default=None, description='Off36', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off37: int | None = Field(default=None, description='Off37', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off38: int | None = Field(default=None, description='Off38', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off39: int | None = Field(default=None, description='Off39', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off40: int | None = Field(default=None, description='Off40', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off41: int | None = Field(default=None, description='Off41', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off42: int | None = Field(default=None, description='Off42', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off43: int | None = Field(default=None, description='Off43', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off44: int | None = Field(default=None, description='Off44', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off45: int | None = Field(default=None, description='Off45', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off46: int | None = Field(default=None, description='Off46', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off47: int | None = Field(default=None, description='Off47', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off48: int | None = Field(default=None, description='Off48', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off49: int | None = Field(default=None, description='Off49', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Off50: int | None = Field(default=None, description='Off50', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M'})
    Ts: int | None = Field(default=None, description='Timestamp value is the number of seconds since January 1, 2000', json_schema_extra={'type': 'uint32', 'size': 2, 'access': 'RW', 'mandatory': 'M', 'label': 'Timestamp'})
    Ms: int | None = Field(default=None, description='Millisecond counter 0-999', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Milliseconds'})
    Seq: int | None = Field(default=None, description='Sequence number of request', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Sequence'})
    Role: int | None = Field(default=None, description='Digital Signature ID', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Role'})
    Alg: Model_3Alg | int | None = Field(default=None, description='Algorithm used to compute the digital signature', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Algorithm'})
    N: int | None = Field(default=None, description='Number of registers comprising the digital signature.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'N'})
    repeating: list[Model_3Repeating] = Field(default_factory=list, description='repeating', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
