"""SunSpec model 806: Flow Battery Model

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Flow_battery',
    'Flow_batteryBattery_string',
]


class Flow_batteryBattery_string(SunSpecGroup):
    """battery_string"""

    GROUP_NAME: ClassVar[str] = 'battery_string'

    BatStTBD: int | None = Field(default=None, description='Battery String Points To Be Determined', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Battery String Points To Be Determined'})


@register_model
class Flow_battery(SunSpecModel):
    """Flow Battery Model"""

    GROUP_NAME: ClassVar[str] = 'flow_battery'
    MODEL_ID: ClassVar[int] = 806
    MODEL_LABEL: ClassVar[str] = 'Flow Battery Model'

    ID: int | None = Field(default=806, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 806})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    BatTBD: int | None = Field(default=None, description='Battery Points To Be Determined', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Battery Points To Be Determined'})
    battery_string: list[Flow_batteryBattery_string] = Field(default_factory=list, description='battery_string', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
