"""SunSpec model 307: Base Met

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Base_met',
]


@register_model
class Base_met(SunSpecModel):
    """Base Meteorological Model"""

    GROUP_NAME: ClassVar[str] = 'base_met'
    MODEL_ID: ClassVar[int] = 307
    MODEL_LABEL: ClassVar[str] = 'Base Met'

    ID: int | None = Field(default=307, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 307})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    TmpAmb: int | None = Field(default=None, description='Ambient Temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': -1, 'label': 'Ambient Temperature'})
    RH: int | None = Field(default=None, description='Relative Humidity', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'label': 'Relative Humidity'})
    Pres: int | None = Field(default=None, description='Barometric Pressure', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'HPa', 'label': 'Barometric Pressure'})
    WndSpd: int | None = Field(default=None, description='Wind Speed', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'mps', 'label': 'Wind Speed'})
    WndDir: int | None = Field(default=None, description='Wind Direction', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'deg', 'label': 'Wind Direction'})
    Rain: int | None = Field(default=None, description='Rainfall', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'mm', 'label': 'Rainfall'})
    Snw: int | None = Field(default=None, description='Snow Depth', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'mm', 'label': 'Snow Depth'})
    PPT: int | None = Field(default=None, description='Precipitation Type (WMO 4680 SYNOP code reference)', json_schema_extra={'type': 'int16', 'size': 1, 'label': 'Precipitation Type'})
    ElecFld: int | None = Field(default=None, description='Electric Field', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Vm', 'label': 'Electric Field'})
    SurWet: int | None = Field(default=None, description='Surface Wetness', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'kO', 'label': 'Surface Wetness'})
    SoilWet: int | None = Field(default=None, description='Soil Wetness', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'label': 'Soil Wetness'})
