"""SunSpec model 64413: PV Curves

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'PVSimCurves',
    'PVSimCurvesIV',
]


class PVSimCurvesIV(SunSpecGroup):
    """IV"""

    GROUP_NAME: ClassVar[str] = 'IV'

    P: float | None = Field(default=None, description='Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'W', 'label': 'Power'})
    I: float | None = Field(default=None, description='Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'label': 'Current'})
    V: float | None = Field(default=None, description='Voltage', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Voltage'})


@register_model
class PVSimCurves(SunSpecModel):
    """Current-Voltage and Power-Voltage Profiles for PV Simulation."""

    GROUP_NAME: ClassVar[str] = 'PVSimCurves'
    MODEL_ID: ClassVar[int] = 64413
    MODEL_LABEL: ClassVar[str] = 'PV Curves'

    ID: int | None = Field(default=64413, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 64413})
    L: int | None = Field(default=None, description='Model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    IVLen: int | None = Field(default=None, description='Number of points in the IV curve.', json_schema_extra={'type': 'count', 'size': 1, 'static': 'D', 'label': 'IV length'})
    Irr: int | None = Field(default=None, description='Plane of Array Irradiance', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W/m^2', 'sf': 'Irr_SF', 'static': 'S', 'label': 'POA Irradiance'})
    Irr_SF: int | None = Field(default=None, description='Irr_SF', json_schema_extra={'type': 'sunssf', 'size': 1})
    IV: list[PVSimCurvesIV] = Field(default_factory=list, description='IV', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'IVLen'})
