"""SunSpec model 64001: Veris Status and Configuration

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_64001',
]


@register_model
class Model_64001(SunSpecModel):
    """Veris Status and Configuration"""

    GROUP_NAME: ClassVar[str] = 'model_64001'
    MODEL_ID: ClassVar[int] = 64001
    MODEL_LABEL: ClassVar[str] = 'Veris Status and Configuration'

    ID: int | None = Field(default=64001, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 64001})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Cmd: int | None = Field(default=None, description='Command Code', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Command Code'})
    HWRev: int | None = Field(default=None, description='Hardware Revision', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Hardware Revision'})
    RSFWRev: int | None = Field(default=None, description='RS FW Revision', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'RS FW Revision'})
    OSFWRev: int | None = Field(default=None, description='OS FW Revision', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'OS FW Revision'})
    ProdRev: str | None = Field(default=None, description='Product Revision', json_schema_extra={'type': 'string', 'size': 2, 'label': 'Product Revision'})
    Boots: int | None = Field(default=None, description='Boot Count', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Boot Count'})
    Switch: int | None = Field(default=None, description='DIP Switches', json_schema_extra={'type': 'bitfield16', 'size': 1, 'label': 'DIP Switches'})
    Sensors: int | None = Field(default=None, description='Num Detected Sensors', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Num Detected Sensors'})
    Talking: int | None = Field(default=None, description='Num Communicating Sensors', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Num Communicating Sensors'})
    Status: int | None = Field(default=None, description='System Status', json_schema_extra={'type': 'bitfield16', 'size': 1, 'label': 'System Status'})
    Config: int | None = Field(default=None, description='System Configuration', json_schema_extra={'type': 'bitfield16', 'size': 1, 'label': 'System Configuration'})
    LEDblink: int | None = Field(default=None, description='LED Blink Threshold', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'label': 'LED Blink Threshold'})
    LEDon: int | None = Field(default=None, description='LED On Threshold', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'label': 'LED On Threshold'})
    Reserved: int | None = Field(default=None, description='Reserved', json_schema_extra={'type': 'uint16', 'size': 1})
    Loc: str | None = Field(default=None, description='Location String', json_schema_extra={'type': 'string', 'size': 16, 'label': 'Location String'})
    S1ID: int | None = Field(default=None, description='Sensor 1 Unit ID', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Sensor 1 Unit ID'})
    S1Addr: int | None = Field(default=None, description='Sensor 1 Address', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 1 Address'})
    S1OSVer: int | None = Field(default=None, description='Sensor 1 OS Version', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 1 OS Version'})
    S1Ver: str | None = Field(default=None, description='Sensor 1 Product Version', json_schema_extra={'type': 'string', 'size': 2, 'label': 'Sensor 1 Product Version'})
    S1Serial: str | None = Field(default=None, description='Sensor 1 Serial Num', json_schema_extra={'type': 'string', 'size': 5, 'label': 'Sensor 1 Serial Num'})
    S2ID: int | None = Field(default=None, description='Sensor 2 Unit ID', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Sensor 2 Unit ID'})
    S2Addr: int | None = Field(default=None, description='Sensor 2 Address', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 2 Address'})
    S2OSVer: int | None = Field(default=None, description='Sensor 2 OS Version', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 2 OS Version'})
    S2Ver: str | None = Field(default=None, description='Sensor 2 Product Version', json_schema_extra={'type': 'string', 'size': 2, 'label': 'Sensor 2 Product Version'})
    S2Serial: str | None = Field(default=None, description='Sensor 2 Serial Num', json_schema_extra={'type': 'string', 'size': 5, 'label': 'Sensor 2 Serial Num'})
    S3ID: int | None = Field(default=None, description='Sensor 3 Unit ID', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Sensor 3 Unit ID'})
    S3Addr: int | None = Field(default=None, description='Sensor 3 Address', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 3 Address'})
    S3OSVer: int | None = Field(default=None, description='Sensor 3 OS Version', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 3 OS Version'})
    S3Ver: str | None = Field(default=None, description='Sensor 3 Product Version', json_schema_extra={'type': 'string', 'size': 2, 'label': 'Sensor 3 Product Version'})
    S3Serial: str | None = Field(default=None, description='Sensor 3 Serial Num', json_schema_extra={'type': 'string', 'size': 5, 'label': 'Sensor 3 Serial Num'})
    S4ID: int | None = Field(default=None, description='Sensor 4 Unit ID', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Sensor 4 Unit ID'})
    S4Addr: int | None = Field(default=None, description='Sensor 4 Address', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 4 Address'})
    S4OSVer: int | None = Field(default=None, description='Sensor 4 OS Version', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Sensor 4 OS Version'})
    S4Ver: str | None = Field(default=None, description='Sensor 4 Product Version', json_schema_extra={'type': 'string', 'size': 2, 'label': 'Sensor 4 Product Version'})
    S4Serial: str | None = Field(default=None, description='Sensor 4 Serial Num', json_schema_extra={'type': 'string', 'size': 5, 'label': 'Sensor 4 Serial Num'})
