"""SunSpec model 63001: SunSpec Test Model 1

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_63001',
    'Model_63001Repeating',
]


class Model_63001Repeating(SunSpecGroup):
    """repeating"""

    GROUP_NAME: ClassVar[str] = 'repeating'

    sunssf_8: int | None = Field(default=None, description='sunssf_8', json_schema_extra={'type': 'sunssf', 'size': 1})
    int16_11: int | None = Field(default=None, description='int16_11', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_8', 'access': 'RW'})
    int16_12: int | None = Field(default=None, description='int16_12', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_9'})
    int16_u: int | None = Field(default=None, description='int16_u', json_schema_extra={'type': 'int16', 'size': 1})
    uint16_11: int | None = Field(default=None, description='uint16_11', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_8', 'access': 'RW'})
    uint16_12: int | None = Field(default=None, description='uint16_12', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_9'})
    uint16_13: int | None = Field(default=None, description='uint16_13', json_schema_extra={'type': 'uint16', 'size': 1})
    uint16_u: int | None = Field(default=None, description='uint16_u', json_schema_extra={'type': 'uint16', 'size': 1})
    int32: int | None = Field(default=None, description='int32', json_schema_extra={'type': 'int32', 'size': 2, 'sf': 'sunssf_1', 'access': 'RW'})
    int32_u: int | None = Field(default=None, description='int32_u', json_schema_extra={'type': 'int32', 'size': 2})
    uint32: int | None = Field(default=None, description='uint32', json_schema_extra={'type': 'uint32', 'size': 2, 'sf': 'sunssf_9', 'access': 'RW'})
    uint32_u: int | None = Field(default=None, description='uint32_u', json_schema_extra={'type': 'uint32', 'size': 2})
    sunssf_9: int | None = Field(default=None, description='sunssf_9', json_schema_extra={'type': 'sunssf', 'size': 1})
    pad_2: int | None = Field(default=None, description='pad_2', json_schema_extra={'type': 'pad', 'size': 1})


@register_model
class Model_63001(SunSpecModel):
    """SunSpec Test Model 1"""

    GROUP_NAME: ClassVar[str] = 'model_63001'
    MODEL_ID: ClassVar[int] = 63001
    MODEL_LABEL: ClassVar[str] = 'SunSpec Test Model 1'

    ID: int | None = Field(default=63001, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 63001})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    sunssf_1: int | None = Field(default=None, description='sunssf_1', json_schema_extra={'type': 'sunssf', 'size': 1})
    sunssf_2: int | None = Field(default=None, description='sunssf_2', json_schema_extra={'type': 'sunssf', 'size': 1})
    sunssf_3: int | None = Field(default=None, description='sunssf_3', json_schema_extra={'type': 'sunssf', 'size': 1})
    sunssf_4: int | None = Field(default=None, description='sunssf_4', json_schema_extra={'type': 'sunssf', 'size': 1})
    int16_1: int | None = Field(default=None, description='int16_1', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_1'})
    int16_2: int | None = Field(default=None, description='int16_2', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_2'})
    int16_3: int | None = Field(default=None, description='int16_3', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_3'})
    int16_4: int | None = Field(default=None, description='int16_4', json_schema_extra={'type': 'int16', 'size': 1, 'sf': 'sunssf_4', 'access': 'RW'})
    int16_5: int | None = Field(default=None, description='int16_5', json_schema_extra={'type': 'int16', 'size': 1})
    int16_u: int | None = Field(default=None, description='int16_u', json_schema_extra={'type': 'int16', 'size': 1})
    uint16_1: int | None = Field(default=None, description='uint16_1', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_1'})
    uint16_2: int | None = Field(default=None, description='uint16_2', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_2'})
    uint16_3: int | None = Field(default=None, description='uint16_3', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_3'})
    uint16_4: int | None = Field(default=None, description='uint16_4', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'sunssf_4', 'access': 'RW'})
    uint16_5: int | None = Field(default=None, description='uint16_5', json_schema_extra={'type': 'uint16', 'size': 1})
    uint16_u: int | None = Field(default=None, description='uint16_u', json_schema_extra={'type': 'uint16', 'size': 1})
    acc16: int | None = Field(default=None, description='acc16', json_schema_extra={'type': 'acc16', 'size': 1})
    acc16_u: int | None = Field(default=None, description='acc16_u', json_schema_extra={'type': 'acc16', 'size': 1})
    enum16: int | None = Field(default=None, description='enum16', json_schema_extra={'type': 'enum16', 'size': 1})
    enum16_u: int | None = Field(default=None, description='enum16_u', json_schema_extra={'type': 'enum16', 'size': 1})
    bitfield16: int | None = Field(default=None, description='bitfield16', json_schema_extra={'type': 'bitfield16', 'size': 1})
    bitfield16_u: int | None = Field(default=None, description='bitfield16_u', json_schema_extra={'type': 'bitfield16', 'size': 1})
    int32_1: int | None = Field(default=None, description='int32_1', json_schema_extra={'type': 'int32', 'size': 2, 'sf': 'sunssf_5'})
    int32_2: int | None = Field(default=None, description='int32_2', json_schema_extra={'type': 'int32', 'size': 2, 'sf': 'sunssf_6'})
    int32_3: int | None = Field(default=None, description='int32_3', json_schema_extra={'type': 'int32', 'size': 2, 'sf': 'sunssf_7', 'access': 'RW'})
    int32_4: int | None = Field(default=None, description='int32_4', json_schema_extra={'type': 'int32', 'size': 2})
    int32_5: int | None = Field(default=None, description='int32_5', json_schema_extra={'type': 'int32', 'size': 2})
    int32_u: int | None = Field(default=None, description='int32_u', json_schema_extra={'type': 'int32', 'size': 2})
    uint32_1: int | None = Field(default=None, description='uint32_1', json_schema_extra={'type': 'uint32', 'size': 2, 'sf': 'sunssf_5'})
    uint32_2: int | None = Field(default=None, description='uint32_2', json_schema_extra={'type': 'uint32', 'size': 2, 'sf': 'sunssf_6'})
    uint32_3: int | None = Field(default=None, description='uint32_3', json_schema_extra={'type': 'uint32', 'size': 2, 'sf': 'sunssf_7', 'access': 'RW'})
    uint32_4: int | None = Field(default=None, description='uint32_4', json_schema_extra={'type': 'uint32', 'size': 2, 'sf': 1})
    uint32_5: int | None = Field(default=None, description='uint32_5', json_schema_extra={'type': 'uint32', 'size': 2})
    uint32_u: int | None = Field(default=None, description='uint32_u', json_schema_extra={'type': 'uint32', 'size': 2})
    acc32: int | None = Field(default=None, description='acc32', json_schema_extra={'type': 'acc32', 'size': 2})
    acc32_u: int | None = Field(default=None, description='acc32_u', json_schema_extra={'type': 'acc32', 'size': 2})
    enum32: int | None = Field(default=None, description='enum32', json_schema_extra={'type': 'enum32', 'size': 2})
    enum32_u: int | None = Field(default=None, description='enum32_u', json_schema_extra={'type': 'enum32', 'size': 2})
    bitfield32: int | None = Field(default=None, description='bitfield32', json_schema_extra={'type': 'bitfield32', 'size': 2})
    bitfield32_u: int | None = Field(default=None, description='bitfield32_u', json_schema_extra={'type': 'bitfield32', 'size': 2})
    ipaddr: str | None = Field(default=None, description='ipaddr', json_schema_extra={'type': 'ipaddr', 'size': 2, 'access': 'RW'})
    ipaddr_u: str | None = Field(default=None, description='ipaddr_u', json_schema_extra={'type': 'ipaddr', 'size': 2})
    int64: int | None = Field(default=None, description='int64', json_schema_extra={'type': 'int64', 'size': 4, 'access': 'RW'})
    int64_u: int | None = Field(default=None, description='int64_u', json_schema_extra={'type': 'int64', 'size': 4})
    acc64: int | None = Field(default=None, description='acc64', json_schema_extra={'type': 'acc64', 'size': 4})
    acc64_u: int | None = Field(default=None, description='acc64_u', json_schema_extra={'type': 'acc64', 'size': 4})
    ipv6addr: str | None = Field(default=None, description='ipv6addr', json_schema_extra={'type': 'ipv6addr', 'size': 8})
    ipv6addr_u: str | None = Field(default=None, description='ipv6addr_u', json_schema_extra={'type': 'ipv6addr', 'size': 8})
    float32: float | None = Field(default=None, description='float32', json_schema_extra={'type': 'float32', 'size': 2, 'access': 'RW'})
    float32_u: float | None = Field(default=None, description='float32_u', json_schema_extra={'type': 'float32', 'size': 2})
    string: str | None = Field(default=None, description='string', json_schema_extra={'type': 'string', 'size': 16, 'access': 'RW'})
    string_u: str | None = Field(default=None, description='string_u', json_schema_extra={'type': 'string', 'size': 16})
    sunssf_5: int | None = Field(default=None, description='sunssf_5', json_schema_extra={'type': 'sunssf', 'size': 1})
    sunssf_6: int | None = Field(default=None, description='sunssf_6', json_schema_extra={'type': 'sunssf', 'size': 1})
    sunssf_7: int | None = Field(default=None, description='sunssf_7', json_schema_extra={'type': 'sunssf', 'size': 1})
    pad_1: int | None = Field(default=None, description='pad_1', json_schema_extra={'type': 'pad', 'size': 1})
    repeating: list[Model_63001Repeating] = Field(default_factory=list, description='repeating', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
