"""SunSpec model 801: Energy Storage Base Model (DEPRECATED)

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Storage',
]


@register_model
class Storage(SunSpecModel):
    """This model has been deprecated."""

    GROUP_NAME: ClassVar[str] = 'storage'
    MODEL_ID: ClassVar[int] = 801
    MODEL_LABEL: ClassVar[str] = 'Energy Storage Base Model (DEPRECATED)'

    ID: int | None = Field(default=801, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 801})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    DEPRECATED: int | None = Field(default=None, description='This model has been deprecated.', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Deprecated Model'})
