"""SunSpec model 19: PPP Link

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_19',
    'Model_19Auth',
    'Model_19Dup',
    'Model_19Flw',
    'Model_19Pty',
]


class Model_19Pty(SunSpecEnum):
    """Enumeration for point ``Model_19.Pty`` (enum16)."""
    NONE = 0
    ODD = 1
    EVEN = 2


class Model_19Dup(SunSpecEnum):
    """Enumeration for point ``Model_19.Dup`` (enum16)."""
    FULL = 0
    HALF = 1


class Model_19Flw(SunSpecEnum):
    """Enumeration for point ``Model_19.Flw`` (enum16)."""
    NONE = 0
    HW = 1
    XONXOFF = 2


class Model_19Auth(SunSpecEnum):
    """Enumeration for point ``Model_19.Auth`` (enum16)."""
    NONE = 0
    PAP = 1
    CHAP = 2


@register_model
class Model_19(SunSpecModel):
    """Include this model to configure a Point-to-Point Protocol link"""

    GROUP_NAME: ClassVar[str] = 'model_19'
    MODEL_ID: ClassVar[int] = 19
    MODEL_LABEL: ClassVar[str] = 'PPP Link'

    ID: int | None = Field(default=19, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 19})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Nam: str | None = Field(default=None, description='Interface name', json_schema_extra={'type': 'string', 'size': 4, 'access': 'RW', 'label': 'Name'})
    Rte: int | None = Field(default=None, description='Interface baud rate in bits per second', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'bps', 'access': 'RW', 'mandatory': 'M', 'label': 'Rate'})
    Bits: int | None = Field(default=None, description='Number of data bits per character', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Bits'})
    Pty: Model_19Pty | int | None = Field(default=None, description='Parity setting', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Parity'})
    Dup: Model_19Dup | int | None = Field(default=None, description='Duplex mode', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Duplex'})
    Flw: Model_19Flw | int | None = Field(default=None, description='Flow Control Method', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Flow Control'})
    Auth: Model_19Auth | int | None = Field(default=None, description='Authentication method', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Authentication'})
    UsrNam: str | None = Field(default=None, description='Username for authentication', json_schema_extra={'type': 'string', 'size': 12, 'label': 'Username'})
    Pw: str | None = Field(default=None, description='Password for authentication', json_schema_extra={'type': 'string', 'size': 6, 'label': 'Password'})
    Pad: int | None = Field(default=None, description='Pad', json_schema_extra={'type': 'pad', 'size': 1})
