"""SunSpec model 708: DER Trip HV

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERTripHV',
    'DERTripHVAdptCrvRslt',
    'DERTripHVCrv',
    'DERTripHVCrvMayTrip',
    'DERTripHVCrvMayTripPt',
    'DERTripHVCrvMomCess',
    'DERTripHVCrvMomCessPt',
    'DERTripHVCrvMustTrip',
    'DERTripHVCrvMustTripPt',
    'DERTripHVCrvReadOnly',
    'DERTripHVEna',
]


class DERTripHVCrvReadOnly(SunSpecEnum):
    """Enumeration for point ``DERTripHVCrv.ReadOnly`` (enum16)."""
    RW = 0    # Read-Write Access
    R = 1    # Read-Only Access


class DERTripHVEna(SunSpecEnum):
    """Enumeration for point ``DERTripHV.Ena`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERTripHVAdptCrvRslt(SunSpecEnum):
    """Enumeration for point ``DERTripHV.AdptCrvRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DERTripHVCrvMustTripPt(SunSpecGroup):
    """Must trip curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point', 'standards': ['IEEE 1547-2018']})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point', 'standards': ['IEEE 1547-2018']})


class DERTripHVCrvMustTrip(SunSpecGroup):
    """Stored must trip curve."""

    GROUP_NAME: ClassVar[str] = 'MustTrip'

    ActPt: int | None = Field(default=None, description='Number of active points in must trip curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points', 'standards': ['IEEE 1547-2018']})
    Pt: list[DERTripHVCrvMustTripPt] = Field(default_factory=list, description='Must trip curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripHVCrvMayTripPt(SunSpecGroup):
    """May trip curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point'})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point'})


class DERTripHVCrvMayTrip(SunSpecGroup):
    """Stored may trip curve."""

    GROUP_NAME: ClassVar[str] = 'MayTrip'

    ActPt: int | None = Field(default=None, description='Number of active points in may trip curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points'})
    Pt: list[DERTripHVCrvMayTripPt] = Field(default_factory=list, description='May trip curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripHVCrvMomCessPt(SunSpecGroup):
    """Momentary cessation curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point'})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point'})


class DERTripHVCrvMomCess(SunSpecGroup):
    """Stored momentary cessation curve."""

    GROUP_NAME: ClassVar[str] = 'MomCess'

    ActPt: int | None = Field(default=None, description='Number of active points in the momentary cessation curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points'})
    Pt: list[DERTripHVCrvMomCessPt] = Field(default_factory=list, description='Momentary cessation curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripHVCrv(SunSpecGroup):
    """Stored curve sets."""

    GROUP_NAME: ClassVar[str] = 'Crv'

    ReadOnly: DERTripHVCrvReadOnly | int | None = Field(default=None, description='Curve read-write access.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Curve Access', 'standards': ['IEEE 1547-2018']})
    MustTrip: DERTripHVCrvMustTrip | None = Field(default=None, description='Stored must trip curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})
    MayTrip: DERTripHVCrvMayTrip | None = Field(default=None, description='Stored may trip curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})
    MomCess: DERTripHVCrvMomCess | None = Field(default=None, description='Stored momentary cessation curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})


@register_model
class DERTripHV(SunSpecModel):
    """DER high voltage trip model."""

    GROUP_NAME: ClassVar[str] = 'DERTripHV'
    MODEL_ID: ClassVar[int] = 708
    MODEL_LABEL: ClassVar[str] = 'DER Trip HV'

    ID: int | None = Field(default=708, description='DER high voltage trip model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 708})
    L: int | None = Field(default=None, description='DER high voltage trip model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Ena: DERTripHVEna | int | None = Field(default=None, description='DER high voltage trip control enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DER Trip HV Module Enable', 'standards': ['IEEE 1547-2018']})
    AdptCrvReq: int | None = Field(default=None, description='Index of curve points to adopt. First curve index is 1.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Adopt Curve Request', 'standards': ['IEEE 1547-2018']})
    AdptCrvRslt: DERTripHVAdptCrvRslt | int | None = Field(default=None, description='Result of last adopt curve operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Adopt Curve Result', 'standards': ['IEEE 1547-2018']})
    NPt: int | None = Field(default=None, description='Number of curve points supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Number Of Points', 'standards': ['IEEE 1547-2018']})
    NCrvSet: int | None = Field(default=None, description='Number of stored curves supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Curve Count', 'standards': ['IEEE 1547-2018']})
    V_SF: int | None = Field(default=None, description='Scale factor for curve voltage points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Scale Factor', 'standards': ['IEEE 1547-2018']})
    Tms_SF: int | None = Field(default=None, description='Scale factor for curve time points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Time Point Scale Factor', 'standards': ['IEEE 1547-2018']})
    Crv: list[DERTripHVCrv] = Field(default_factory=list, description='Stored curve sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NCrvSet'})
