"""SunSpec model 713: DER Storage Capacity

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERStorageCapacity',
    'DERStorageCapacitySta',
]


class DERStorageCapacitySta(SunSpecEnum):
    """Enumeration for point ``DERStorageCapacity.Sta`` (enum16)."""
    OK = 0
    WARNING = 1    # Warning
    ERROR = 2    # Error


@register_model
class DERStorageCapacity(SunSpecModel):
    """DER storage capacity."""

    GROUP_NAME: ClassVar[str] = 'DERStorageCapacity'
    MODEL_ID: ClassVar[int] = 713
    MODEL_LABEL: ClassVar[str] = 'DER Storage Capacity'

    ID: int | None = Field(default=713, description='DER storage capacity model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 713})
    L: int | None = Field(default=None, description='DER storage capacity model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    WHRtg: int | None = Field(default=None, description='Energy rating of the DER storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'WH', 'sf': 'WH_SF', 'label': 'Energy Rating'})
    WHAvail: int | None = Field(default=None, description='Energy available of the DER storage (WHAvail = WHRtg * SoC * SoH)', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'WH', 'sf': 'WH_SF', 'label': 'Energy Available'})
    SoC: int | None = Field(default=None, description='State of charge of the DER storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'sf': 'Pct_SF', 'label': 'State of Charge', 'standards': ['IEEE 1547-2018']})
    SoH: int | None = Field(default=None, description='State of health of the DER storage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'sf': 'Pct_SF', 'label': 'State of Health'})
    Sta: DERStorageCapacitySta | int | None = Field(default=None, description='Storage status.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Status'})
    WH_SF: int | None = Field(default=None, description='Scale factor for energy capacity.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Energy Scale Factor'})
    Pct_SF: int | None = Field(default=None, description='Scale factor for percentage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Percent Scale Factor'})
