"""SunSpec model 707: DER Trip LV

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERTripLV',
    'DERTripLVAdptCrvRslt',
    'DERTripLVCrv',
    'DERTripLVCrvMayTrip',
    'DERTripLVCrvMayTripPt',
    'DERTripLVCrvMomCess',
    'DERTripLVCrvMomCessPt',
    'DERTripLVCrvMustTrip',
    'DERTripLVCrvMustTripPt',
    'DERTripLVCrvReadOnly',
    'DERTripLVEna',
]


class DERTripLVCrvReadOnly(SunSpecEnum):
    """Enumeration for point ``DERTripLVCrv.ReadOnly`` (enum16)."""
    RW = 0    # Read-Write Access
    R = 1    # Read-Only Access


class DERTripLVEna(SunSpecEnum):
    """Enumeration for point ``DERTripLV.Ena`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERTripLVAdptCrvRslt(SunSpecEnum):
    """Enumeration for point ``DERTripLV.AdptCrvRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DERTripLVCrvMustTripPt(SunSpecGroup):
    """Must trip curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point', 'standards': ['IEEE 1547-2018']})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point', 'standards': ['IEEE 1547-2018']})


class DERTripLVCrvMustTrip(SunSpecGroup):
    """Stored must trip curve."""

    GROUP_NAME: ClassVar[str] = 'MustTrip'

    ActPt: int | None = Field(default=None, description='Number of active points in must trip curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points', 'standards': ['IEEE 1547-2018']})
    Pt: list[DERTripLVCrvMustTripPt] = Field(default_factory=list, description='Must trip curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripLVCrvMayTripPt(SunSpecGroup):
    """May trip curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point'})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point'})


class DERTripLVCrvMayTrip(SunSpecGroup):
    """Stored may trip curve."""

    GROUP_NAME: ClassVar[str] = 'MayTrip'

    ActPt: int | None = Field(default=None, description='Number of active points in may trip curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points'})
    Pt: list[DERTripLVCrvMayTripPt] = Field(default_factory=list, description='May trip curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripLVCrvMomCessPt(SunSpecGroup):
    """Momentary cessation curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point'})
    Tms: int | None = Field(default=None, description='Curve time point in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Time Point'})


class DERTripLVCrvMomCess(SunSpecGroup):
    """Stored momentary cessation curve."""

    GROUP_NAME: ClassVar[str] = 'MomCess'

    ActPt: int | None = Field(default=None, description='Number of active points in the momentary cessation curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Number Of Active Points'})
    Pt: list[DERTripLVCrvMomCessPt] = Field(default_factory=list, description='Momentary cessation curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


class DERTripLVCrv(SunSpecGroup):
    """Stored curve sets."""

    GROUP_NAME: ClassVar[str] = 'Crv'

    ReadOnly: DERTripLVCrvReadOnly | int | None = Field(default=None, description='Curve read-write access.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Curve Access', 'standards': ['IEEE 1547-2018']})
    MustTrip: DERTripLVCrvMustTrip | None = Field(default=None, description='Stored must trip curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})
    MayTrip: DERTripLVCrvMayTrip | None = Field(default=None, description='Stored may trip curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})
    MomCess: DERTripLVCrvMomCess | None = Field(default=None, description='Stored momentary cessation curve.', json_schema_extra={'type': 'group', 'group_type': 'group'})


@register_model
class DERTripLV(SunSpecModel):
    """DER low voltage trip model."""

    GROUP_NAME: ClassVar[str] = 'DERTripLV'
    MODEL_ID: ClassVar[int] = 707
    MODEL_LABEL: ClassVar[str] = 'DER Trip LV'

    ID: int | None = Field(default=707, description='DER low voltage trip model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 707})
    L: int | None = Field(default=None, description='DER low voltage trip model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Ena: DERTripLVEna | int | None = Field(default=None, description='DER low voltage trip control enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DER Trip LV Module Enable', 'standards': ['IEEE 1547-2018']})
    AdptCrvReq: int | None = Field(default=None, description='Index of curve points to adopt. First curve index is 1.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Adopt Curve Request', 'standards': ['IEEE 1547-2018']})
    AdptCrvRslt: DERTripLVAdptCrvRslt | int | None = Field(default=None, description='Result of last adopt curve operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Adopt Curve Result', 'standards': ['IEEE 1547-2018']})
    NPt: int | None = Field(default=None, description='Number of curve points supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Number Of Points', 'standards': ['IEEE 1547-2018']})
    NCrvSet: int | None = Field(default=None, description='Number of stored curves supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Curve Count', 'standards': ['IEEE 1547-2018']})
    V_SF: int | None = Field(default=None, description='Scale factor for curve voltage points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Scale Factor', 'standards': ['IEEE 1547-2018']})
    Tms_SF: int | None = Field(default=None, description='Scale factor for curve time points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Time Point Scale Factor', 'standards': ['IEEE 1547-2018']})
    Crv: list[DERTripLVCrv] = Field(default_factory=list, description='Stored curve sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NCrvSet'})
