"""SunSpec model 706: DER Volt-Watt

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERVoltWatt',
    'DERVoltWattAdptCrvRslt',
    'DERVoltWattCrv',
    'DERVoltWattCrvDeptRef',
    'DERVoltWattCrvPt',
    'DERVoltWattCrvReadOnly',
    'DERVoltWattEna',
]


class DERVoltWattCrvDeptRef(SunSpecEnum):
    """Enumeration for point ``DERVoltWattCrv.DeptRef`` (enum16)."""
    W_MAX_PCT = 0
    W_AVAL_PCT = 1


class DERVoltWattCrvReadOnly(SunSpecEnum):
    """Enumeration for point ``DERVoltWattCrv.ReadOnly`` (enum16)."""
    RW = 0    # Read-Write Access
    R = 1    # Read-Only Access


class DERVoltWattEna(SunSpecEnum):
    """Enumeration for point ``DERVoltWatt.Ena`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERVoltWattAdptCrvRslt(SunSpecEnum):
    """Enumeration for point ``DERVoltWatt.AdptCrvRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DERVoltWattCrvPt(SunSpecGroup):
    """Stored curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point', 'standards': ['IEEE 1547-2018']})
    W: int | None = Field(default=None, description='Active power in percent of rated active power.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'DeptRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'Dependent Reference', 'standards': ['IEEE 1547-2018']})


class DERVoltWattCrv(SunSpecGroup):
    """Stored curve sets."""

    GROUP_NAME: ClassVar[str] = 'Crv'

    ActPt: int | None = Field(default=None, description='Number of active points.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Active Points', 'standards': ['IEEE 1547-2018']})
    DeptRef: DERVoltWattCrvDeptRef | int | None = Field(default=None, description='Curve dependent reference.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Dependent Reference', 'standards': ['IEEE 1547-2018']})
    RspTms: int | None = Field(default=None, description='Open loop response time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'RspTms_SF', 'access': 'RW', 'label': 'Open Loop Response Time', 'standards': ['IEEE 1547-2018']})
    ReadOnly: DERVoltWattCrvReadOnly | int | None = Field(default=None, description='Curve read-write access.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Curve Access', 'standards': ['IEEE 1547-2018']})
    Pt: list[DERVoltWattCrvPt] = Field(default_factory=list, description='Stored curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


@register_model
class DERVoltWatt(SunSpecModel):
    """DER Volt-Watt model."""

    GROUP_NAME: ClassVar[str] = 'DERVoltWatt'
    MODEL_ID: ClassVar[int] = 706
    MODEL_LABEL: ClassVar[str] = 'DER Volt-Watt'

    ID: int | None = Field(default=706, description='DER Volt-Watt model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 706})
    L: int | None = Field(default=None, description='DER Volt-Watt model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Ena: DERVoltWattEna | int | None = Field(default=None, description='Volt-Watt control enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DER Volt-Watt Module Enable', 'standards': ['IEEE 1547-2018']})
    AdptCrvReq: int | None = Field(default=None, description='Index of curve points to adopt. First curve index is 1.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Adopt Curve Request', 'standards': ['IEEE 1547-2018']})
    AdptCrvRslt: DERVoltWattAdptCrvRslt | int | None = Field(default=None, description='Result of last adopt curve operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Adopt Curve Result', 'standards': ['IEEE 1547-2018']})
    NPt: int | None = Field(default=None, description='Number of curve points supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Number Of Points', 'standards': ['IEEE 1547-2018']})
    NCrv: int | None = Field(default=None, description='Number of stored curves supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Curve Count', 'standards': ['IEEE 1547-2018']})
    RvrtTms: int | None = Field(default=None, description='Reversion time in seconds. 0 = No reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Reversion Timeout'})
    RvrtRem: int | None = Field(default=None, description='Reversion time remaining in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Reversion Time Remaining'})
    RvrtCrv: int | None = Field(default=None, description='Default curve after reversion timeout.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Reversion Curve'})
    V_SF: int | None = Field(default=None, description='Scale factor for curve voltage points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Scale Factor', 'standards': ['IEEE 1547-2018']})
    DeptRef_SF: int | None = Field(default=None, description='Scale factor for curve watt points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Watt Scale Factor', 'standards': ['IEEE 1547-2018']})
    RspTms_SF: int | None = Field(default=None, description='Open loop response time scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Open-Loop Scale Factor', 'standards': ['IEEE 1547-2018']})
    Crv: list[DERVoltWattCrv] = Field(default_factory=list, description='Stored curve sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NCrv'})
