"""SunSpec model 128: Dynamic Reactive Current

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Reactive_current',
    'Reactive_currentArGraMod',
    'Reactive_currentModEna',
]


class Reactive_currentArGraMod(SunSpecEnum):
    """Enumeration for point ``Reactive_current.ArGraMod`` (enum16)."""
    EDGE = 0
    CENTER = 1


class Reactive_currentModEna(SunSpecFlags):
    """Bitfield for point ``Reactive_current.ModEna`` (bitfield16)."""
    ENABLED = 1


@register_model
class Reactive_current(SunSpecModel):
    """Dynamic Reactive Current"""

    GROUP_NAME: ClassVar[str] = 'reactive_current'
    MODEL_ID: ClassVar[int] = 128
    MODEL_LABEL: ClassVar[str] = 'Dynamic Reactive Current'

    ID: int | None = Field(default=128, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 128})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    ArGraMod: Reactive_currentArGraMod | int | None = Field(default=None, description='Indicates if gradients trend toward zero at the edges of the deadband or trend toward zero at the center of the deadband.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ArGraMod'})
    ArGraSag: int | None = Field(default=None, description='The gradient used to increase capacitive dynamic current. A value of 0 indicates no additional reactive current support.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%ARtg/%dV', 'sf': 'ArGra_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'ArGraSag'})
    ArGraSwell: int | None = Field(default=None, description='The gradient used to increase inductive dynamic current. A value of 0 indicates no additional reactive current support.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%ARtg/%dV', 'sf': 'ArGra_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'ArGraSwell'})
    ModEna: Reactive_currentModEna | int | None = Field(default=None, description='Activate dynamic reactive current model', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    FilTms: int | None = Field(default=None, description='The time window used to calculate the moving average voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'FilTms'})
    DbVMin: int | None = Field(default=None, description='The lower delta voltage limit for which negative voltage deviations less than this value no dynamic vars are produced.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'VRefPct_SF', 'access': 'RW', 'label': 'DbVMin'})
    DbVMax: int | None = Field(default=None, description='The upper delta voltage limit for which positive voltage deviations less than this value no dynamic current produced.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'VRefPct_SF', 'access': 'RW', 'label': 'DbVMax'})
    BlkZnV: int | None = Field(default=None, description='Block zone voltage which defines a lower voltage boundary below which no dynamic current is produced.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'VRefPct_SF', 'access': 'RW', 'label': 'BlkZnV'})
    HysBlkZnV: int | None = Field(default=None, description='Hysteresis voltage used with BlkZnV.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'VRefPct_SF', 'access': 'RW', 'label': 'HysBlkZnV'})
    BlkZnTmms: int | None = Field(default=None, description='Block zone time the time before which reactive current support remains active regardless of how low the voltage drops.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'mSecs', 'access': 'RW', 'label': 'BlkZnTmms'})
    HoldTmms: int | None = Field(default=None, description='Hold time during which reactive current support continues after the average voltage has entered the dead zone.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'mSecs', 'access': 'RW', 'label': 'HoldTmms'})
    ArGra_SF: int | None = Field(default=None, description='Scale factor for the gradients.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'ArGra_SF'})
    VRefPct_SF: int | None = Field(default=None, description='Scale factor for the voltage zone and limit settings.', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'VRefPct_SF'})
    Pad: int | None = Field(default=None, description='Pad', json_schema_extra={'type': 'pad', 'size': 1})
