"""SunSpec model 113: Inverter (Three Phase) FLOAT

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Inverter_three_phase_float',
    'Inverter_three_phase_floatEvt1',
    'Inverter_three_phase_floatSt',
]


class Inverter_three_phase_floatSt(SunSpecEnum):
    """Enumeration for point ``Inverter_three_phase_float.St`` (enum16)."""
    OFF = 1
    SLEEPING = 2
    STARTING = 3
    MPPT = 4
    THROTTLED = 5
    SHUTTING_DOWN = 6
    FAULT = 7
    STANDBY = 8


class Inverter_three_phase_floatEvt1(SunSpecFlags):
    """Bitfield for point ``Inverter_three_phase_float.Evt1`` (bitfield32)."""
    GROUND_FAULT = 1
    DC_OVER_VOLT = 2
    AC_DISCONNECT = 4
    DC_DISCONNECT = 8
    GRID_DISCONNECT = 16
    CABINET_OPEN = 32
    MANUAL_SHUTDOWN = 64
    OVER_TEMP = 128
    OVER_FREQUENCY = 256
    UNDER_FREQUENCY = 512
    AC_OVER_VOLT = 1024
    AC_UNDER_VOLT = 2048
    BLOWN_STRING_FUSE = 4096
    UNDER_TEMP = 8192
    MEMORY_LOSS = 16384
    HW_TEST_FAILURE = 32768


@register_model
class Inverter_three_phase_float(SunSpecModel):
    """Include this model for three phase inverter monitoring using float values"""

    GROUP_NAME: ClassVar[str] = 'inverter_three_phase_float'
    MODEL_ID: ClassVar[int] = 113
    MODEL_LABEL: ClassVar[str] = 'Inverter (Three Phase) FLOAT'

    ID: int | None = Field(default=113, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 113})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    A: float | None = Field(default=None, description='AC Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'mandatory': 'M', 'label': 'Amps'})
    AphA: float | None = Field(default=None, description='Phase A Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'mandatory': 'M', 'label': 'Amps PhaseA'})
    AphB: float | None = Field(default=None, description='Phase B Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'mandatory': 'M', 'label': 'Amps PhaseB'})
    AphC: float | None = Field(default=None, description='Phase C Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'mandatory': 'M', 'label': 'Amps PhaseC'})
    PPVphAB: float | None = Field(default=None, description='Phase Voltage AB', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Phase Voltage AB'})
    PPVphBC: float | None = Field(default=None, description='Phase Voltage BC', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Phase Voltage BC'})
    PPVphCA: float | None = Field(default=None, description='Phase Voltage CA', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'Phase Voltage CA'})
    PhVphA: float | None = Field(default=None, description='Phase Voltage AN', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'mandatory': 'M', 'label': 'Phase Voltage AN'})
    PhVphB: float | None = Field(default=None, description='Phase Voltage BN', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'mandatory': 'M', 'label': 'Phase Voltage BN'})
    PhVphC: float | None = Field(default=None, description='Phase Voltage CN', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'mandatory': 'M', 'label': 'Phase Voltage CN'})
    W: float | None = Field(default=None, description='AC Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'W', 'mandatory': 'M', 'label': 'Watts'})
    Hz: float | None = Field(default=None, description='Line Frequency', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'Hz', 'mandatory': 'M', 'label': 'Hz'})
    VA: float | None = Field(default=None, description='AC Apparent Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'VA', 'label': 'VA'})
    VAr: float | None = Field(default=None, description='AC Reactive Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'var', 'label': 'VAr'})
    PF: float | None = Field(default=None, description='AC Power Factor', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'Pct', 'label': 'PF'})
    WH: float | None = Field(default=None, description='AC Energy', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'Wh', 'mandatory': 'M', 'label': 'WattHours'})
    DCA: float | None = Field(default=None, description='DC Current', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'A', 'label': 'DC Amps'})
    DCV: float | None = Field(default=None, description='DC Voltage', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'V', 'label': 'DC Voltage'})
    DCW: float | None = Field(default=None, description='DC Power', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'W', 'label': 'DC Watts'})
    TmpCab: float | None = Field(default=None, description='Cabinet Temperature', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'C', 'mandatory': 'M', 'label': 'Cabinet Temperature'})
    TmpSnk: float | None = Field(default=None, description='Heat Sink Temperature', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'C', 'label': 'Heat Sink Temperature'})
    TmpTrns: float | None = Field(default=None, description='Transformer Temperature', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'C', 'label': 'Transformer Temperature'})
    TmpOt: float | None = Field(default=None, description='Other Temperature', json_schema_extra={'type': 'float32', 'size': 2, 'units': 'C', 'label': 'Other Temperature'})
    St: Inverter_three_phase_floatSt | int | None = Field(default=None, description='Operating state', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Operating State'})
    StVnd: int | None = Field(default=None, description='Vendor specific operating state code', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Vendor Operating State'})
    Evt1: Inverter_three_phase_floatEvt1 | int | None = Field(default=None, description='Event fields', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Event1'})
    Evt2: int | None = Field(default=None, description='Reserved for future use', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Event Bitfield 2'})
    EvtVnd1: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event Bitfield 1'})
    EvtVnd2: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event Bitfield 2'})
    EvtVnd3: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event Bitfield 3'})
    EvtVnd4: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event Bitfield 4'})
