"""SunSpec model 10: Communication Interface Header

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_10',
    'Model_10St',
    'Model_10Typ',
]


class Model_10St(SunSpecEnum):
    """Enumeration for point ``Model_10.St`` (enum16)."""
    DOWN = 0
    UP = 1
    FAULT = 2


class Model_10Typ(SunSpecEnum):
    """Enumeration for point ``Model_10.Typ`` (enum16)."""
    UNKNOWN = 0
    INTERNAL = 1
    TWISTED_PAIR = 2
    FIBER = 3
    WIRELESS = 4


@register_model
class Model_10(SunSpecModel):
    """To be included first for a complete interface description"""

    GROUP_NAME: ClassVar[str] = 'model_10'
    MODEL_ID: ClassVar[int] = 10
    MODEL_LABEL: ClassVar[str] = 'Communication Interface Header'

    ID: int | None = Field(default=10, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 10})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    St: Model_10St | int | None = Field(default=None, description='Overall interface status', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Interface Status'})
    Ctl: int | None = Field(default=None, description='Overall interface control (TBD)', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Interface Control'})
    Typ: Model_10Typ | int | None = Field(default=None, description='Type of physical media', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Physical Access Type'})
    Pad: int | None = Field(default=None, description='Pad', json_schema_extra={'type': 'pad', 'size': 1})
