"""SunSpec model 402: String Combiner (Advanced)

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'String_combiner_advanced',
    'String_combiner_advancedEvt',
    'String_combiner_advancedString',
    'String_combiner_advancedStringInEvt',
]


class String_combiner_advancedStringInEvt(SunSpecFlags):
    """Bitfield for point ``String_combiner_advancedString.InEvt`` (bitfield32)."""
    LOW_VOLTAGE = 1
    LOW_POWER = 2
    LOW_EFFICIENCY = 4
    CURRENT = 8
    VOLTAGE = 16
    POWER = 32
    PR = 64
    DISCONNECTED = 128
    FUSE_FAULT = 256
    COMBINER_FUSE_FAULT = 512
    COMBINER_CABINET_OPEN = 1024
    TEMP = 2048
    GROUNDFAULT = 4096
    REVERSED_POLARITY = 8192
    INCOMPATIBLE = 16384
    COMM_ERROR = 32768
    INTERNAL_ERROR = 65536
    THEFT = 131072
    ARC_DETECTED = 262144


class String_combiner_advancedEvt(SunSpecFlags):
    """Bitfield for point ``String_combiner_advanced.Evt`` (bitfield32)."""
    LOW_VOLTAGE = 1
    LOW_POWER = 2
    LOW_EFFICIENCY = 4
    CURRENT = 8
    VOLTAGE = 16
    POWER = 32
    PR = 64
    DISCONNECTED = 128
    FUSE_FAULT = 256
    COMBINER_FUSE_FAULT = 512
    COMBINER_CABINET_OPEN = 1024
    TEMP = 2048
    GROUNDFAULT = 4096
    REVERSED_POLARITY = 8192
    INCOMPATIBLE = 16384
    COMM_ERROR = 32768
    INTERNAL_ERROR = 65536
    THEFT = 131072
    ARC_DETECTED = 262144


class String_combiner_advancedString(SunSpecGroup):
    """string"""

    GROUP_NAME: ClassVar[str] = 'string'

    InID: int | None = Field(default=None, description='Uniquely identifies this input set', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'ID'})
    InEvt: String_combiner_advancedStringInEvt | int | None = Field(default=None, description='String Input Event Flags', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Input Event'})
    EvtVnd: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event'})
    InDCA: int | None = Field(default=None, description='String Input Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'DCA_SF', 'mandatory': 'M', 'label': 'Amps'})
    InDCAhr: int | None = Field(default=None, description='String Input Amp-Hours', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Ah', 'sf': 'DCAhr_SF', 'label': 'Amp-hours'})
    InDCV: int | None = Field(default=None, description='String Input Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'DCV_SF', 'label': 'Voltage'})
    InDCW: int | None = Field(default=None, description='String Input Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'DCWh_SF', 'label': 'Watts'})
    InDCWh: int | None = Field(default=None, description='String Input Energy', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Wh', 'label': 'Watt-hours'})
    InDCPR: int | None = Field(default=None, description='String Performance Ratio', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'label': 'PR'})
    InN: int | None = Field(default=None, description='Number of modules in this input string', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'N'})


@register_model
class String_combiner_advanced(SunSpecModel):
    """An advanced string combiner"""

    GROUP_NAME: ClassVar[str] = 'string_combiner_advanced'
    MODEL_ID: ClassVar[int] = 402
    MODEL_LABEL: ClassVar[str] = 'String Combiner (Advanced)'

    ID: int | None = Field(default=402, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 402})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    DCA_SF: int | None = Field(default=None, description='Current scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    DCAhr_SF: int | None = Field(default=None, description='Amp-hour scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    DCV_SF: int | None = Field(default=None, description='Voltage scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    DCW_SF: int | None = Field(default=None, description='Power scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    DCWh_SF: int | None = Field(default=None, description='Energy scale factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    DCAMax: int | None = Field(default=None, description='Maximum DC Current Rating', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'label': 'Rating'})
    N: int | None = Field(default=None, description='Number of Inputs', json_schema_extra={'type': 'count', 'size': 1, 'label': 'N'})
    Evt: String_combiner_advancedEvt | int | None = Field(default=None, description='Events', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Event'})
    EvtVnd: int | None = Field(default=None, description='Vendor defined events', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Event'})
    DCA: int | None = Field(default=None, description='Total measured current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'DCA_SF', 'mandatory': 'M', 'label': 'Amps'})
    DCAhr: int | None = Field(default=None, description='Total metered Amp-hours', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Ah', 'sf': 'DCAhr_SF', 'label': 'Amp-hours'})
    DCV: int | None = Field(default=None, description='Output Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'DCV_SF', 'label': 'Voltage'})
    Tmp: int | None = Field(default=None, description='Internal operating temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Temp'})
    DCW: int | None = Field(default=None, description='Output power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'DCW_SF', 'label': 'Watts'})
    DCPR: int | None = Field(default=None, description='DC Performance ratio value', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'label': 'PR'})
    DCWh: int | None = Field(default=None, description='Output energy', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Wh', 'sf': 'DCWh_SF', 'mandatory': 'M', 'label': 'Watt-hours'})
    string: list[String_combiner_advancedString] = Field(default_factory=list, description='string', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
