"""SunSpec model 502: Solar Module

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Solar_module',
    'Solar_moduleEvt',
    'Solar_moduleStat',
]


class Solar_moduleStat(SunSpecEnum):
    """Enumeration for point ``Solar_module.Stat`` (enum16)."""
    OFF = 1
    SLEEPING = 2
    STARTING = 3
    MPPT = 4
    THROTTLED = 5
    SHUTTING_DOWN = 6
    FAULT = 7
    STANDBY = 8
    TEST = 9
    OTHER = 10


class Solar_moduleEvt(SunSpecFlags):
    """Bitfield for point ``Solar_module.Evt`` (bitfield32)."""
    GROUND_FAULT = 1
    INPUT_OVER_VOLTAGE = 2
    RESERVED_2 = 4
    DC_DISCONNECT = 8
    RESERVED_4 = 16
    RESERVED_5 = 32
    MANUAL_SHUTDOWN = 64
    OVER_TEMPERATURE = 128
    RESERVED_8 = 256
    RESERVED_9 = 512
    RESERVED_10 = 1024
    RESERVED_11 = 2048
    BLOWN_FUSE = 4096
    UNDER_TEMPERATURE = 8192
    MEMORY_LOSS = 16384
    ARC_DETECTION = 32768
    THEFT_DETECTION = 65536
    OUTPUT_OVER_CURRENT = 131072
    OUTPUT_OVER_VOLTAGE = 262144
    OUTPUT_UNDER_VOLTAGE = 524288
    TEST_FAILED = 1048576


@register_model
class Solar_module(SunSpecModel):
    """A solar module model supporting DC-DC converter"""

    GROUP_NAME: ClassVar[str] = 'solar_module'
    MODEL_ID: ClassVar[int] = 502
    MODEL_LABEL: ClassVar[str] = 'Solar Module'

    ID: int | None = Field(default=502, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 502})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    A_SF: int | None = Field(default=None, description='Current scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    V_SF: int | None = Field(default=None, description='Voltage scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    W_SF: int | None = Field(default=None, description='Power scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    Wh_SF: int | None = Field(default=None, description='Energy scale factor', json_schema_extra={'type': 'sunssf', 'size': 1})
    Stat: Solar_moduleStat | int | None = Field(default=None, description='Module Status Code', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Status'})
    StatVend: int | None = Field(default=None, description='Module Vendor Status Code', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Vendor Status'})
    Evt: Solar_moduleEvt | int | None = Field(default=None, description='Module Event Flags', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'Events'})
    EvtVend: int | None = Field(default=None, description='Vendor specific flags', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor Module Event Flags'})
    Ctl: int | None = Field(default=None, description='Module Control', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Control'})
    CtlVend: int | None = Field(default=None, description='Vendor Module Control', json_schema_extra={'type': 'enum32', 'size': 2, 'access': 'RW', 'label': 'Vendor Control'})
    CtlVal: int | None = Field(default=None, description='Module Control Value', json_schema_extra={'type': 'int32', 'size': 2, 'access': 'RW', 'label': 'Control Value'})
    Tms: int | None = Field(default=None, description='Time in seconds since 2000 epoch', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Timestamp'})
    OutA: int | None = Field(default=None, description='Output Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'label': 'Output Current'})
    OutV: int | None = Field(default=None, description='Output Voltage', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Output Voltage'})
    OutWh: int | None = Field(default=None, description='Output Energy', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'Wh_SF', 'label': 'Output Energy'})
    OutPw: int | None = Field(default=None, description='Output Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Output Power'})
    Tmp: int | None = Field(default=None, description='Module Temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Temp'})
    InA: int | None = Field(default=None, description='Input Current', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'label': 'Input Current'})
    InV: int | None = Field(default=None, description='Input Voltage', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Input Voltage'})
    InWh: int | None = Field(default=None, description='Input Energy', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'Wh_SF', 'label': 'Input Energy'})
    InW: int | None = Field(default=None, description='Input Power', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'W', 'sf': 'W_SF', 'label': 'Input Power'})
