"""SunSpec model 803: Lithium-Ion Battery Bank Model

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Lithium_ion_bank',
    'Lithium_ion_bankString',
    'Lithium_ion_bankStringStrConFail',
    'Lithium_ion_bankStringStrConSt',
    'Lithium_ion_bankStringStrDisRsn',
    'Lithium_ion_bankStringStrEvt1',
    'Lithium_ion_bankStringStrSetCon',
    'Lithium_ion_bankStringStrSetEna',
    'Lithium_ion_bankStringStrSt',
]


class Lithium_ion_bankStringStrSt(SunSpecFlags):
    """Bitfield for point ``Lithium_ion_bankString.StrSt`` (bitfield32)."""
    STRING_ENABLED = 1
    CONTACTOR_STATUS = 2


class Lithium_ion_bankStringStrConFail(SunSpecEnum):
    """Enumeration for point ``Lithium_ion_bankString.StrConFail`` (enum16)."""
    NO_FAILURE = 0
    BUTTON_PUSHED = 1
    STR_GROUND_FAULT = 2
    OUTSIDE_VOLTAGE_RANGE = 3
    STRING_NOT_ENABLED = 4
    FUSE_OPEN = 5
    CONTACTOR_FAILURE = 6
    PRECHARGE_FAILURE = 7
    STRING_FAULT = 8


class Lithium_ion_bankStringStrDisRsn(SunSpecEnum):
    """Enumeration for point ``Lithium_ion_bankString.StrDisRsn`` (enum16)."""
    NONE = 0
    FAULT = 1
    MAINTENANCE = 2
    EXTERNAL = 3
    OTHER = 4


class Lithium_ion_bankStringStrConSt(SunSpecFlags):
    """Bitfield for point ``Lithium_ion_bankString.StrConSt`` (bitfield32)."""
    CONTACTOR_0 = 1
    CONTACTOR_1 = 2
    CONTACTOR_2 = 4
    CONTACTOR_3 = 8
    CONTACTOR_4 = 16
    CONTACTOR_5 = 32
    CONTACTOR_6 = 64
    CONTACTOR_7 = 128
    CONTACTOR_8 = 256
    CONTACTOR_9 = 512
    CONTACTOR_10 = 1024
    CONTACTOR_11 = 2048
    CONTACTOR_12 = 4096
    CONTACTOR_13 = 8192
    CONTACTOR_14 = 16384
    CONTACTOR_15 = 32768
    CONTACTOR_16 = 65536
    CONTACTOR_17 = 131072
    CONTACTOR_18 = 262144
    CONTACTOR_19 = 524288
    CONTACTOR_20 = 1048576
    CONTACTOR_21 = 2097152
    CONTACTOR_22 = 4194304
    CONTACTOR_23 = 8388608
    CONTACTOR_24 = 16777216
    CONTACTOR_25 = 33554432
    CONTACTOR_26 = 67108864
    CONTACTOR_27 = 134217728
    CONTACTOR_28 = 268435456
    CONTACTOR_29 = 536870912
    CONTACTOR_30 = 1073741824


class Lithium_ion_bankStringStrEvt1(SunSpecFlags):
    """Bitfield for point ``Lithium_ion_bankString.StrEvt1`` (bitfield32)."""
    COMMUNICATION_ERROR = 1
    OVER_TEMP_ALARM = 2
    OVER_TEMP_WARNING = 4
    UNDER_TEMP_ALARM = 8
    UNDER_TEMP_WARNING = 16
    OVER_CHARGE_CURRENT_ALARM = 32
    OVER_CHARGE_CURRENT_WARNING = 64
    OVER_DISCHARGE_CURRENT_ALARM = 128
    OVER_DISCHARGE_CURRENT_WARNING = 256
    OVER_VOLT_ALARM = 512
    OVER_VOLT_WARNING = 1024
    UNDER_VOLT_ALARM = 2048
    UNDER_VOLT_WARNING = 4096
    UNDER_SOC_MIN_ALARM = 8192
    UNDER_SOC_MIN_WARNING = 16384
    OVER_SOC_MAX_ALARM = 32768
    OVER_SOC_MAX_WARNING = 65536
    VOLTAGE_IMBALANCE_WARNING = 131072
    TEMPERATURE_IMBALANCE_ALARM = 262144
    TEMPERATURE_IMBALANCE_WARNING = 524288
    CONTACTOR_ERROR = 1048576
    FAN_ERROR = 2097152
    GROUND_FAULT = 4194304
    OPEN_DOOR_ERROR = 8388608
    RESERVED_1 = 16777216
    OTHER_ALARM = 33554432
    OTHER_WARNING = 67108864
    RESERVED_2 = 134217728
    CONFIGURATION_ALARM = 268435456
    CONFIGURATION_WARNING = 536870912


class Lithium_ion_bankStringStrSetEna(SunSpecEnum):
    """Enumeration for point ``Lithium_ion_bankString.StrSetEna`` (enum16)."""
    ENABLE_STRING = 1
    DISABLE_STRING = 2


class Lithium_ion_bankStringStrSetCon(SunSpecEnum):
    """Enumeration for point ``Lithium_ion_bankString.StrSetCon`` (enum16)."""
    CONNECT_STRING = 1
    DISCONNECT_STRING = 2


class Lithium_ion_bankString(SunSpecGroup):
    """string"""

    GROUP_NAME: ClassVar[str] = 'string'

    StrNMod: int | None = Field(default=None, description='Count of modules in the string.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Module Count'})
    StrSt: Lithium_ion_bankStringStrSt | int | None = Field(default=None, description='Current status of the string.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'String Status'})
    StrConFail: Lithium_ion_bankStringStrConFail | int | None = Field(default=None, description='Connection Failure Reason', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Connection Failure Reason'})
    StrSoC: int | None = Field(default=None, description='Battery string state of charge, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%', 'sf': 'SoC_SF', 'mandatory': 'M', 'label': 'String State of Charge'})
    StrSoH: int | None = Field(default=None, description='Battery string state of health, expressed as a percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%', 'sf': 'SoH_SF', 'label': 'String State of Health'})
    StrA: int | None = Field(default=None, description='String current measurement.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'String Current'})
    StrCellVMax: int | None = Field(default=None, description='Maximum voltage for all cells in the string.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'mandatory': 'M', 'label': 'Max Cell Voltage'})
    StrCellVMaxMod: int | None = Field(default=None, description='Module containing the maximum cell voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Cell Voltage Module'})
    StrCellVMin: int | None = Field(default=None, description='Minimum voltage for all cells in the string.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'mandatory': 'M', 'label': 'Min Cell Voltage'})
    StrCellVMinMod: int | None = Field(default=None, description='Module containing the minimum cell voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Cell Voltage Module'})
    StrCellVAvg: int | None = Field(default=None, description='Average voltage for all cells in the string.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'CellV_SF', 'mandatory': 'M', 'label': 'Average Cell Voltage'})
    StrModTmpMax: int | None = Field(default=None, description='Maximum temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'mandatory': 'M', 'label': 'Max Module Temperature'})
    StrModTmpMaxMod: int | None = Field(default=None, description='Module with the maximum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Module Temperature Module'})
    StrModTmpMin: int | None = Field(default=None, description='Minimum temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'mandatory': 'M', 'label': 'Min Module Temperature'})
    StrModTmpMinMod: int | None = Field(default=None, description='Module with the minimum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Module Temperature Module'})
    StrModTmpAvg: int | None = Field(default=None, description='Average temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'mandatory': 'M', 'label': 'Average Module Temperature'})
    StrDisRsn: Lithium_ion_bankStringStrDisRsn | int | None = Field(default=None, description='Reason why the string is currently disabled.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Disabled Reason'})
    StrConSt: Lithium_ion_bankStringStrConSt | int | None = Field(default=None, description='Status of the contactor(s) for the string.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Contactor Status'})
    StrEvt1: Lithium_ion_bankStringStrEvt1 | int | None = Field(default=None, description='Alarms, warnings and status values.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'mandatory': 'M', 'label': 'String Event 1'})
    StrEvt2: int | None = Field(default=None, description='Alarms, warnings and status values.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'String Event 2'})
    StrEvtVnd1: int | None = Field(default=None, description='Vendor defined events.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor String Event Bitfield 1'})
    StrEvtVnd2: int | None = Field(default=None, description='Vendor defined events.', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Vendor String Event Bitfield 2'})
    StrSetEna: Lithium_ion_bankStringStrSetEna | int | None = Field(default=None, description='Enables and disables the string.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Enable/Disable String'})
    StrSetCon: Lithium_ion_bankStringStrSetCon | int | None = Field(default=None, description='Connects and disconnects the string.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Connect/Disconnect String'})
    Pad1: int | None = Field(default=None, description='Pad register.', json_schema_extra={'type': 'pad', 'size': 1, 'mandatory': 'M', 'label': 'Pad'})
    Pad2: int | None = Field(default=None, description='Pad register.', json_schema_extra={'type': 'pad', 'size': 1, 'mandatory': 'M', 'label': 'Pad'})


@register_model
class Lithium_ion_bank(SunSpecModel):
    """Lithium-Ion Battery Bank Model"""

    GROUP_NAME: ClassVar[str] = 'lithium_ion_bank'
    MODEL_ID: ClassVar[int] = 803
    MODEL_LABEL: ClassVar[str] = 'Lithium-Ion Battery Bank Model'

    ID: int | None = Field(default=803, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 803})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    NStr: int | None = Field(default=None, description='Number of strings in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'String Count'})
    NStrCon: int | None = Field(default=None, description='Number of strings with contactor closed.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Connected String Count'})
    ModTmpMax: int | None = Field(default=None, description='Maximum temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'mandatory': 'M', 'label': 'Max Module Temperature'})
    ModTmpMaxStr: int | None = Field(default=None, description='String containing the module with maximum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Module Temperature String'})
    ModTmpMaxMod: int | None = Field(default=None, description='Module with maximum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max Module Temperature Module'})
    ModTmpMin: int | None = Field(default=None, description='Minimum temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'mandatory': 'M', 'label': 'Min Module Temperature'})
    ModTmpMinStr: int | None = Field(default=None, description='String containing the module with minimum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Module Temperature String'})
    ModTmpMinMod: int | None = Field(default=None, description='Module with minimum temperature.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min Module Temperature Module'})
    ModTmpAvg: int | None = Field(default=None, description='Average temperature for all modules in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'sf': 'ModTmp_SF', 'label': 'Average Module Temperature'})
    StrVMax: int | None = Field(default=None, description='Maximum string voltage for all strings in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Max String Voltage'})
    StrVMaxStr: int | None = Field(default=None, description='String with maximum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max String Voltage String'})
    StrVMin: int | None = Field(default=None, description='Minimum string voltage for all strings in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Min String Voltage'})
    StrVMinStr: int | None = Field(default=None, description='String with minimum voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min String Voltage String'})
    StrVAvg: int | None = Field(default=None, description='Average string voltage for all strings in the bank.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'label': 'Average String Voltage'})
    StrAMax: int | None = Field(default=None, description='Maximum current of any string in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'label': 'Max String Current'})
    StrAMaxStr: int | None = Field(default=None, description='String with the maximum current.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Max String Current String'})
    StrAMin: int | None = Field(default=None, description='Minimum current of any string in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'label': 'Min String Current'})
    StrAMinStr: int | None = Field(default=None, description='String with the minimum current.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Min String Current String'})
    StrAAvg: int | None = Field(default=None, description='Average string current for all strings in the bank.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'label': 'Average String Current'})
    NCellBal: int | None = Field(default=None, description='Total number of cells that are currently being balanced.', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Battery Cell Balancing Count'})
    CellV_SF: int | None = Field(default=None, description='Scale factor for cell voltage.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    ModTmp_SF: int | None = Field(default=None, description='Scale factor for module temperatures.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    A_SF: int | None = Field(default=None, description='Scale factor for string currents.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    SoH_SF: int | None = Field(default=None, description='Scale factor for string state of health.', json_schema_extra={'type': 'sunssf', 'size': 1})
    SoC_SF: int | None = Field(default=None, description='Scale factor for string state of charge.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    V_SF: int | None = Field(default=None, description='Scale factor for string voltage.', json_schema_extra={'type': 'sunssf', 'size': 1})
    string: list[Lithium_ion_bankString] = Field(default_factory=list, description='string', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NStr'})
