"""SunSpec model 140: HVRTX

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Hvrtx',
    'HvrtxCrvType',
    'HvrtxCurve',
    'HvrtxCurveReadOnly',
    'HvrtxModEna',
]


class HvrtxCurveReadOnly(SunSpecEnum):
    """Enumeration for point ``HvrtxCurve.ReadOnly`` (enum16)."""
    READWRITE = 0
    READONLY = 1


class HvrtxModEna(SunSpecFlags):
    """Bitfield for point ``Hvrtx.ModEna`` (bitfield16)."""
    ENABLED = 1


class HvrtxCrvType(SunSpecEnum):
    """Enumeration for point ``Hvrtx.CrvType`` (enum16)."""
    CEASE_TO_ENERGIZE = 1


class HvrtxCurve(SunSpecGroup):
    """curve"""

    GROUP_NAME: ClassVar[str] = 'curve'

    ActPt: int | None = Field(default=None, description='Number of active points in array.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActPt'})
    Tms1: int | None = Field(default=None, description='Point 1 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'Tms1'})
    V1: int | None = Field(default=None, description='Point 1 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'mandatory': 'M', 'label': 'V1'})
    Tms2: int | None = Field(default=None, description='Point 2 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms2'})
    V2: int | None = Field(default=None, description='Point 2 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V2'})
    Tms3: int | None = Field(default=None, description='Point 3 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms3'})
    V3: int | None = Field(default=None, description='Point 3 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V3'})
    Tms4: int | None = Field(default=None, description='Point 4 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms4'})
    V4: int | None = Field(default=None, description='Point 4 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V4'})
    Tms5: int | None = Field(default=None, description='Point 5 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms5'})
    V5: int | None = Field(default=None, description='Point 5 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V5'})
    Tms6: int | None = Field(default=None, description='Point 6 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms6'})
    V6: int | None = Field(default=None, description='Point 6 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V6'})
    Tms7: int | None = Field(default=None, description='Point 7 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms7'})
    V7: int | None = Field(default=None, description='Point 7 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V7'})
    Tms8: int | None = Field(default=None, description='Point 8 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms8'})
    V8: int | None = Field(default=None, description='Point 8 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V8'})
    Tms9: int | None = Field(default=None, description='Point 9 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms9'})
    V9: int | None = Field(default=None, description='Point 9 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V9'})
    Tms10: int | None = Field(default=None, description='Point 10 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms10'})
    V10: int | None = Field(default=None, description='Point 10 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V10'})
    Tms11: int | None = Field(default=None, description='Point 11 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms11'})
    V11: int | None = Field(default=None, description='Point 11 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V11'})
    Tms12: int | None = Field(default=None, description='Point 12 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms12'})
    V12: int | None = Field(default=None, description='Point 12 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V12'})
    Tms13: int | None = Field(default=None, description='Point 13 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms13'})
    V13: int | None = Field(default=None, description='Point 13 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V13'})
    Tms14: int | None = Field(default=None, description='Point 14 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms14'})
    V14: int | None = Field(default=None, description='Point 14 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V14'})
    Tms15: int | None = Field(default=None, description='Point 15 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms15'})
    V15: int | None = Field(default=None, description='Point 15 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V15'})
    Tms16: int | None = Field(default=None, description='Point 16 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms16'})
    V16: int | None = Field(default=None, description='Point 16 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V16'})
    Tms17: int | None = Field(default=None, description='Point 17 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms17'})
    V17: int | None = Field(default=None, description='Point 17 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V17'})
    Tms18: int | None = Field(default=None, description='Point 18 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms18'})
    V18: int | None = Field(default=None, description='Point 18 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V18'})
    Tms19: int | None = Field(default=None, description='Point 19 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms19'})
    V19: int | None = Field(default=None, description='Point 19 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V19'})
    Tms20: int | None = Field(default=None, description='Point 20 duration.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'sf': 'Tms_SF', 'access': 'RW', 'label': 'Tms20'})
    V20: int | None = Field(default=None, description='Point 20 voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '% VRef', 'sf': 'V_SF', 'access': 'RW', 'label': 'V20'})
    CrvNam: str | None = Field(default=None, description='Optional description for curve.', json_schema_extra={'type': 'string', 'size': 8, 'access': 'RW', 'label': 'CrvNam'})
    ReadOnly: HvrtxCurveReadOnly | int | None = Field(default=None, description='Curve is read-only or can be modified.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'ReadOnly'})


@register_model
class Hvrtx(SunSpecModel):
    """HVRT extended curve"""

    GROUP_NAME: ClassVar[str] = 'hvrtx'
    MODEL_ID: ClassVar[int] = 140
    MODEL_LABEL: ClassVar[str] = 'HVRTX'

    ID: int | None = Field(default=140, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 140})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    ActCrv: int | None = Field(default=None, description='Index of active curve. 0=no active curve.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ActCrv'})
    ModEna: HvrtxModEna | int | None = Field(default=None, description='LVRT control mode. Enable active curve.', union_mode='left_to_right', json_schema_extra={'type': 'bitfield16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'ModEna'})
    WinTms: int | None = Field(default=None, description='Time window for LVRT change.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'WinTms'})
    RvrtTms: int | None = Field(default=None, description='Timeout period for LVRT curve selection.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RvrtTms'})
    RmpTms: int | None = Field(default=None, description='Ramp time for moving from current mode to new mode.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'RmpTms'})
    NCrv: int | None = Field(default=None, description='Number of curves supported (recommend 4).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NCrv'})
    NPt: int | None = Field(default=None, description='Number of curve points supported (maximum of 20).', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'NPt'})
    Tms_SF: int | None = Field(default=None, description='Scale factor for duration.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'Tms_SF'})
    V_SF: int | None = Field(default=None, description='Scale factor for percent VRef.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'V_SF'})
    CrvType: HvrtxCrvType | int | None = Field(default=None, description='CrvType', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M'})
    curve: list[HvrtxCurve] = Field(default_factory=list, description='curve', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
