"""SunSpec model 704: DER AC Controls

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERCtlAC',
    'DERCtlACAntiIslEna',
    'DERCtlACPFWAbs',
    'DERCtlACPFWAbsEna',
    'DERCtlACPFWAbsEnaRvrt',
    'DERCtlACPFWAbsExt',
    'DERCtlACPFWAbsRvrt',
    'DERCtlACPFWAbsRvrtExt',
    'DERCtlACPFWInj',
    'DERCtlACPFWInjEna',
    'DERCtlACPFWInjEnaRvrt',
    'DERCtlACPFWInjExt',
    'DERCtlACPFWInjRvrt',
    'DERCtlACPFWInjRvrtExt',
    'DERCtlACVarSetEna',
    'DERCtlACVarSetEnaRvrt',
    'DERCtlACVarSetMod',
    'DERCtlACVarSetPri',
    'DERCtlACWMaxLimPctEna',
    'DERCtlACWMaxLimPctEnaRvrt',
    'DERCtlACWRmpRef',
    'DERCtlACWSetEna',
    'DERCtlACWSetEnaRvrt',
    'DERCtlACWSetMod',
]


class DERCtlACPFWInjExt(SunSpecEnum):
    """Enumeration for point ``DERCtlACPFWInj.Ext`` (enum16)."""
    OVER_EXCITED = 0    # Over-Excited
    UNDER_EXCITED = 1    # Under-Excited


class DERCtlACPFWInjRvrtExt(SunSpecEnum):
    """Enumeration for point ``DERCtlACPFWInjRvrt.Ext`` (enum16)."""
    OVER_EXCITED = 0    # Over-Excited
    UNDER_EXCITED = 1    # Under-Excited


class DERCtlACPFWAbsExt(SunSpecEnum):
    """Enumeration for point ``DERCtlACPFWAbs.Ext`` (enum16)."""
    OVER_EXCITED = 0    # Over-Excited
    UNDER_EXCITED = 1    # Under-Excited


class DERCtlACPFWAbsRvrtExt(SunSpecEnum):
    """Enumeration for point ``DERCtlACPFWAbsRvrt.Ext`` (enum16)."""
    OVER_EXCITED = 0    # Over-Excited
    UNDER_EXCITED = 1    # Under-Excited


class DERCtlACPFWInjEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.PFWInjEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACPFWInjEnaRvrt(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.PFWInjEnaRvrt`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACPFWAbsEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.PFWAbsEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACPFWAbsEnaRvrt(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.PFWAbsEnaRvrt`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACWMaxLimPctEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WMaxLimPctEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACWMaxLimPctEnaRvrt(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WMaxLimPctEnaRvrt`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACWSetEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WSetEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACWSetMod(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WSetMod`` (enum16)."""
    W_MAX_PCT = 0    # Active Power As Max Percent
    WATTS = 1    # Active Power As Watts


class DERCtlACWSetEnaRvrt(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WSetEnaRvrt`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACVarSetEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.VarSetEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACVarSetMod(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.VarSetMod`` (enum16)."""
    W_MAX_PCT = 0    # Reactive Power As Watt Max Pct
    VAR_MAX_PCT = 1    # Reactive Power As Var Max Pct
    VAR_AVAIL_PCT = 2    # Reactive Power As Var Avail Pct
    VA_MAX_PCT = 3    # Reactive Power As VA Max Pct
    VARS = 4    # Reactive Power As Vars


class DERCtlACVarSetPri(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.VarSetPri`` (enum16)."""
    ACTIVE = 0    # Active Power Priority
    REACTIVE = 1    # Reactive Power Priority
    VENDOR = 2    # Vendor Power Priority


class DERCtlACVarSetEnaRvrt(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.VarSetEnaRvrt`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACWRmpRef(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.WRmpRef`` (enum16)."""
    A_MAX = 0    # Max Current Ramp
    W_MAX = 1    # Max Active Power Ramp


class DERCtlACAntiIslEna(SunSpecEnum):
    """Enumeration for point ``DERCtlAC.AntiIslEna`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERCtlACPFWInj(SunSpecGroup):
    """Power factor setpoint when injecting active power."""

    GROUP_NAME: ClassVar[str] = 'PFWInj'

    PF: int | None = Field(default=None, description='Power factor setpoint when injecting active power.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Power Factor (W Inj) ', 'standards': ['IEEE 1547-2018']})
    Ext: DERCtlACPFWInjExt | int | None = Field(default=None, description='Power factor excitation setpoint when injecting active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Excitation (W Inj)', 'standards': ['IEEE 1547-2018']})


class DERCtlACPFWInjRvrt(SunSpecGroup):
    """Reversion power factor setpoint when injecting active power."""

    GROUP_NAME: ClassVar[str] = 'PFWInjRvrt'

    PF: int | None = Field(default=None, description='Reversion power factor setpoint when injecting active power.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Reversion Power Factor (W Inj) '})
    Ext: DERCtlACPFWInjRvrtExt | int | None = Field(default=None, description='Reversion power factor excitation setpoint when injecting active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reversion PF Excitation (W Inj)'})


class DERCtlACPFWAbs(SunSpecGroup):
    """Power factor setpoint when absorbing active power."""

    GROUP_NAME: ClassVar[str] = 'PFWAbs'

    PF: int | None = Field(default=None, description='Power factor setpoint when absorbing active power.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Power Factor (W Abs) '})
    Ext: DERCtlACPFWAbsExt | int | None = Field(default=None, description='Power factor excitation setpoint when absorbing active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Excitation (W Abs)'})


class DERCtlACPFWAbsRvrt(SunSpecGroup):
    """Reversion power factor setpoint when absorbing active power."""

    GROUP_NAME: ClassVar[str] = 'PFWAbsRvrt'

    PF: int | None = Field(default=None, description='Reversion power factor setpoint when absorbing active power.', json_schema_extra={'type': 'uint16', 'size': 1, 'sf': 'PF_SF', 'access': 'RW', 'label': 'Reversion Power Factor (W Abs) '})
    Ext: DERCtlACPFWAbsRvrtExt | int | None = Field(default=None, description='Reversion power factor excitation setpoint when absorbing active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reversion PF Excitation (W Abs)'})


@register_model
class DERCtlAC(SunSpecModel):
    """DER AC controls model."""

    GROUP_NAME: ClassVar[str] = 'DERCtlAC'
    MODEL_ID: ClassVar[int] = 704
    MODEL_LABEL: ClassVar[str] = 'DER AC Controls'

    ID: int | None = Field(default=704, description='DER AC controls model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 704})
    L: int | None = Field(default=None, description='DER AC controls model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    PFWInjEna: DERCtlACPFWInjEna | int | None = Field(default=None, description='Power factor enable when injecting active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Enable (W Inj) Enable', 'standards': ['IEEE 1547-2018']})
    PFWInjEnaRvrt: DERCtlACPFWInjEnaRvrt | int | None = Field(default=None, description='Power factor reversion timer when injecting active power enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Reversion Enable (W Inj)'})
    PFWInjRvrtTms: int | None = Field(default=None, description='Power factor reversion timer when injecting active power.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'PF Reversion Time (W Inj)'})
    PFWInjRvrtRem: int | None = Field(default=None, description='Power factor reversion time remaining when injecting active power.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'PF Reversion Time Rem (W Inj)'})
    PFWAbsEna: DERCtlACPFWAbsEna | int | None = Field(default=None, description='Power factor enable when absorbing active power.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Enable (W Abs) Enable'})
    PFWAbsEnaRvrt: DERCtlACPFWAbsEnaRvrt | int | None = Field(default=None, description='Power factor reversion timer when absorbing active power enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Factor Reversion Enable (W Abs)'})
    PFWAbsRvrtTms: int | None = Field(default=None, description='Power factor reversion timer when absorbing active power.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'PF Reversion Time (W Abs)'})
    PFWAbsRvrtRem: int | None = Field(default=None, description='Power factor reversion time remaining when absorbing active power.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'PF Reversion Time Rem (W Abs)'})
    WMaxLimPctEna: DERCtlACWMaxLimPctEna | int | None = Field(default=None, description='Limit maximum active power percent enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Limit Max Power Pct Enable', 'standards': ['IEEE 1547-2018']})
    WMaxLimPct: int | None = Field(default=None, description='Limit maximum active power percent value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'sf': 'WMaxLimPct_SF', 'access': 'RW', 'label': 'Limit Max Power Pct Setpoint', 'standards': ['IEEE 1547-2018']})
    WMaxLimPctRvrt: int | None = Field(default=None, description='Reversion limit maximum active power percent value.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Pct', 'sf': 'WMaxLimPct_SF', 'access': 'RW', 'label': 'Reversion Limit Max Power Pct'})
    WMaxLimPctEnaRvrt: DERCtlACWMaxLimPctEnaRvrt | int | None = Field(default=None, description='Reversion limit maximum active power percent value enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reversion Limit Max Power Pct Enable'})
    WMaxLimPctRvrtTms: int | None = Field(default=None, description='Limit maximum active power percent reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Limit Max Power Pct Reversion Time'})
    WMaxLimPctRvrtRem: int | None = Field(default=None, description='Limit maximum active power percent reversion time remaining.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Limit Max Power Pct Rev Time Rem'})
    WSetEna: DERCtlACWSetEna | int | None = Field(default=None, description='Set active power enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Set Active Power Enable'})
    WSetMod: DERCtlACWSetMod | int | None = Field(default=None, description='Set active power mode.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Set Active Power Mode'})
    WSet: int | None = Field(default=None, description='Active power setting value in watts.', json_schema_extra={'type': 'int32', 'size': 2, 'units': 'W', 'sf': 'WSet_SF', 'access': 'RW', 'label': 'Active Power Setpoint (W)'})
    WSetRvrt: int | None = Field(default=None, description='Reversion active power setting value in watts.', json_schema_extra={'type': 'int32', 'size': 2, 'units': 'W', 'sf': 'WSet_SF', 'access': 'RW', 'label': 'Reversion Active Power (W)'})
    WSetPct: int | None = Field(default=None, description='Active power setting value as percent.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'WSetPct_SF', 'access': 'RW', 'label': 'Active Power Setpoint (Pct)'})
    WSetPctRvrt: int | None = Field(default=None, description='Reversion active power setting value as percent.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'WSetPct_SF', 'access': 'RW', 'label': 'Reversion Active Power (Pct)'})
    WSetEnaRvrt: DERCtlACWSetEnaRvrt | int | None = Field(default=None, description='Reversion active power function enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reversion Active Power Enable'})
    WSetRvrtTms: int | None = Field(default=None, description='Set active power reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Active Power Reversion Time'})
    WSetRvrtRem: int | None = Field(default=None, description='Set active power reversion time remaining.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Active Power Rev Time Rem'})
    VarSetEna: DERCtlACVarSetEna | int | None = Field(default=None, description='Set reactive power enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Set Reactive Power Enable', 'standards': ['IEEE 1547-2018']})
    VarSetMod: DERCtlACVarSetMod | int | None = Field(default=None, description='Set reactive power mode.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Set Reactive Power Mode', 'standards': ['IEEE 1547-2018']})
    VarSetPri: DERCtlACVarSetPri | int | None = Field(default=None, description='Reactive power priority.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reactive Power Priority', 'standards': ['IEEE 1547-2018']})
    VarSet: int | None = Field(default=None, description='Reactive power setting value in vars.', json_schema_extra={'type': 'int32', 'size': 2, 'units': 'Var', 'sf': 'VarSet_SF', 'access': 'RW', 'label': 'Reactive Power Setpoint (Vars)'})
    VarSetRvrt: int | None = Field(default=None, description='Reversion reactive power setting value in vars.', json_schema_extra={'type': 'int32', 'size': 2, 'units': 'Var', 'sf': 'VarSet_SF', 'access': 'RW', 'label': 'Reversion Reactive Power (Vars)'})
    VarSetPct: int | None = Field(default=None, description='Reactive power setting value as percent.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'VarSetPct_SF', 'access': 'RW', 'label': 'Reactive Power Setpoint (Pct)', 'standards': ['IEEE 1547-2018']})
    VarSetPctRvrt: int | None = Field(default=None, description='Reversion reactive power setting value as percent.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'Pct', 'sf': 'VarSetPct_SF', 'access': 'RW', 'label': 'Reversion Reactive Power (Pct)'})
    VarSetEnaRvrt: DERCtlACVarSetEnaRvrt | int | None = Field(default=None, description='Reversion reactive power function enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Reversion Reactive Power Enable'})
    VarSetRvrtTms: int | None = Field(default=None, description='Set reactive power reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Reactive Power Reversion Time'})
    VarSetRvrtRem: int | None = Field(default=None, description='Set reactive power reversion time remaining.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Reactive Power Rev Time Rem'})
    WRmp: int | None = Field(default=None, description='Ramp rate for increases in active power during normal generation.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%Max/Sec', 'access': 'RW', 'label': 'Normal Ramp Rate'})
    WRmpRef: DERCtlACWRmpRef | int | None = Field(default=None, description='Ramp rate reference unit for increases in active power or current during normal generation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Normal Ramp Rate Reference'})
    VarRmp: int | None = Field(default=None, description='Ramp rate based on max reactive power per second.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': '%Max/Sec', 'access': 'RW', 'label': 'Reactive Power Ramp Rate'})
    AntiIslEna: DERCtlACAntiIslEna | int | None = Field(default=None, description='Anti-islanding enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Anti-Islanding Enable'})
    PF_SF: int | None = Field(default=None, description='Power factor scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Power Factor Scale Factor', 'standards': ['IEEE 1547-2018']})
    WMaxLimPct_SF: int | None = Field(default=None, description='Limit maximum power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Limit Max Power Scale Factor', 'standards': ['IEEE 1547-2018']})
    WSet_SF: int | None = Field(default=None, description='Active power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Active Power Scale Factor'})
    WSetPct_SF: int | None = Field(default=None, description='Active power pct scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Active Power Pct Scale Factor'})
    VarSet_SF: int | None = Field(default=None, description='Reactive power scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Reactive Power Scale Factor'})
    VarSetPct_SF: int | None = Field(default=None, description='Reactive power pct scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'static': 'S', 'label': 'Reactive Power Pct Scale Factor', 'standards': ['IEEE 1547-2018']})
    PFWInj: DERCtlACPFWInj | None = Field(default=None, description='Power factor setpoint when injecting active power.', json_schema_extra={'type': 'group', 'group_type': 'sync'})
    PFWInjRvrt: DERCtlACPFWInjRvrt | None = Field(default=None, description='Reversion power factor setpoint when injecting active power.', json_schema_extra={'type': 'group', 'group_type': 'sync'})
    PFWAbs: DERCtlACPFWAbs | None = Field(default=None, description='Power factor setpoint when absorbing active power.', json_schema_extra={'type': 'group', 'group_type': 'sync'})
    PFWAbsRvrt: DERCtlACPFWAbsRvrt | None = Field(default=None, description='Reversion power factor setpoint when absorbing active power.', json_schema_extra={'type': 'group', 'group_type': 'sync'})
