"""SunSpec model 160: Multiple MPPT Inverter Extension Model

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Mppt',
    'MpptEvt',
    'MpptModule',
    'MpptModuleDCEvt',
    'MpptModuleDCSt',
]


class MpptModuleDCSt(SunSpecEnum):
    """Enumeration for point ``MpptModule.DCSt`` (enum16)."""
    OFF = 1
    SLEEPING = 2
    STARTING = 3
    MPPT = 4
    THROTTLED = 5
    SHUTTING_DOWN = 6
    FAULT = 7
    STANDBY = 8
    TEST = 9
    RESERVED_10 = 10


class MpptModuleDCEvt(SunSpecFlags):
    """Bitfield for point ``MpptModule.DCEvt`` (bitfield32)."""
    GROUND_FAULT = 1
    INPUT_OVER_VOLTAGE = 2
    RESERVED_2 = 4
    DC_DISCONNECT = 8
    RESERVED_4 = 16
    CABINET_OPEN = 32
    MANUAL_SHUTDOWN = 64
    OVER_TEMP = 128
    RESERVED_8 = 256
    RESERVED_9 = 512
    RESERVED_10 = 1024
    RESERVED_11 = 2048
    BLOWN_FUSE = 4096
    UNDER_TEMP = 8192
    MEMORY_LOSS = 16384
    ARC_DETECTION = 32768
    RESERVED_16 = 65536
    RESERVED_17 = 131072
    RESERVED_18 = 262144
    RESERVED_19 = 524288
    TEST_FAILED = 1048576
    INPUT_UNDER_VOLTAGE = 2097152
    INPUT_OVER_CURRENT = 4194304


class MpptEvt(SunSpecFlags):
    """Bitfield for point ``Mppt.Evt`` (bitfield32)."""
    GROUND_FAULT = 1
    INPUT_OVER_VOLTAGE = 2
    RESERVED_2 = 4
    DC_DISCONNECT = 8
    RESERVED_4 = 16
    CABINET_OPEN = 32
    MANUAL_SHUTDOWN = 64
    OVER_TEMP = 128
    RESERVED_8 = 256
    RESERVED_9 = 512
    RESERVED_10 = 1024
    RESERVED_11 = 2048
    BLOWN_FUSE = 4096
    UNDER_TEMP = 8192
    MEMORY_LOSS = 16384
    ARC_DETECTION = 32768
    RESERVED_16 = 65536
    RESERVED_17 = 131072
    RESERVED_18 = 262144
    RESERVED_19 = 524288
    TEST_FAILED = 1048576
    INPUT_UNDER_VOLTAGE = 2097152
    INPUT_OVER_CURRENT = 4194304


class MpptModule(SunSpecGroup):
    """module"""

    GROUP_NAME: ClassVar[str] = 'module'

    ID: int | None = Field(default=None, description='Input ID', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Input ID'})
    IDStr: str | None = Field(default=None, description='Input ID String', json_schema_extra={'type': 'string', 'size': 8, 'label': 'Input ID String'})
    DCA: int | None = Field(default=None, description='DC Current', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'DCA_SF', 'label': 'DC Current'})
    DCV: int | None = Field(default=None, description='DC Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'DCV_SF', 'label': 'DC Voltage'})
    DCW: int | None = Field(default=None, description='DC Power', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'DCW_SF', 'label': 'DC Power'})
    DCWH: int | None = Field(default=None, description='Lifetime Energy', json_schema_extra={'type': 'acc32', 'size': 2, 'units': 'Wh', 'sf': 'DCWH_SF', 'label': 'Lifetime Energy'})
    Tms: int | None = Field(default=None, description='Timestamp', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Timestamp'})
    Tmp: int | None = Field(default=None, description='Temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Temperature'})
    DCSt: MpptModuleDCSt | int | None = Field(default=None, description='Operating State', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'label': 'Operating State'})
    DCEvt: MpptModuleDCEvt | int | None = Field(default=None, description='Module Events', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Module Events'})


@register_model
class Mppt(SunSpecModel):
    """Multiple MPPT Inverter Extension Model"""

    GROUP_NAME: ClassVar[str] = 'mppt'
    MODEL_ID: ClassVar[int] = 160
    MODEL_LABEL: ClassVar[str] = 'Multiple MPPT Inverter Extension Model'

    ID: int | None = Field(default=160, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 160})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    DCA_SF: int | None = Field(default=None, description='Current Scale Factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'Current Scale Factor'})
    DCV_SF: int | None = Field(default=None, description='Voltage Scale Factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'Voltage Scale Factor'})
    DCW_SF: int | None = Field(default=None, description='Power Scale Factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'Power Scale Factor'})
    DCWH_SF: int | None = Field(default=None, description='Energy Scale Factor', json_schema_extra={'type': 'sunssf', 'size': 1, 'label': 'Energy Scale Factor'})
    Evt: MpptEvt | int | None = Field(default=None, description='Global Events', union_mode='left_to_right', json_schema_extra={'type': 'bitfield32', 'size': 2, 'label': 'Global Events'})
    N: int | None = Field(default=None, description='Number of Modules', json_schema_extra={'type': 'count', 'size': 1, 'label': 'Number of Modules'})
    TmsPer: int | None = Field(default=None, description='Timestamp Period', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Timestamp Period'})
    module: list[MpptModule] = Field(default_factory=list, description='module', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
