"""SunSpec model 64020: Mersen GreenString

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_64020',
    'Model_64020Repeating',
]


class Model_64020Repeating(SunSpecGroup):
    """repeating"""

    GROUP_NAME: ClassVar[str] = 'repeating'

    SerialNumber: str | None = Field(default=None, description='strings of 16 characters', json_schema_extra={'type': 'string', 'size': 9, 'mandatory': 'M', 'label': 'Serial number'})
    Firmware: str | None = Field(default=None, description='string of 11 characters', json_schema_extra={'type': 'string', 'size': 6, 'mandatory': 'M', 'label': 'Firmware version'})
    Hardware: int | None = Field(default=None, description='Hardware version', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Hardware version'})


@register_model
class Model_64020(SunSpecModel):
    """Mersen GreenString"""

    GROUP_NAME: ClassVar[str] = 'model_64020'
    MODEL_ID: ClassVar[int] = 64020
    MODEL_LABEL: ClassVar[str] = 'Mersen GreenString'

    ID: int | None = Field(default=64020, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 64020})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Aux0Tmp: int | None = Field(default=None, description='Aux 0 temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Aux 0 temperature'})
    Aux1Tmp: int | None = Field(default=None, description='Aux 1 temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Aux 1 temperature'})
    Aux2Tmp: int | None = Field(default=None, description='Aux 2 temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Aux 2 temperature'})
    Aux3Tmp: int | None = Field(default=None, description='Aux 3 temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Aux 3 temperature'})
    Aux4Tmp: int | None = Field(default=None, description='Aux 4 temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'label': 'Aux 4 temperature'})
    ProbeTmp: int | None = Field(default=None, description='Probe Temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'mandatory': 'M', 'label': 'Probe Temperature'})
    MainTmp: int | None = Field(default=None, description='Main Temperature', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'C', 'mandatory': 'M', 'label': 'Main Temperature'})
    SensorV_SF: int | None = Field(default=None, description='Voltage scale factor for the sensors', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'Voltage scale factor for the sensors'})
    SensorA_SF: int | None = Field(default=None, description='Current scale factor for the sensors', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'Current scale factor for the sensors'})
    SensorHz_SF: int | None = Field(default=None, description='Frequency scale factor for the sensors', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'label': 'Frequency scale factor for the sensors'})
    Sensor1Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor1 Voltage'})
    Sensor2Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor2 Voltage'})
    Sensor3Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor3 Voltage'})
    Sensor4Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor4 Voltage'})
    Sensor5Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor5 Voltage'})
    Sensor6Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor6 Voltage'})
    Sensor7Voltage: int | None = Field(default=None, description='scale of 0-10V', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'V', 'sf': 'SensorV_SF', 'label': 'Sensor7 Voltage'})
    Sensor1Current: int | None = Field(default=None, description='scale of 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor1 Current'})
    Sensor2Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor2 Current'})
    Sensor3Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor3 Current'})
    Sensor4Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor4 Current'})
    Sensor5Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor5 Current'})
    Sensor6Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor6 Current'})
    Sensor7Current: int | None = Field(default=None, description='in 4-20mA or 4-20mA', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'A', 'sf': 'SensorA_SF', 'label': 'Sensor7 Current'})
    Sensor8: int | None = Field(default=None, description='frequency in Hz', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Hz', 'sf': 'SensorHz_SF', 'label': 'Sensor8 frequency'})
    Relay1: int | None = Field(default=None, description='Relay 1 state', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Relay 1 state'})
    Relay2: int | None = Field(default=None, description='Relay 2 state', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Relay 2 state'})
    Relay3: int | None = Field(default=None, description='Relay 3 state', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Relay 3 state'})
    ResetAccumulators: int | None = Field(default=None, description='always 0 in reading, used the code 0xC0DA during the writing for resetting them', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Reset the accumulators'})
    Reset: int | None = Field(default=None, description='always 0 in reading, used the code 0xC0DA during the writing for resetting the system', json_schema_extra={'type': 'uint16', 'size': 1, 'label': 'Reset the system'})
    repeating: list[Model_64020Repeating] = Field(default_factory=list, description='repeating', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 0})
