"""SunSpec model 64111: Basic Charge Controller

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'Model_64111',
    'Model_64111ChargerSt',
]


class Model_64111ChargerSt(SunSpecEnum):
    """Enumeration for point ``Model_64111.ChargerSt`` (enum16)."""
    OFF = 0    # Off
    FLOAT = 1    # Float
    BULK = 2    # Bulk
    ABSORB = 3    # Absorb
    EQ = 4


@register_model
class Model_64111(SunSpecModel):
    """Basic Charge Controller"""

    GROUP_NAME: ClassVar[str] = 'model_64111'
    MODEL_ID: ClassVar[int] = 64111
    MODEL_LABEL: ClassVar[str] = 'Basic Charge Controller'

    ID: int | None = Field(default=64111, description='Model identifier', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 64111})
    L: int | None = Field(default=None, description='Model length', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Port: int | None = Field(default=None, description='Port Number', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'label': 'Port Number'})
    V_SF: int | None = Field(default=None, description='V_SF', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    A_SF: int | None = Field(default=None, description='A_SF', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    P_SF: int | None = Field(default=None, description='P_SF', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    AH_SF: int | None = Field(default=None, description='AH_SF', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    KWH_SF: int | None = Field(default=None, description='KWH_SF', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M'})
    BattV: int | None = Field(default=None, description='Battery Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Battery Voltage'})
    ArrayV: int | None = Field(default=None, description='Array Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Array Voltage'})
    OutputA: int | None = Field(default=None, description='Output Current', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'A_SF', 'mandatory': 'M', 'label': 'Output Current'})
    InputA: int | None = Field(default=None, description='Array Current', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'A', 'sf': 'P_SF', 'mandatory': 'M', 'label': 'Array Current'})
    ChargerSt: Model_64111ChargerSt | int | None = Field(default=None, description='Operating State', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Operating State'})
    OutputW: int | None = Field(default=None, description='Output Wattage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'P_SF', 'mandatory': 'M', 'label': 'Output Wattage'})
    TodayMinBatV: int | None = Field(default=None, description="Today's Minimum Battery Voltage", json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': "Today's Minimum Battery Voltage"})
    TodayMaxBatV: int | None = Field(default=None, description="Today's Maximum Battery Voltage", json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': "Today's Maximum Battery Voltage"})
    VOCV: int | None = Field(default=None, description='VOC', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'VOC'})
    TodayMaxVOC: int | None = Field(default=None, description="Today's Maximum VOC", json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': "Today's Maximum VOC"})
    TodaykWhOutput: int | None = Field(default=None, description="Today's kWh", json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'kWh', 'sf': 'KWH_SF', 'mandatory': 'M', 'label': "Today's kWh"})
    TodayAHOutput: int | None = Field(default=None, description="Today's AH", json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'AH', 'sf': 'AH_SF', 'mandatory': 'M', 'label': "Today's AH"})
    LifeTimeKWHOut: int | None = Field(default=None, description='Lifetime kWh', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'kWh', 'sf': 'P_SF', 'mandatory': 'M', 'label': 'Lifetime kWh'})
    LifeTimeAHOut: int | None = Field(default=None, description='Lifetime kAH', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'kAH', 'sf': 'KWH_SF', 'mandatory': 'M', 'label': 'Lifetime kAH'})
    LifeTimeMaxOut: int | None = Field(default=None, description='Lifetime Maximum Output Wattage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'W', 'sf': 'P_SF', 'mandatory': 'M', 'label': 'Lifetime Maximum Output Wattage'})
    LifeTimeMaxBatt: int | None = Field(default=None, description='Lifetime Maximum Battery Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Lifetime Maximum Battery Voltage'})
    LifeTimeMaxVOC: int | None = Field(default=None, description='Lifetime Maximum VOC Voltage', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'V', 'sf': 'V_SF', 'mandatory': 'M', 'label': 'Lifetime Maximum VOC Voltage'})
