"""SunSpec model 705: DER Volt-Var

Generated by ``interoperability.models.sunspec.generate_models``. Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..common import SunSpecEnum, SunSpecFlags, SunSpecGroup, SunSpecModel, register_model

__all__ = [
    'DERVoltVar',
    'DERVoltVarAdptCrvRslt',
    'DERVoltVarCrv',
    'DERVoltVarCrvDeptRef',
    'DERVoltVarCrvPri',
    'DERVoltVarCrvPt',
    'DERVoltVarCrvReadOnly',
    'DERVoltVarCrvVRefAutoEna',
    'DERVoltVarEna',
]


class DERVoltVarCrvDeptRef(SunSpecEnum):
    """Enumeration for point ``DERVoltVarCrv.DeptRef`` (enum16)."""
    W_MAX_PCT = 0    # Percent Max Watts
    VAR_MAX_PCT = 1    # Percent Max Vars
    VAR_AVAL_PCT = 2    # Percent Available Vars
    VA_MAX_PCT = 3    # Percent Max Apparent Power


class DERVoltVarCrvPri(SunSpecEnum):
    """Enumeration for point ``DERVoltVarCrv.Pri`` (enum16)."""
    ACTIVE = 0    # Active Power Priority
    REACTIVE = 1    # Reactive Power Priority
    VENDOR = 2    # Vendor Power Priority


class DERVoltVarCrvVRefAutoEna(SunSpecEnum):
    """Enumeration for point ``DERVoltVarCrv.VRefAutoEna`` (enum16)."""
    DISABLED = 0    # Disabled Flag
    ENABLED = 1    # Enabled Flag


class DERVoltVarCrvReadOnly(SunSpecEnum):
    """Enumeration for point ``DERVoltVarCrv.ReadOnly`` (enum16)."""
    RW = 0    # Read-Write Access
    R = 1    # Read-Only Access


class DERVoltVarEna(SunSpecEnum):
    """Enumeration for point ``DERVoltVar.Ena`` (enum16)."""
    DISABLED = 0    # Disabled
    ENABLED = 1    # Enabled


class DERVoltVarAdptCrvRslt(SunSpecEnum):
    """Enumeration for point ``DERVoltVar.AdptCrvRslt`` (enum16)."""
    IN_PROGRESS = 0    # Update In Progress
    COMPLETED = 1    # Update Complete
    FAILED = 2    # Update Failed


class DERVoltVarCrvPt(SunSpecGroup):
    """Stored curve points."""

    GROUP_NAME: ClassVar[str] = 'Pt'

    V: int | None = Field(default=None, description='Curve voltage point as percentage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Voltage Point', 'standards': ['IEEE 1547-2018']})
    Var: int | None = Field(default=None, description='Curve reactive power point as set in DeptRef point.', json_schema_extra={'type': 'int16', 'size': 1, 'units': 'DeptRef', 'sf': 'DeptRef_SF', 'access': 'RW', 'label': 'Reactive Power Point', 'standards': ['IEEE 1547-2018']})


class DERVoltVarCrv(SunSpecGroup):
    """Stored curve sets."""

    GROUP_NAME: ClassVar[str] = 'Crv'

    ActPt: int | None = Field(default=None, description='Number of active points.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Active Points', 'standards': ['IEEE 1547-2018']})
    DeptRef: DERVoltVarCrvDeptRef | int | None = Field(default=None, description='Curve dependent reference.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Dependent Reference', 'standards': ['IEEE 1547-2018']})
    Pri: DERVoltVarCrvPri | int | None = Field(default=None, description='Power priority.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Power Priority', 'standards': ['IEEE 1547-2018']})
    VRef: int | None = Field(default=None, description='Vref adjustment as percentage of nominal voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'access': 'RW', 'label': 'Vref Adjustment', 'standards': ['IEEE 1547-2018']})
    VRefAuto: int | None = Field(default=None, description='Autonomous vref value as a percentage of nominal voltage.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'VNomPct', 'sf': 'V_SF', 'label': 'Current Autonomous Vref'})
    VRefAutoEna: DERVoltVarCrvVRefAutoEna | int | None = Field(default=None, description='Enable autonomous vref.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'label': 'Autonomous Vref Enable', 'standards': ['IEEE 1547-2018']})
    VRefAutoTms: int | None = Field(default=None, description='Autonomous vref time constant.', json_schema_extra={'type': 'uint16', 'size': 1, 'units': 'Secs', 'access': 'RW', 'label': 'Auto Vref Time Constant', 'standards': ['IEEE 1547-2018']})
    RspTms: int | None = Field(default=None, description='Open loop response time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'sf': 'RspTms_SF', 'access': 'RW', 'label': 'Open Loop Response Time', 'standards': ['IEEE 1547-2018']})
    ReadOnly: DERVoltVarCrvReadOnly | int | None = Field(default=None, description='Curve read-write access.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Curve Access', 'standards': ['IEEE 1547-2018']})
    Pt: list[DERVoltVarCrvPt] = Field(default_factory=list, description='Stored curve points.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NPt'})


@register_model
class DERVoltVar(SunSpecModel):
    """DER Volt-Var model."""

    GROUP_NAME: ClassVar[str] = 'DERVoltVar'
    MODEL_ID: ClassVar[int] = 705
    MODEL_LABEL: ClassVar[str] = 'DER Volt-Var'

    ID: int | None = Field(default=705, description='DER Volt-Var model ID.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'fixed_value': 705})
    L: int | None = Field(default=None, description='DER Volt-Var model length.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S'})
    Ena: DERVoltVarEna | int | None = Field(default=None, description='Volt-Var control enable.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'DER Volt-Var Module Enable', 'standards': ['IEEE 1547-2018']})
    AdptCrvReq: int | None = Field(default=None, description='Index of curve points to adopt. First curve index is 1.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'mandatory': 'M', 'label': 'Adopt Curve Request', 'standards': ['IEEE 1547-2018']})
    AdptCrvRslt: DERVoltVarAdptCrvRslt | int | None = Field(default=None, description='Result of last adopt curve operation.', union_mode='left_to_right', json_schema_extra={'type': 'enum16', 'size': 1, 'mandatory': 'M', 'label': 'Adopt Curve Result', 'standards': ['IEEE 1547-2018']})
    NPt: int | None = Field(default=None, description='Number of curve points supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Number Of Points', 'standards': ['IEEE 1547-2018']})
    NCrv: int | None = Field(default=None, description='Number of stored curves supported.', json_schema_extra={'type': 'uint16', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Stored Curve Count', 'standards': ['IEEE 1547-2018']})
    RvrtTms: int | None = Field(default=None, description='Reversion time in seconds. 0 = No reversion time.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'access': 'RW', 'label': 'Reversion Timeout'})
    RvrtRem: int | None = Field(default=None, description='Reversion time remaining in seconds.', json_schema_extra={'type': 'uint32', 'size': 2, 'units': 'Secs', 'label': 'Reversion Time Remaining'})
    RvrtCrv: int | None = Field(default=None, description='Default curve after reversion timeout.', json_schema_extra={'type': 'uint16', 'size': 1, 'access': 'RW', 'label': 'Reversion Curve'})
    V_SF: int | None = Field(default=None, description='Scale factor for curve voltage points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Voltage Scale Factor', 'standards': ['IEEE 1547-2018']})
    DeptRef_SF: int | None = Field(default=None, description='Scale factor for curve var points.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Var Scale Factor', 'standards': ['IEEE 1547-2018']})
    RspTms_SF: int | None = Field(default=None, description='Open loop response time scale factor.', json_schema_extra={'type': 'sunssf', 'size': 1, 'mandatory': 'M', 'static': 'S', 'label': 'Open-Loop Scale Factor', 'standards': ['IEEE 1547-2018']})
    Crv: list[DERVoltVarCrv] = Field(default_factory=list, description='Stored curve sets.', json_schema_extra={'type': 'group', 'group_type': 'group', 'count': 'NCrv'})
