"""OpenFMB ``capbankmodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class CapBankControlYPSH(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankControlYPSH``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankControlYPSH'
    AmpLmt: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    AmpThdHi: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    AmpThdLo: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    CtlModeAuto: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    CtlModeOvrRd: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    CtlModeRem: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    DirMode: _common_module.Optional_DirectionModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_DirectionModeKind'})
    Pos: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    TempLmt: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    TempThdHi: _common_module.ControlAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlAPC'})
    TempThdLo: _common_module.ControlAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlAPC'})
    VArLmt: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    VArThdHi: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VArThdLo: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VolLmt: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    VolThdHi: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VolThdLo: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})

class CapBankPoint(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankPoint``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankPoint'
    control: CapBankControlYPSH | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankControlYPSH'})
    startTime: _common_module.Timestamp | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Timestamp'})

class CapBankCSG(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankCSG``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankCSG'
    crvPts: list[CapBankPoint] = Field(default_factory=list, json_schema_extra={'proto': 'capbankmodule.CapBankPoint'})

class CapBankControlScheduleFSCH(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankControlScheduleFSCH``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankControlScheduleFSCH'
    ValCSG: CapBankCSG | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankCSG'})

class CapBankControlFSCC(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankControlFSCC``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankControlFSCC'
    controlFSCC: _common_module.ControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlFSCC'})
    capBankControlScheduleFSCH: CapBankControlScheduleFSCH | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankControlScheduleFSCH'})

class CapBankControl(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankControl``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    capBankControlFSCC: CapBankControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankControlFSCC'})

class CapBankSystem(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankSystem``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankSystem'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})

class CapBankControlProfile(OpenFMBMessage):
    """OpenFMB profile ``capbankmodule.CapBankControlProfile``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    capBankControl: CapBankControl | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankControl'})
    capBankSystem: CapBankSystem | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankSystem'})

class CapBankDiscreteControlYPSH(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankDiscreteControlYPSH``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankDiscreteControlYPSH'
    logicalNodeForControl: _common_module.LogicalNodeForControl | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForControl'})
    control: CapBankControlYPSH | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankControlYPSH'})

class CapBankDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankDiscreteControl``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    capBankDiscreteControlYPSH: CapBankDiscreteControlYPSH | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankDiscreteControlYPSH'})

class CapBankDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``capbankmodule.CapBankDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    capBankControl: CapBankDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankDiscreteControl'})
    capBankSystem: CapBankSystem | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankSystem'})

class CapBankEventAndStatusYPSH(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankEventAndStatusYPSH``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankEventAndStatusYPSH'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    AmpLmt: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    CtlMode: _common_module.Optional_ControlModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_ControlModeKind'})
    DirRev: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    Pos: _common_module.PhaseDPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseDPS'})
    TempLmt: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    VArLmt: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    VolLmt: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})

class CapBankEvent(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankEvent``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    CapBankEventAndStatusYPSH_: CapBankEventAndStatusYPSH | None = Field(default=None, alias='CapBankEventAndStatusYPSH', json_schema_extra={'proto': 'capbankmodule.CapBankEventAndStatusYPSH'})

class CapBankEventProfile(OpenFMBMessage):
    """OpenFMB profile ``capbankmodule.CapBankEventProfile``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    capBankEvent: CapBankEvent | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankEvent'})
    capBankSystem: CapBankSystem | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankSystem'})

class CapBankReading(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankReading``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    secondaryReadingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class CapBankReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``capbankmodule.CapBankReadingProfile``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    capBankReading: CapBankReading | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankReading'})
    capBankSystem: CapBankSystem | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankSystem'})

class CapBankStatus(OpenFMBMessage):
    """OpenFMB message ``capbankmodule.CapBankStatus``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    capBankEventAndStatusYPSH: CapBankEventAndStatusYPSH | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankEventAndStatusYPSH'})

class CapBankStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``capbankmodule.CapBankStatusProfile``."""
    PROTO: ClassVar[str] = 'capbankmodule.CapBankStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    capBankStatus: CapBankStatus | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankStatus'})
    capBankSystem: CapBankSystem | None = Field(default=None, json_schema_extra={'proto': 'capbankmodule.CapBankSystem'})


PROFILES = {'CapBankControlProfile': CapBankControlProfile, 'CapBankDiscreteControlProfile': CapBankDiscreteControlProfile, 'CapBankEventProfile': CapBankEventProfile, 'CapBankReadingProfile': CapBankReadingProfile, 'CapBankStatusProfile': CapBankStatusProfile}
__all__ = ['CapBankCSG', 'CapBankControl', 'CapBankControlFSCC', 'CapBankControlProfile', 'CapBankControlScheduleFSCH', 'CapBankControlYPSH', 'CapBankDiscreteControl', 'CapBankDiscreteControlProfile', 'CapBankDiscreteControlYPSH', 'CapBankEvent', 'CapBankEventAndStatusYPSH', 'CapBankEventProfile', 'CapBankPoint', 'CapBankReading', 'CapBankReadingProfile', 'CapBankStatus', 'CapBankStatusProfile', 'CapBankSystem']
