"""OpenFMB ``loadmodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class LoadPoint(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadPoint``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadPoint'
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    reactivePwrSetPointEnabled: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    realPwrSetPointEnabled: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    reset: _common_module.ControlSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlSPC'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})
    startTime: _common_module.ControlTimestamp | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlTimestamp'})

class LoadCSG(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadCSG``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadCSG'
    crvPts: list[LoadPoint] = Field(default_factory=list, json_schema_extra={'proto': 'loadmodule.LoadPoint'})

class LoadControlScheduleFSCH(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadControlScheduleFSCH``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadControlScheduleFSCH'
    ValDCSG: LoadCSG | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadCSG'})

class LoadControlFSCC(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadControlFSCC``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadControlFSCC'
    controlFSCC: _common_module.ControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlFSCC'})
    loadControlScheduleFSCH: LoadControlScheduleFSCH | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadControlScheduleFSCH'})

class LoadControl(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadControl``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    loadControlFSCC: LoadControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadControlFSCC'})

class LoadControlProfile(OpenFMBMessage):
    """OpenFMB profile ``loadmodule.LoadControlProfile``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    energyConsumer: _common_module.EnergyConsumer | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnergyConsumer'})
    loadControl: LoadControl | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadControl'})

class LoadPointStatus(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadPointStatus``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadPointStatus'
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    reactivePwrSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    realPwrSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    reset: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})

class LoadEventAndStatusZGLD(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadEventAndStatusZGLD``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadEventAndStatusZGLD'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    EmgStop: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    PointStatus: LoadPointStatus | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadPointStatus'})

class LoadEventZGLD(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadEventZGLD``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadEventZGLD'
    loadEventAndStatusZGLD: LoadEventAndStatusZGLD | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadEventAndStatusZGLD'})

class LoadEvent(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadEvent``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    loadEventZGLD: LoadEventZGLD | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadEventZGLD'})

class LoadEventProfile(OpenFMBMessage):
    """OpenFMB profile ``loadmodule.LoadEventProfile``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    energyConsumer: _common_module.EnergyConsumer | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnergyConsumer'})
    loadEvent: LoadEvent | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadEvent'})

class LoadReading(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadReading``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class LoadReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``loadmodule.LoadReadingProfile``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    energyConsumer: _common_module.EnergyConsumer | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnergyConsumer'})
    loadReading: LoadReading | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadReading'})

class LoadStatusZGLD(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadStatusZGLD``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadStatusZGLD'
    loadEventAndStatusZGLD: LoadEventAndStatusZGLD | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadEventAndStatusZGLD'})

class LoadStatus(OpenFMBMessage):
    """OpenFMB message ``loadmodule.LoadStatus``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    isUncontrollable: bool | None = Field(default=None, json_schema_extra={'proto': 'google.protobuf.BoolValue', 'wrapper': 'BoolValue'})
    loadStatusZGLD: LoadStatusZGLD | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadStatusZGLD'})

class LoadStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``loadmodule.LoadStatusProfile``."""
    PROTO: ClassVar[str] = 'loadmodule.LoadStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    energyConsumer: _common_module.EnergyConsumer | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EnergyConsumer'})
    loadStatus: LoadStatus | None = Field(default=None, json_schema_extra={'proto': 'loadmodule.LoadStatus'})


PROFILES = {'LoadControlProfile': LoadControlProfile, 'LoadEventProfile': LoadEventProfile, 'LoadReadingProfile': LoadReadingProfile, 'LoadStatusProfile': LoadStatusProfile}
__all__ = ['LoadCSG', 'LoadControl', 'LoadControlFSCC', 'LoadControlProfile', 'LoadControlScheduleFSCH', 'LoadEvent', 'LoadEventAndStatusZGLD', 'LoadEventProfile', 'LoadEventZGLD', 'LoadPoint', 'LoadPointStatus', 'LoadReading', 'LoadReadingProfile', 'LoadStatus', 'LoadStatusProfile', 'LoadStatusZGLD']
