"""OpenFMB ``regulatormodule`` messages as pydantic models.

Generated by ``generate_models.py`` from the OpenFMB protobuf PSM; do not edit by hand. Field
names follow the protobuf JSON mapping. Unknown fields are rejected so that messages of the
wrong shape fail validation instead of matching nothing.
"""
from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import Field

from .._base import OpenFMBMessage
from .. import common_module as _common_module


class DirectionalATCC(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.DirectionalATCC``."""
    PROTO: ClassVar[str] = 'regulatormodule.DirectionalATCC'
    BndWid: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    CtlDlTmms: _common_module.PhaseISC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseISC'})
    LDCR: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    LDCX: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VolSpt: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    voltageSetPointEnabled: _common_module.PhaseDPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseDPC'})

class RegulatorControlATCC(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorControlATCC``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorControlATCC'
    logicalNodeForControl: _common_module.LogicalNodeForControl | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForControl'})
    DirFwd: DirectionalATCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.DirectionalATCC'})
    DirMode: _common_module.Optional_DirectionModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_DirectionModeKind'})
    DirRev: DirectionalATCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.DirectionalATCC'})
    DirThd: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    ParOp: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})
    TapOpL: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    TapOpR: _common_module.PhaseSPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPC'})
    VolLmtHi: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VolLmtLo: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    VolLmtMode: _common_module.Optional_VoltLimitModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_VoltLimitModeKind'})

class RegulatorPoint(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorPoint``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorPoint'
    control: RegulatorControlATCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorControlATCC'})
    startTime: _common_module.Timestamp | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Timestamp'})

class RegulatorCSG(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorCSG``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorCSG'
    crvPts: list[RegulatorPoint] = Field(default_factory=list, json_schema_extra={'proto': 'regulatormodule.RegulatorPoint'})

class RegulatorControlScheduleFSCH(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorControlScheduleFSCH``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorControlScheduleFSCH'
    ValDCSG: RegulatorCSG | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorCSG'})

class RegulatorControlFSCC(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorControlFSCC``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorControlFSCC'
    controlFSCC: _common_module.ControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlFSCC'})
    regulatorControlScheduleFSCH: RegulatorControlScheduleFSCH | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorControlScheduleFSCH'})

class RegulatorControl(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorControl``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    regulatorControlFSCC: RegulatorControlFSCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorControlFSCC'})

class RegulatorSystem(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorSystem``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorSystem'
    conductingEquipment: _common_module.ConductingEquipment | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipment'})

class RegulatorControlProfile(OpenFMBMessage):
    """OpenFMB profile ``regulatormodule.RegulatorControlProfile``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    regulatorControl: RegulatorControl | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorControl'})
    regulatorSystem: RegulatorSystem | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorSystem'})

class RegulatorDiscreteControl(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorDiscreteControl``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorDiscreteControl'
    controlValue: _common_module.ControlValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlValue'})
    check: _common_module.CheckConditions | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.CheckConditions'})
    regulatorControlATCC: RegulatorControlATCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorControlATCC'})

class RegulatorDiscreteControlProfile(OpenFMBMessage):
    """OpenFMB profile ``regulatormodule.RegulatorDiscreteControlProfile``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorDiscreteControlProfile'
    PROFILE: ClassVar[bool] = True
    controlMessageInfo: _common_module.ControlMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ControlMessageInfo'})
    regulatorDiscreteControl: RegulatorDiscreteControl | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorDiscreteControl'})
    regulatorSystem: RegulatorSystem | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorSystem'})

class RegulatorEventAndStatusATCC(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorEventAndStatusATCC``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorEventAndStatusATCC'
    BndCtr: _common_module.ASG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ASG'})
    BndWid: _common_module.ASG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ASG'})
    BndWidHi: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    BndWidLo: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    DirCtlRev: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    DirIndt: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    DirRev: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    LDCR: _common_module.ASG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ASG'})
    LDCX: _common_module.ASG | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ASG'})
    ParOp: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    rampRates: _common_module.RampRate | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.RampRate'})
    state: _common_module.Optional_StateKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_StateKind'})
    StDlTmms: _common_module.StatusINC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusINC'})
    TapOpErr: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    TapPos: _common_module.PhaseINS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseINS'})
    VolLmtHi: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    VolLmtLo: _common_module.PhaseSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseSPS'})
    VolSpt: _common_module.PhaseAPC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseAPC'})
    voltageSetPointEnabled: _common_module.StatusSPS | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusSPS'})
    DirMod: _common_module.Optional_DirectionModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_DirectionModeKind'})
    VolLmtMode: _common_module.Optional_VoltLimitModeKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.Optional_VoltLimitModeKind'})

class RegulatorEventAndStatusANCR(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorEventAndStatusANCR``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorEventAndStatusANCR'
    logicalNodeForEventAndStatus: _common_module.LogicalNodeForEventAndStatus | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.LogicalNodeForEventAndStatus'})
    DynamicTest: _common_module.ENS_DynamicTestKind | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ENS_DynamicTestKind'})
    PointStatus: RegulatorEventAndStatusATCC | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorEventAndStatusATCC'})

class RegulatorEvent(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorEvent``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorEvent'
    eventValue: _common_module.EventValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventValue'})
    regulatorEventAndStatusANCR: RegulatorEventAndStatusANCR | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorEventAndStatusANCR'})

class RegulatorEventProfile(OpenFMBMessage):
    """OpenFMB profile ``regulatormodule.RegulatorEventProfile``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorEventProfile'
    PROFILE: ClassVar[bool] = True
    eventMessageInfo: _common_module.EventMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.EventMessageInfo'})
    regulatorEvent: RegulatorEvent | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorEvent'})
    regulatorSystem: RegulatorSystem | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorSystem'})

class RegulatorReading(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorReading``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorReading'
    conductingEquipmentTerminalReading: _common_module.ConductingEquipmentTerminalReading | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ConductingEquipmentTerminalReading'})
    phaseMMTN: _common_module.PhaseMMTN | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.PhaseMMTN'})
    readingMMTR: _common_module.ReadingMMTR | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMTR'})
    readingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    secondaryReadingMMXU: _common_module.ReadingMMXU | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMXU'})
    readingMMDC: _common_module.ReadingMMDC | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMMDC'})

class RegulatorReadingProfile(OpenFMBMessage):
    """OpenFMB profile ``regulatormodule.RegulatorReadingProfile``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorReadingProfile'
    PROFILE: ClassVar[bool] = True
    readingMessageInfo: _common_module.ReadingMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.ReadingMessageInfo'})
    regulatorReading: list[RegulatorReading] = Field(default_factory=list, json_schema_extra={'proto': 'regulatormodule.RegulatorReading'})
    regulatorSystem: RegulatorSystem | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorSystem'})

class RegulatorStatus(OpenFMBMessage):
    """OpenFMB message ``regulatormodule.RegulatorStatus``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorStatus'
    statusValue: _common_module.StatusValue | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusValue'})
    regulatorEventAndStatusANCR: RegulatorEventAndStatusANCR | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorEventAndStatusANCR'})

class RegulatorStatusProfile(OpenFMBMessage):
    """OpenFMB profile ``regulatormodule.RegulatorStatusProfile``."""
    PROTO: ClassVar[str] = 'regulatormodule.RegulatorStatusProfile'
    PROFILE: ClassVar[bool] = True
    statusMessageInfo: _common_module.StatusMessageInfo | None = Field(default=None, json_schema_extra={'proto': 'commonmodule.StatusMessageInfo'})
    regulatorStatus: RegulatorStatus | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorStatus'})
    regulatorSystem: RegulatorSystem | None = Field(default=None, json_schema_extra={'proto': 'regulatormodule.RegulatorSystem'})


PROFILES = {'RegulatorControlProfile': RegulatorControlProfile, 'RegulatorDiscreteControlProfile': RegulatorDiscreteControlProfile, 'RegulatorEventProfile': RegulatorEventProfile, 'RegulatorReadingProfile': RegulatorReadingProfile, 'RegulatorStatusProfile': RegulatorStatusProfile}
__all__ = ['DirectionalATCC', 'RegulatorCSG', 'RegulatorControl', 'RegulatorControlATCC', 'RegulatorControlFSCC', 'RegulatorControlProfile', 'RegulatorControlScheduleFSCH', 'RegulatorDiscreteControl', 'RegulatorDiscreteControlProfile', 'RegulatorEvent', 'RegulatorEventAndStatusANCR', 'RegulatorEventAndStatusATCC', 'RegulatorEventProfile', 'RegulatorPoint', 'RegulatorReading', 'RegulatorReadingProfile', 'RegulatorStatus', 'RegulatorStatusProfile', 'RegulatorSystem']
