"""IEEE 2030.5 enumerations.

Generated by ``interoperability.models.ieee2030_5.generate_models`` from the Eclipse VOLTTRON
xsdata dataclasses of the IEEE 2030.5 ``sep.xsd`` schema (commit 804bed4ae5d957341600765c21a99bf3c1daea64). Do not edit by hand.
"""

from __future__ import annotations

import enum

__all__ = [
    'AccumlationBehaviourType',
    'CommodityType',
    'ConsumptionBlockType',
    'CurveType',
    'DERUnitRefType',
    'DataQualifierType',
    'DeviceCategoryType',
    'FlowDirectionType',
    'KindType',
    'PhaseCode',
    'PrimacyType',
    'QualityFlagsType',
    'ResponseRequiredType',
    'RoleFlagsType',
    'RtgAbnormalCategoryType',
    'RtgNormalCategoryType',
    'ServiceKind',
    'SubscribableType',
    'TOUType',
    'UomType',
]


class PrimacyType(enum.IntEnum):
    """IEEE 2030.5 ``PrimacyType`` values."""
    InHomeManagementSystem = 0
    ContractedPremisesServiceProvider = 1
    NonContractualServiceProvider = 2


class DERUnitRefType(enum.IntEnum):
    """IEEE 2030.5 ``DERUnitRefType`` values."""
    NA = 0
    setMaxW = 1
    setMaxVar = 2
    statVarAvail = 3
    setEffectiveV = 4
    setMaxChargeRateW = 5
    setMaxDischargeRateW = 6
    statWAvail = 7


class CurveType(enum.IntEnum):
    """IEEE 2030.5 ``CurveType`` values."""
    opModFreqWatt = 0
    opModHFRTMayTrip = 1
    opModHFRTMustTrip = 2
    opModHVRTMayTrip = 3
    opModHVRTMomentaryCessation = 4
    opModHVRTMustTrip = 5
    opModLFRTMayTrip = 6
    opModLFRTMustTrip = 7
    opModLVRTMayTrip = 8
    opModLVRTMomentaryCessation = 9
    opModLVRTMustTrip = 10
    opModVoltVar = 11
    opModVoltWatt = 12
    opModWattPF = 13
    opModWattVar = 14


class DeviceCategoryType(enum.IntEnum):
    """IEEE 2030.5 ``DeviceCategoryType`` values."""
    PROGRAMMABLE_COMMUNICATING_THERMOSTAT = 0
    STRIP_HEATERS = 1
    BASEBOARD_HEATERS = 2
    WATER_HEATER = 3
    POOL_PUMP = 4
    SAUNA = 5
    HOT_TUB = 6
    SMART_APPLIANCE = 7
    IRRIGATION_PUMP = 8
    MANAGED_COMMERCIAL_AND_INDUSTRIAL_LOADS = 9
    SIMPLE_RESIDENTIAL_LOADS = 10
    EXTERIOR_LIGHTING = 11
    INTERIOR_LIGHTING = 12
    LOAD_CONTROL_SWITCH = 13
    ENERGY_MANAGEMENT_SYSTEM = 14
    SMART_ENERGY_MODULE = 15
    ELECTRIC_VEHICLE = 16
    ELECTRIC_VEHICLE_SUPPLY_EQUIPMENT = 17
    VIRTUAL_OR_MIXED_DER = 18
    RECIPROCATING_ENGINE = 19
    FUEL_CELL = 20
    PHOTOVOLTAIC_SYSTEM = 21
    COMBINED_HEAT_AND_POWER = 22
    COMBINED_PV_AND_STORAGE = 23
    OTHER_GENERATION_SYSTEMS = 24
    OTHER_STORAGE_SYSTEMS = 25
    AGGREGATOR = 99
    OTHER_CLIENT = 100


class RtgNormalCategoryType(enum.IntEnum):
    """IEEE 2030.5 ``RtgNormalCategoryType`` values."""
    not_specified = 0
    category_a = 1
    category_b = 2


class RtgAbnormalCategoryType(enum.IntEnum):
    """IEEE 2030.5 ``RtgAbnormalCategoryType`` values."""
    not_specified = 0
    category_I = 1
    category_II = 2
    category_III = 3


class DataQualifierType(enum.IntEnum):
    """IEEE 2030.5 ``DataQualifierType`` values."""
    Not_applicable = 0
    Average = 2
    Maximum = 8
    Minimum = 9
    Normal = 12
    Standard_deviation_of_population = 29
    Standard_deviation_of_sample = 30


class CommodityType(enum.IntEnum):
    """IEEE 2030.5 ``CommodityType`` values."""
    Not_applicable = 0
    Electricity_secondary_metered = 1
    Electricity_primary_metered = 2
    Air = 4
    NaturalGas = 7
    Propane = 8
    PotableWater = 9
    Steam = 10
    WasteWater = 11
    HeatingFluid = 12
    CoolingFluid = 13


class FlowDirectionType(enum.IntEnum):
    """IEEE 2030.5 ``FlowDirectionType`` values."""
    Not_applicable = 0
    Forward = 1
    Reverse = 19


class UomType(enum.IntEnum):
    """IEEE 2030.5 ``UomType`` values."""
    Not_applicable = 0
    Amperes = 5
    Kelvin = 6
    Degrees_celsius = 23
    Voltage = 29
    Joule = 31
    Hz = 33
    W = 38
    M_cubed = 42
    VA = 61
    VAr = 63
    CosTheta = 65
    V_squared = 67
    A_squared = 69
    VAh = 71
    Wh = 72
    VArh = 73
    Ah = 106
    Ft_cubed = 119
    Ft_cubed_per_hour = 122
    M_cubed_per_hour = 125
    US_gallons = 128
    UG_gallons_per_hour = 129
    Imperial_gallons = 130
    Imperial_gallons_per_hour = 131
    BTU = 132
    BTU_per_hour = 133
    Liter = 134
    Liter_per_hour = 137
    PA_gauge = 140
    PA_absolute = 155
    Therm = 169


class RoleFlagsType(enum.IntEnum):
    """IEEE 2030.5 ``RoleFlagsType`` values."""
    IsMirror = 0
    IsPremiseAggregationPoint = 1
    IsPEV = 2
    IsDER = 4
    IsRevenueQuality = 8
    IsDC = 16
    IsSubmeter = 32


class AccumlationBehaviourType(enum.IntEnum):
    """IEEE 2030.5 ``AccumlationBehaviourType`` values."""
    Not_applicable = 0
    Cumulative = 3
    DeltaData = 4
    Indicating = 6
    Summation = 9
    Instantaneous = 12


class ServiceKind(enum.IntEnum):
    """IEEE 2030.5 ``ServiceKind`` values."""
    Electricity = 0
    Gas = 1
    Water = 2
    Time = 3
    Pressure = 4
    Heat = 5
    Cooling = 6


class QualityFlagsType(enum.IntEnum):
    """IEEE 2030.5 ``QualityFlagsType`` values."""
    Valid = 0
    Manually_edited = 1
    estimated_using_reference_day = 2
    estimated_using_linear_interpolation = 4
    questionable = 8
    derived = 16
    projected = 32


class ConsumptionBlockType(enum.IntEnum):
    """IEEE 2030.5 ``ConsumptionBlockType`` values."""
    Not_applicable = 0
    Block_1 = 1
    Block_2 = 2
    Block_3 = 3
    Block_4 = 4
    Block_5 = 5
    Block_6 = 6
    Block_7 = 7
    Block_8 = 8
    Block_9 = 9
    Block_10 = 10
    Block_11 = 11
    Block_12 = 12
    Block_13 = 13
    Block_14 = 14
    Block_15 = 15
    Block_16 = 16


class TOUType(enum.IntEnum):
    """IEEE 2030.5 ``TOUType`` values."""
    Not_applicable = 0
    TOU_A = 1
    TOU_B = 2
    TOU_C = 3
    TOU_D = 4
    TOU_E = 5
    TOU_F = 6
    TOU_G = 7
    TOU_H = 8
    TOU_I = 9
    TOU_J = 10
    TOU_K = 11
    TOU_L = 12
    TOU_M = 13
    TOU_N = 14
    TOU_O = 15


class KindType(enum.IntEnum):
    """IEEE 2030.5 ``KindType`` values."""
    Not_applicable = 0
    Currency = 3
    Demand = 8
    Energy = 12
    Power = 37


class PhaseCode(enum.IntEnum):
    """IEEE 2030.5 ``PhaseCode`` values."""
    Not_applicable = 0
    Phase_C = 32
    Phase_CN = 33
    Phase_CA = 40
    Phase_B = 64
    Phase_BN = 65
    Phase_BC = 66
    Phase_A = 128
    Phase_AN = 129
    Phase_AB = 132
    Phase_ABC = 224


class ResponseRequiredType(enum.IntEnum):
    """IEEE 2030.5 ``ResponseRequiredType`` values."""
    enddevice_shall_indicate_that_message_was_received = 0
    enddevice_shall_indicate_specific_response = 1
    enduser_customer_response_is_required = 2


class SubscribableType(enum.IntEnum):
    """IEEE 2030.5 ``SubscribableType`` values."""
    resource_does_not_support_subscriptions = 0
    resource_supports_non_conditional_subscriptions = 1
    resource_supports_conditional_subscriptions = 2
    resource_supports_both_conditional_and_non_conditional_subscriptions = 3

